### ISSUE TITLE
Can't access my own kbfs directory

### ISSUE THREAD

**Issue by langri-sha** [keybase/client#10047]
Hello! I've never had any actual luck using my private `kbfs` directory. I've installed the `keybase-bin` package from AUR on Arch Linux, ran `run_keybase`, I can confirm I'm logged in and as far as what I can tell from the system's journal all the Keybase services seem to start ok!

my log id: aa5ff9dcf2f8436867a2591c

**Comment by strib** [comment]
Looks like you have revoked all the devices that had access to that folder have been revoked (`Astrea`, `Laputa`, and the paper key `private service`).   This is likely because you used a PGP key to provision your newest devices, which doesn't give your older devices a chance to rekey.  (We don't allow that anymore.)

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/langrisha because all the devices that have access have been revoked."
```

and post the results here.

**Comment by langri-sha** [comment]
Thanks, that explains it 🙈. Here's the message :lock_with_ink_pen: 

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkFA7mqS FDyJkcVZO88mmwK me00VETFISJ5KjW uVVVaOtibDFzhDh dNSAQqxb8FXi0YF ELNXb1cfJ0lxKPE jMDBiEmJPUpWoLS Jtq128jsIpFde10 aN79iumxliYIsNX Va2w5ljwiyZUlpc cxbC3wQGmg83fTc QxIBa8kn2vDp1MU T1YIRuQloUF3cZ6 xZHkpBQT6LTjlEV VkEjKQcHXFKp53t 8CDzxlmvLvdEKO9 gbEO3SyNaF9pyK4 aTrpvbvKKWpSPtn Cywc2um8ufKzTfL 3NZ6Z98laLYLTRo qc3wTROyLEjCt5U 6jX6OvcAaXl65w4 KzClMz6van3DgnC uupObTLsIdYxFlj Mxa. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by langri-sha** [comment]
Thanks @strib :raised_hands:! I'm all set up now :heart:
