### ISSUE TITLE
No suitable device key found

### ISSUE THREAD

**Issue by InAnimaTe** [keybase/client#10059]
This is more of a question issue around the fact that I can no longer decrypt a file I encrypted on another machine which is no longer alive:

```
└[~/notes/secure]> cat oldies.txt.kbenc | keybase decrypt
Decryption failed; try one of these devices instead:
  * awesome-computer (desktop); provisioned 1 year ago (2016-09-10 16:25:00 EDT)
▶ ERROR decrypt error: no suitable device key found
```

`awesome-computer` has since been decommissioned and is no longer available. I seem to not be understanding how Keybase actually works here though. Why does that specific device need to exist for this file to be decrypted just because the file was encrypted on that device? Is there any way to get this data? What do I need to do in the future to reliably use Keybase as an encryption utility for files?

Thanks for this awesome software tool and your help!

**Comment by cjb** [comment]
Hi! `encrypt for someuser` with `keybase encrypt` means `encrypt for all of the devices owned by someuser right now` -- so in this case you had only one device, it only encrypted for that one, and then you lost it.  :/

So it's not because the file was encrypted on that device, but because that device is the only one that existed for that user at that time.

There's a separate `keybase pgp encrypt` for dealing with encryption to PGP keys instead of Keybase device keys.

**Comment by InAnimaTe** [comment]
Interesting. Definitely will want to use pgp encrypt then since these types of files need to be opened on future or non-enrolled devices in an emergency etc.. I suppose this is a nice feature given a proper use-case, I just was completely unaware the devices would be authoritative staples in the ability to further read the file.

Thanks for the insight.
