### ISSUE TITLE
Cannot delete and then recreate team with same name.

### ISSUE THREAD

**Issue by CypherZealot** [keybase/client#10287]
```
$ keybase team delete team1234
WARNING: This will:

(1) destroy all data in team1234's chats, KBFS folders, and git repositories.
(2) prevent "team1234" from being used again as a team name.

** if you are sure, please type: "nuke team1234" > nuke team1234
Success! Team team1234 deleted.


$ keybase team create team1234
▶ ERROR team already exists (code 2619)`
```

Not able to recreate a team name that I really need after deleting it. Is there some time period defined on how long it is supposed to take to be able to remake a team with the same name?

Really want the team name back that I can't create anymore.

**Comment by tbabej** [comment]
Also encountering this problem.

**Comment by maxtaco** [comment]
By design. We explicitly warn of this limitation.

**Comment by junderw** [comment]
@CypherZealot This is by design. It is also heavily warned. (It says right there in your post:
(`(2) prevent "team1234" from being used again as a team name.`) )

The reason is:

1. Mr. A creates team ABC for all his employees.
2. People join the team sharing super secret info.
3. Mr. A decides he no longer wants to use Keybase, and deletes team ABC.
4. Mr. X, the CEO of ABC corp's competitor takes the team ABC name.
5. Some employees click through rekeying warnings (they don't understand what that means) and continue to post ABC corp secrets to Mr. X's team ABC.

The same thing happens when companies forget to renew domains. Competitors buy the domain and can then receive allllll the email to that domain. Corporate secrets and all.

Once a team is created, you own that team forever. If you delete it, it's deleted forever.

**Comment by CypherZealot** [comment]
Thanks for the explanation. That makes sense. Seems like an important security feature. 

Closing issue.
