### ISSUE TITLE
Because of `keybase chat delete-history`, I can no longer open my team chat on iOS

### ISSUE THREAD

**Issue by huyz** [keybase/client#10339]
I tried the new `keybase chat delete-history [team] --age=1w` command on OSX.   That didn't seem to work as I could scroll back on my laptop.  Then I tried `keybase chat delete-history [team]`, which did work in deleting the entire chat history of the default channel for my team.

But now, when I go to my iPhone client and try to open that channel, the client crashes immediately.

**Comment by maxtaco** [comment]
cc @mlsteele

**Comment by bits01** [comment]
Same problem/crash with the Android app too.

**Comment by mlsteele** [comment]
Could you both do a log send from the phone? It's under settings -> "Feedback".

**Comment by unlocKing** [comment]
same here on iPhone... 

A few times it has opened Keybase app has opened but if I go to the chat that I deleted it keeps crashing again.

**Comment by huyz** [comment]
@mlsteele sent

**Comment by mlsteele** [comment]
Thanks for the log and for reporting this!

This is a bug in the ios and android apps that will be fixed in the upcoming release. We haven't released the mobile apps in a while and I jumped the gun on turning that CLI on. The mobile version doesn't understand delete-history yet and unfortunately crashes. As soon as the next app update comes around your conversations will start working again.

In the meantime you can continue to use the desktop, or do silly hacks like make a chat with an extra person or use another team.

This is the same issue as https://github.com/keybase/keybase-issues/issues/3168

**Comment by mlsteele** [comment]
Could anyone confirm that the conversations that were broken are now fixed with new mobile apps?

**Comment by huyz** [comment]
The conversation was fixed days before the new mobile apps. As if you fixed it on the server or as if the client automatically downloaded new code (which could it be?)

**Comment by mlsteele** [comment]
Huh. I didn't do anything on purpose on the server. Could be something cleared your cache and somehow that worked. The mobile apps were out a few days ago, maybe you autoupdated? Anyway glad it's fixed! I'll re-enable the CLI later today.

**Comment by huyz** [comment]
I don’t think it was the cache because I had already tried to reinstall the iOS app before and that hadn’t fixed it. This time, I didn’t do anything and it worked magically. I don’t have auto-update enabled for my App Store settings. 
I checked that it worked after my friend told me it had been magically fixed on his Android device as well (same shared team conversation, btw). So it wasn’t just me.
