### ISSUE TITLE
Unable to rekey private folder

### ISSUE THREAD

**Issue by jimcavoli** [keybase/client#10464]
After re-ordering addresses on my private key, the private area of kbfs locked up and is prompting me to open the app, but opening the app doesn't clear the issue and doesn't actually rekey the folder. I also happen to have needed to reissue paper keys and, unfortunately, did that after the identity reordering rather than before. I'm not sure how to get the private share un-screwed, and loss of the old folder is acceptable.

my log id: 3999174bacf52de9d5bd391c

**Comment by strib** [comment]
Sorry for the bad behavior.  It looks like this is stemming from an issue when you created the folder way back in July 2016, and then shortly after that you reset your account.  Back then we didn't handle account resets properly, so I think the folder has been broken since then.  Reordering identities in a PGP key doesn't affect KBFS, as we don't use PGP at all for that.

Probably the best thing to do is to reset the folder.  If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/jimcavoli because all the devices that have access have been revoked."
```

and post the results here.

**Comment by jimcavoli** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkIHZyuP XlYv7l38GPopSXT zUlrQdJTT55kvu2 YuAsJgjwMkpVctw sdLGW8Nu9B9ltib pUUepF3lUGHnuyo oqzEIE7U1Xdswop bsULK435p6fryZM lBfMR3U9EvAIon7 rsgv8ZbK2YLAWE6 DkBv4UFcs5A92h2 2WDzTCzWqfWYjGC itZYrqZAdBuP74Q m4wk9BQTCJNQrc5 rptA4RM5N5fgaQQ PS5WvcZ6sTcGCK6 lwDBFSKfS4ejXGE pvmpspFbi905CZ0 tY5LkBMHOgooIFM KOkpHO6K3ckl6VW ft6BeaT4sYI0jb1 S5zGqPnq1NfLQz3 aE3FLt9Vhr6Y9Yp rEE. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

Getting rid of the rekey request badge should happen the next time we update our server code (likely within the next few days).
