### ISSUE TITLE
Windows 10 update not available after new release

### ISSUE THREAD

**Issue by matthewpucc** [keybase/client#10484]
For the past few weeks I have been getting prompts to update the Windows 10 client. When I try to apply the update, the installer does not have an install/upgrade option. It only has a repair option.

So far I've uninstalled and reinstalled from a fresh download. After the first update, the issue started appearing again.

I am on Windows 10, build 17083.
Keybase version is 1.40.0.19

**Comment by maxtaco** [comment]
cc @zanderz

**Comment by zanderz** [comment]
Can you do a `keybase log send` and post the ID? Thanks.

**Comment by matthewpucc** [comment]
Report ID: acb1b8c8282f4ee62e97dd1c

**Comment by zanderz** [comment]
Sure enough, those updates are failing, so the updater keeps pestering you. Since this happened over more than one version iteration, I wonder if you have some extra security settings/policies enabled? The installer seems to get stuck thinking files are in use. You should be able to get around this by uninstalling and then downloading again from keybase.io - your settings and device provisioning won't be affected. Upcoming versions may solve this, we're working on it. Thanks!

**Comment by matthewpucc** [comment]
I don't intentionally have any security settings/policies in place. It is just normal windows settings. I'll continue applying the versions manually.

**Comment by zanderz** [comment]
@matthewpucc One reason the upgrade failed is because files were still in use, caused by a bug we have since fixed. Are you able to upgrade yet? You may need to uninstall + reinstall. Sorry for the hassle.

**Comment by matthewpucc** [comment]
@zanderz I was successfully able to update to 1.0.44.1 yesterday actually. Good job on the patch! I'll let you know if I see any failures in the future.
