### ISSUE TITLE
Windows10: cannot upload 50MB file with KBFS

### ISSUE THREAD

**Issue by gaaned92** [keybase/client#10958]
Keybase GUI Version: 1.0.45-20180305115557+3a1c65a

I have about 1 GB of data uploaded.
When trying to upload 50MB file by copying in KBFS/public/gaaned92 with explorer, speed decreases and I get this error message:
error 0x8000705AA : insufficient system resources

If I copy with command line it says : file too large

Until now it was working without problem

I have a lot of free disk and memory  space.

**Comment by strib** [comment]
@gaaned92 can you please do `keybase log send`?

It might be that the _directory_ is too large, if you have a ton of files with really long names in it.

**Comment by gaaned92** [comment]
Done
 log id: 9b67b5a6c29d8487763c5b1c

**Comment by strib** [comment]
@gaaned92 looks like there's some corruption in one of the local files we use for buffering your data.  I see this error in the logs:

```
Error when enabling journal for 66a40672ac4fb3797ff8d774098ce617: strconv.ParseUint: parsing "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00": invalid syntax
failed to parse "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
```

which is weird, but I've seen similar things before, we need to make improvements there.  As a result, your KBFS wasn't buffering data on the local disk, it was trying to flush it out over the network immediately.  That doesn't work so well with big files, and it was failing internally with a timeout.  (It's hard to give accurate error codes back to windows over the file system interface, so the errors are confusing.)

I think you can fix it by:

1. Stopping Keybase/KBFS so that the K: drive is no longer mounted.
2. Moving any directories in `%appdata%\Local\Keybase\kbfs_journal\v1\` to some place else, to get them out of the way.
3. Restarting Keybase/KBFS.

That should get you using the local disk for buffering again.  Let me know how it goes, and sorry for the inconvenience.

**Comment by gaaned92** [comment]
@strib  Thank you, it's working again.

Question: is there a clean way to stop and restart KBFS?

**Comment by strib** [comment]
You should be able to quit from the Keybase app menu, and restart using the app shortcut.  Does that work?

**Comment by gaaned92** [comment]
It works.
Thank you for fast answers
