### ISSUE TITLE
Cannot open folders on Windows 10

### ISSUE THREAD

**Issue by etamponi** [keybase/client#11209]
I just installed Windows 10 and Keybase, but I can't access the Keybase folders. K:/ does not appear in Explorer either. I tried to run Repair from the installer with no success.

Keybase GUI Version: 1.0.47-20180403200126+d3b2e30

**Comment by zanderz** [comment]
Can you perform a `keybase log send` at the CLI and post the log ID? Thanks.

**Comment by joshsleeper** [comment]
Same boat here.

* windows 10 pro version 1709 (os build 16299.334)
* keybase client + service version `1.0.47-20180403195507+d3b2e30`

my log id: `e179118b5f6400e1a9c88a1c`

**Comment by brush701** [comment]
same here, windows 10 pro 1709 (build 16299.309)
keybase client + service: 1.0.47-20180403195507+d3b2e30
log id: f48ebd9f381a4940b89f101c

**Comment by zanderz** [comment]
Sorry everyone, we shipped a bug which will cause this on a fresh install (not an upgrade). If that's you, it can be fixed by entering `keybase kbfsmount set K` (or whichever letter) and totally exiting Keybase and restarting (or just rebooting).

**Comment by brush701** [comment]
Worked for me, thanks!

**Comment by joshsleeper** [comment]
hrmm, that didn't resolve it for me unfortunately.
That said, I should've been more clear.
I'm not a fresh install, I've been through many, many months of keybase updates and am just recently seeing this issue.

**Comment by zanderz** [comment]
@joshsleeper No idea why kbfs wouldn't be running - you can send another log for that. As to your previous log, the filesystem mount fails with a message documented by Dokan as "Dokan mount failed - Can't install driver." This might be because it can't find the dll, or maybe the service isn't working. There are a couple of ways to try the service:
- type `sc query dokan1` at the CLI and make sure status is 4, RUNNING
or
- Open CLI as admin and go to `%programFiles%\Dokan\Dokan Library-1.1.0\sample\mirror`, and run `mirror /r [testdir] /l [mountletter]` and make sure you can browse the given directory at the given mount letter
If the mirror sample is not present, you can uninstall Dokan and install it from https://github.com/dokan-dev/dokany/releases/download/v1.1.0.2000/DokanSetup_redist.exe

**Comment by joshsleeper** [comment]
thanks for the detailed response!

findings:
* `sc query dokan1` didn't seem to return anything. No errors, no message.
* my dokan directory shows version `1.0.0` instead of `1.1.0` (I've never manually installed/uninstalled dokan as far as I can remember, so not sure why.)
* my dokan install doesn't have the `sample` dirname, so I can't test with `mirror`
* when I go to uninstall dokan, it lists it as version `1.0.4.84 (x64)`
* uninstalled dokan and reinstalled using `DokanSetup.redist.exe` you linked
* since `sample` was present in the `1.1.0` dokan directory, I did the `mirror` test which worked as expected
* `sc query dokan1` responded the same after installing `1.1.0`: still no return error/message.
* same keybase gui experience

new logs: `2d768305ae0a4304e36db01c`

Also, interesting tidbit I forgot to mention earlier. I'm seeing the following message when calling `keybase log send`:

    - INFO ignoring UI logs: GUI main process wasn't found

**Comment by zanderz** [comment]
@joshsleeper The filesystem mounted ok this time. During the last run shown in these logs, it now looks like kbfs can't reach its servers. Are you behind a firewall or some corporate network? @strib
```
2018-04-05T09:44:05.227814-07:00 - [DEBU kbfs init.go:358] 00b Using remote mdserver mdserver-0.kbfs.keybaseapi.com:443,mdserver-1.kbfs.keybaseapi.com:443;mdserver-0.kbfs.keybase.io:443,mdserver-1.kbfs.keybase.io:443
2018-04-05T09:44:05.227814-07:00 - [WARN kbfs connection_log.go:65] 00c (CONN KeybaseDaemonRPC 747d2a94) Connection: error dialing transport: Access is denied.
2018-04-05T09:44:05.227814-07:00 - [WARN kbfs keybase_daemon_rpc.go:339] 00e KeybaseDaemonRPC: connection error: "Access is denied."; retrying in 2s
2018-04-05T09:44:05.227814-07:00 - [DEBU kbfs connection_log.go:71] 00d (CONN CryptoClient 0434468f) Connection: dialing transport
```

**Comment by joshsleeper** [comment]
I am behind a corporate firewall on this system, so it's very possible that they changed something and that's affecting this.
That said, I may've gotten it working again?

I killed all keybase related processes in task manager and started everything completely fresh, and it seems to have come up just fine. Interesting!

I've got one more batch of logs in case you can find anything useful from them, but for now I guess I'm back in action. Thanks so much for the debugging assistance @zanderz!!

`3b44849c263e90e23b5e8b1c`

**Comment by zanderz** [comment]
:thumbsup:

**Comment by etamponi** [comment]
Yes, the suggestion provided fixed my issue :) Thanks!

**Comment by beakface** [comment]
I am on Windows 10, haven't upgraded recently, yet I can now not open keybase, either using command line or GUI.  It looks like a window very briefly flashes and then closes.  I could use keybase just fine as of a month ago.
