### ISSUE TITLE
Notifications fail, after iOS settings reset

### ISSUE THREAD

**Issue by moxx** [keybase/client#11263]
After a settings reset on my iPhone also Apps where deleted from Settings>Notification`s. Most apps like whatsapp... aks me again for enable Notifications and the default "iOS Notification"was displayed.

Keybase only give me the personal hint to enable Notifications but no "iOS Notification prompt" will displayed to grant Access again for displaying Notifies. So Keybaseinst listed under "Settings>Notification`s" and Notifications cant be activeded again.

Solution:
1.  remove keybase from device
2. revoke device
3. setup keybase and device again

It would be nice if i pressed on the personal keybase notification hint "Got it" do check again push:permissions and if the are no, prompt again.

**Comment by reedriley** [comment]
I'm hitting this issue as well, on the current latest version of the Keybase iOS app.

**Comment by malgorithms** [comment]
hmm, is the hamburger icon inside the app badged (the bottom right tab on the app), leading to the in-app notification setting? if the app thinks it hasn't gotten you to try to turn on notifications, it's supposed to lead you to something that asks from there. 

it seems like the app has never explicitly asked for permission, which is why it's missing from the ios settings. but if that's the case our app is supposed to try pretty hard to lead you to the in-app settings where it explains it's important to turn it on, and you can click a button to ask for it. 

cc @chrisnojima

**Comment by reedriley** [comment]
When I open the app, I see a "Please turn on notifications!" interstitial.  If I follow it - I'm taken to the "Settings -> Keybase" options page, which don't include anything about notifications.

If I return to the app, the "hamburger" icon is not badged.  However, the "notifications" entry within the "settings" view (after clicking on the "hamburger") is badged.  There's an inline warning about having turned off native notifications for Keybase, and a link.  If I click that link, I'm taken to the "Settings -> Keybase" options page, which don't include anything about notifications.

**Comment by malgorithms** [comment]
ah this is a helpful explanation, thanks.

it seems the app is confused and thinks it has already asked you...the behavior is supposed to be:

(1) if it has never asked you, then ask you
(2) if it has asked you, then link to settings screen

for some reason internal tracking of this is wrong.

Also, I believe the menu item should be badged at the top level. Our app is really not useful unless notifications are turned on, so it's supposed to lead you there.

**Comment by reedriley** [comment]
Right.  And I *want* to turn them on - Keybase is an awesome app!  I just can't figure out how....

They got turned off for the same reason as the original poster - I used the "Reset Settings" feature built into iOS and it has a side effect of resetting all notification permissions.  (In my case - to deal with a hard to reproduce issue involving location services that may have indicated corrupt iOS settings.)

**Comment by malgorithms** [comment]
ahh very helpful that "reset settings" is the cause in both cases. maybe we can detect this has happened. thanks

**Comment by MindTooth** [comment]
Still an issue with the latest version that arrived a couple of days ago.

**Comment by chrisnojima** [comment]
We haven't fixed it yet

**Comment by mjgw** [comment]
> @mjgw are you talking about missing notifications in general or you're in this case where a bunch of people have reset their settings on their device and are in this state

I'm not specifically referring to the problem having been caused by an iOS reset, but am referring to the KB app being unable to restart receiving notifications in the case where something has caused them not to be sent. I'm not clear in all cases what specific issues prevented some team members from receiving notifications, but they did not turn them off or do anything drastic with their devices. It was more that the functionality for resetting this aspect of the app did and does not work reliably. Fixing this by allowing greater control over notifications, and the ability to turn them on and off as necessary, as other apps do, would solve the above issue, as well as any other notification/sync issues.

**Comment by interpolack** [comment]
@chrisnojima once someone has opted to disable notifications (when initially prompted by the app), there is no way for them to enable notifications thereafter. the link that says "Enable notifications" from within the app does not work, and Keybase does not appear in iOS notification settings. revoking the device and reinstalling the app does not fix the issue. i hope this helps. really eager for a couple of my teams to be able to receive mobile notifications.

**Comment by interpolack** [comment]
i'm running keybase 2.11.0 but an outdated version of iOS. if that's the problem sorry for making this more complicated.

**Comment by chrisnojima** [comment]
The iOS version shouldn't matter in this case. Thanks for the update!

**Comment by chrisnojima** [comment]
There's going to be a new version out soon but it will not contain this fix. The next version will

**Comment by chrisnojima** [comment]
on ios 12.1.4 after doing a `Reset All Settings` and `Rest Network Settings` Keybase lets me redo the notification settings. So I can no longer repro this situation. If this happens to you please reopen and give me some details

**Comment by boxxa** [comment]
I have this happening on my iOS and Mac. I think I disabled them on setup of my account. Now I only have the following option under mobile for notifications. Unable to get any other notifications on Mac or iOS
