### ISSUE TITLE
Implement a way to "Freeze" Devices

### ISSUE THREAD

**Issue by JadonZufall** [keybase/client#12081]
Well you can revoke devices from other devices there should be an option to freeze then temporarily disable them until you thaw them or enable them again.

**Comment by dabura667** [comment]
That would be the exact same as revoking and then re-adding.

I guess you could add a flag to the revoke sigchain to say “display this as “frozen” not “revoked”...” but I really don’t see the point.

In order to record the freeze you need to write to the sigchain. In order to prevent a frozen device to decrypt etc. you need to rekey. In order to unfreeze a device you need to share the encryption keys and write to the sigchain.

Which is literally exactly what happens when you revoke a device and then re-add it.
