### ISSUE TITLE
Cannot create, push, or fetch from keybase git remotes

### ISSUE THREAD

**Issue by akatrevorjay** [keybase/client#12101]
Hi. I get this cryptic error message that I wish I had more time to debug:
```
$ git pull
Initializing Keybase... git remote done.
Syncing with Keybase...must be at least 1 (bad fields: seqno) (error 100)
git-remote-keybase error: (1) must be at least 1 (bad fields: seqno) (error 100)
```

Any ideas? Seems to happen across at least two of my computers too. Both Linux though.

**Comment by strib** [comment]
@akatrevorjay Yeah this is a bug I was just working on today.  I think it happens when you're trying to access a folder that was last written by a device that has been revoked kind of a long time ago.  (If that's not the case here, let me know.)  The context is that we're starting to get stricter about the checks that we do around data written by now-revoked devices, but for some older revokes, that data might not be available and right now we're conservatively failing.

keybase/kbfs#1593 will give a better error message in this case; I will merge that soon and it will show up in the next daily linux build.

A longer term fix involves transitioning to a slightly different check that requires a bit of coordination within the app, and it'll probably take a few days to get that done.

In the meantime, I'm afraid I don't have an easy way to fix this for you.  It seems like the best option is just to roll back that check completely and then add it back again later when the long-term fix is ready.  I'll discuss it internally and hopefully we can get something out soon.

**Comment by akatrevorjay** [comment]
Hi! I have not seen this be fixed as of yet unfortunately, same error. I'm fully up to date (using the apt repository). Any idea? :)

**Comment by strib** [comment]
@akatrevorjay can you please do another `keybase log send`?  You definitely shouldn't be seeing the same error on the latest linux build.

**Comment by akatrevorjay** [comment]
I'll have to do it tomorrow, apparently my primary machine has lost access to my private folder, which is strange.

Can I not use my phone to rekey a folder?

**Comment by strib** [comment]
> Can I not use my phone to rekey a folder?

You can.  But the same bug we're talking about above prevents rekeys and private folder access. You can run `keybase log send` from any device where you tried to access your folder, even if it didn't work, and I can debug it with those logs.

**Comment by akatrevorjay** [comment]
Oh. Lol. Great. Yeah, because my private folder *definitely* worked on this laptop before. Where should I send logs?

**Comment by strib** [comment]
@maxtaco @mikem this is another implicit team with a manually reset KBFS folder.  We should delete the team: `f2a696f9227da68f0733def90fbe0924`.

**Comment by strib** [comment]
@akatrevorjay you situation should be cleaned up now.  Can you check it out and close this issue if things look ok?

**Comment by akatrevorjay** [comment]
@strib All fixed. Note: I had to recreate all repos. No biggie in this case however!

**Comment by akatrevorjay** [comment]
Thanks!
