### ISSUE TITLE
Rekey impossible

### ISSUE THREAD

**Issue by InTheFlipside** [keybase/client#12290]
http://prntscr.com/jt9ujq

Impossible to rekey this folder. (already have a new paper key)

**Comment by strib** [comment]
@InTheFlipside maybe you lost/revoked all your previous devices and now there are no devices that can rekey it.  We can reset it for you if you want.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/filpside because all the devices that have access have been revoked."
```

and post the results here.

**Comment by InTheFlipside** [comment]
`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkMT1xSL jysgVXKg6MRmLZU DyNxPFa3WI8afXe OyVo3Vdiy3MXe5F Z2irofYi6EQQssR 4eyywGdg3temtHj IczAyGtXeLDBCvd fPi15WUKuSafsUK DfGQysAke78NJzc vUhgmteFRUqO1VU lU4QNsijGneFcv1 WkuazFymfFVaOCb XysMhwwEDnwZGZE qLjbEPheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvldOu0x3s IEUa4oBy89aTILo 7mStmuDEWr1H0cq MOzQeKGi6ahq0NF L2o193Xn0VhE4nd Xnsmxi9scmClEW9 ovbAherEAI. END KEYBASE SALTPACK SIGNED MESSAGE.` 

Sended, thank :)

**Comment by strib** [comment]
@InTheFlipside I looked into this a little and saw that your folder is still keyed for your device `SourceCode`, which hasn't yet been revoked.  Assuming that device is still online somewhere, I think the probably is likely a bug that is preventing your rekey.  (I could tell for sure if you do a `keybase log send` from `SourceCode` and post the resulting log ID here.)

Depending on your operating system, you could try upgrading, though the bug fix isn't released on all platforms yet.  If it hasn't been released yet, you might be able to use an experimental build instead of waiting for the next release on your platform.

If you'd rather I just reset your folder anyway, that's fine too, just confirm that you want that.  I just like avoiding resets if possible.

**Comment by InTheFlipside** [comment]
@strib 
Thanks for your answer
SourceCode is deleted. (It was my previous windows). I revoked it. (sended `keybase log send`, before and after) 

Can you reset this folder please? I gave up a little bit to find a solution 
( i doubt that it contain important files. I don't remember but it doesn't have importance) 

thank a lot !

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by InTheFlipside** [comment]
everything is okay
thanks :)
