### ISSUE TITLE
Preventing Idle Sleep on macOS

### ISSUE THREAD

**Issue by nickoneill** [keybase/client#12822]
I'm running 2.3.0 on 10.12.6, and I noticed over the last few days that my desktop isn't sleeping after 10 minutes like it used to. Some investigation is pointing me at the Keybase client / Electron.

`pmset -g assertions` says this with the Keybase client open:
`pid 5142(Keybase): [0x0000ed0c0001a045] 00:30:02 NoIdleSleepAssertion named: "Electron"`

And fully quitting keybase (removing keybase from the menu bar) removes that line and allows the machine to sleep at idle again.

It looks like 2.3.0 was released a few days ago, which corresponds to the timeline of my sleep issues.

**Comment by maxtaco** [comment]
cc @mmaxim

**Comment by MoritzFago** [comment]
It looks like https://github.com/keybase/client/pull/12721 has introduced this "feature". According to the discussion in the PR it was to fix something that happened because the app went sleeping. I couldn't find any info why this is a bad thing, I understand why the daemon shouln't sleep but not why the app shouldn't. This makes the current version of keybase unusable for me.

**Comment by sociallymellow** [comment]
+1

**Comment by maxtaco** [comment]
Backed this out in https://github.com/keybase/client/pull/12826.

The behavior we saw was that after electron came back from sleep, it was in a broken state. Hard to test.

**Comment by skannan-maf** [comment]
Just close your laptop and then reopen immediately... You will most likely hit this issue.... 
Anyone know how to solve? Will killing the offending PID work?
PS:
In my case, the pmset output had a clue. It said "pid 99988(Code): "
So I exited VS code and thats it. All solved.
