### ISSUE TITLE
Keybase GUI asking me to rekey

### ISSUE THREAD

**Issue by wsargent** [keybase/client#13107]
Hi there,

I have a Keybase account under https://keybase.io/will_sargent.  I have been getting emails and the GUI asking me to rekey, so that I can access my account -- I've done this multiple times and it seems to have absolutely no effect, on the front end or on the backend.  Any ideas?

Keybase GUI Version: 2.3.0-20180710171051+64615d6258

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by wsargent** [comment]
7883f52c4ee7985df74bf21c

**Comment by strib** [comment]
Well this sucks.  It looks like you haven't written to your private folder in months, and now somehow it's in a bad state where it can't be read (and hence, can't be rekeyed).  The error beneath the hood is "block does not exist", which means we had some internal bug that left your folder in an unreadable state.  Basically, what I think happened is your client (due to a bug) never uploaded some crucial piece of data to our servers.  And it was done by some device that is now revoked, and so I can't even ask you for logs to try to debug it.

Very sorry about this.  One thing I can try to do is roll the state of the folder slightly backward, and see if that helps.  You might lose access to the very last thing you wrote to the folder, depending on what that operation was.  (i.e., if it was a delete, something might re-appear, etc.)

Do you want me to try this?

**Comment by strib** [comment]
@wsargent ok I rolled back the folder a little bit. Please check it out from one of your older devices (might require a Keybase restart) and see if things look ok.  I wouldn't be surprised if there's another error, so if you can't read your private folder still, please do another `keybase log send` and let me know.

**Comment by wsargent** [comment]
Looks fine, thanks
