### ISSUE TITLE
My personal private folder is requesting a rekey, but rekeying with my paper key does nothing

### ISSUE THREAD

**Issue by miztroh2** [keybase/client#13222]
![screenshot from 2018-08-08 16-02-04](https://user-images.githubusercontent.com/40702740/43864189-a91fa4fc-9b24-11e8-94be-40489d089388.png)

my log id: c223fbd0390d563ffe0dbb1c

**Comment by strib** [comment]
Hi @miztroh2 I'm looking at your logs right now.  It seems (like #13107) that your folder is missing some data on our servers.  It looks like it happened on July 13th, due to a write you made from the same device you sent logs from.  Unfortunately the logs you sent only only include data from today.  Is there any chance you have old KBFS log files left in `~/.cache/keybase/` that you can share?

In any case, I can try rolling your folder back a little bit in time, to see if that solves the issue for you.  You may lose whatever was written in your last update though.  Another possibility would be giving you a modified Keybase release that could overlook and/or try to repair the missing data, to let the rekey go through.

Arg, I hope to track this down soon, but I have no idea what the root cause is without seeing logs from around the time it happened.

**Comment by miztroh2** [comment]
Go ahead and roll it back.  I recently reinstalled my OS, so I'm afraid I don't have the logs you're requesting.  You'll notice some device add / removes.  Thank you!

**Comment by miztroh2** [comment]
Looks good.  Thanks!

**Comment by szaffarano** [comment]
I have the same error.  Recently I changed my computer, and after reinstalled keybase, I'm not able to access my private folder.  I tried doing a rekey with my paper key, but it seems that doesn't work

**Comment by strib** [comment]
@szaffarano please do a `keybase log send` and open a new issue including the log ID, we don't look at closed issues.

**Comment by szaffarano** [comment]
> @szaffarano please do a `keybase log send` and open a new issue including the log ID, we don't look at closed issues.

@strib I already did it.  Please see issue #21456 

Thanks
