### ISSUE TITLE
Keybase Finder filesystem stopped working on Mac OS Mojave Developer Beta

### ISSUE THREAD

**Issue by docdyhr** [keybase/client#13552]
After installing Mojave macOS 10.14 (18A377a) beta - The Keybase Finder filesystem integration stopped working on all my Macs running Mojave. When trying to access the files Finder hangs. Even in Terminal when cd'en into the folders Terminal hangs.

- I tried to remove Keybase and reinstall from the web with no success.
- And I have tried reenable from within Keybase Settings Files Window with no success. 

What to do?

**Comment by strib** [comment]
Please start with a `keybase log send`, and post the resulting log ID.

**Comment by cheynen** [comment]
I have two accounts. This is because I was receiving errors stating that my Profile could not be found and my follow status could not be read. If there is a tiny limit for activity such as joining groups or following people, should that not be stated clearly? And perhaps the error message should be modified? I don't know if this is the complete issue, but it must be part of it?

my log id: e08bfe66988937c1b29f871c

**Comment by strib** [comment]
Discussion of Mojave KBFS issues on #13537.
