### ISSUE TITLE
Support Zcash Sapling addresses in profile

### ISSUE THREAD

**Issue by garethtdavies** [keybase/client#14364]
On October 28th Zcash will upgrade to Sapling. In doing so it will enable the more efficient Sapling transactions. These Sapling addresses have a different format and it isn't possible to add these new addresses to the Keybase profile.

Old style: `zcA6qngiR3U7HxYopyTWkaDLwYBd83D5MT7Jb9gpgTzPLMZytzRbtdPP1Syv4RvRgHeoZrJWSask3DyfwXG9DGPMWMvX7aC`

New style: 
`zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly`

While the legacy Sprout z-addresses will continue to function after Sapling activates given the benefits of Sapling it's likely they see far greater adoption so support for them would be most welcome!

**Comment by maxtaco** [comment]
Thank you for the update, we will try to make this change as soon as we can.

**Comment by maxtaco** [comment]
@garethtdavies  do you  have a reference for how to consume and error-check these addresses? Details are scarce as far as I can tell, the the Bitcoin Bech32 scheme doesn't seem to work out of the box.

**Comment by maxtaco** [comment]
In node, I tried this:

```bash
$ npm i bech32
```

```iced
bech32 = require 'bech32'
bech32.decode('zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly')
```

That yields an invalid checksum. This works thought:

```iced
bech32.decode('zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkn3pxg7n')
```

Similar results with Golang library I found.

**Comment by jasondavies** [comment]
I think @garethtdavies gave you an invalid Sapling address by mistake, that's why it doesn't validate.  You can validate a z-addr using zcashd, using the `z_validateaddress` RPC call.

Regarding validation itself: that's slightly more complicated to fully reflect what zcashd does but I will post further details here when I get a chance.  You will need to check the following:

* Prefix is "zs"
* Number of words is 69.
* Check total number of bits is within the expected range when converting from base 32 to base 256.

Do you typically use Node.js within keybase for this kind of check?

**Comment by maxtaco** [comment]
That would explain it! I think this address shows up in the official Zcash docs too, see this screenshot from [this URL](https://zcash.readthedocs.io/en/latest/rtd_pages/payment_api.html).  Also, it shows up in the [official blog post](https://z.cash/blog/whats-new-in-sapling/).  I saw the details about what's inside in the spec, but the spec was mute on what happens one layer up, aside from saying Bech32.  We do some server-side node, but we're using Go on the client side. That branch above shows that I was trying [this library](https://github.com/btcsuite/btcutil) for decoding.

(https://zcash.readthedocs.io/en/latest/rtd_pages/payment_api.html)
<img width="1126" alt="screen shot 2018-10-29 at 1 39 46 pm" src="https://user-images.githubusercontent.com/866815/47668953-24882880-db80-11e8-8655-e0d44b2a3c35.png">

**Comment by samosudov** [comment]
@maxtaco
I use this Bech32 implementation with small changes (https://github.com/bitcoinj/bitcoinj/blob/2ec193f8479425c3a66bebf5f2d3493e39e88f7c/core/src/main/java/org/bitcoinj/core/Bech32.java)
- don't check a length of address when you decode it - https://github.com/bitcoinj/bitcoinj/blob/2ec193f8479425c3a66bebf5f2d3493e39e88f7c/core/src/main/java/org/bitcoinj/core/Bech32.java#L129
because it may be more than 90.
- convert bits before pass it to encode like this (https://github.com/Electron-Cash/Electron-Cash-Java/blob/8e9f323190b355ca1c24025bbaaf0e6411086d7c/BitcoinCashBitArrayConverter.java)
from 8 to 5
- and you can check the length of byte here (https://github.com/bitcoinj/bitcoinj/blob/2ec193f8479425c3a66bebf5f2d3493e39e88f7c/core/src/main/java/org/bitcoinj/core/Bech32.java#L119)
if it more than 32 you don't write a symbol in the address string.

**Comment by garethtdavies** [comment]
Great catch @jasondavies. Sorry for the confusion, I didn’t even think to check this and just copied from the blog post as referenced above.

**Comment by maxtaco** [comment]
@jasondavies Are there valid sample sapling addresses published that I can test against?

**Comment by jasondavies** [comment]
I generated a few for you:

```
zs165czn4y5jfa552kux7yl3y5l8ge4cl6af45y9dh3yzfnkgd68vajyjdlkht54ve958qx693jjak
zs1x2q4pej08shm9pd5fx8jvl97f8f7t8sej8lsgp08jsczxsucr5gkff0yasc0gc43dtv3wczerv5
zs1fw4tgx9gccv2f8af6ugu727slx7pq0nc46yflcuqyluruxtcmg20hxh3r4d9ec9yejj6gfrf2hc
```

**Comment by maxtaco** [comment]
cheers

**Comment by maxtaco** [comment]
Thanks @jasondavies, those all worked.

**Comment by maxtaco** [comment]
https://github.com/keybase/client/pull/14472

**Comment by maxtaco** [comment]
Reader support is in master now. We're going to wait a release cycle before we enable posting of Sapling addresses.  Thank you.

**Comment by jbash** [comment]
What counts as a "release cycle"? I just installed the 3.0.0 RPM and I still can't add an address.

**Comment by maxtaco** [comment]
Forgot to enable it serverside. Try it now?

**Comment by rex4539** [comment]
Still the "waiting one release cycle message" message.

**Comment by maxtaco** [comment]
Sorry about that, we forgot to enable on the client side: https://github.com/keybase/client/pull/15912

Next release cycle, I apologize.
