### ISSUE TITLE
keybase files need to be rekeyed

### ISSUE THREAD

**Issue by tobyjaguar** [keybase/client#14567]
I'm on OSX 10.14.1 and I keep getting a popup that keybase files need to be rekeyed. why/what is happening??

my log id: ed5bc8e05dc8cfe383d91c1c

**Comment by strib** [comment]
It looks like you're trying to access a shared folder that has been reset because the other user reset their account.  Folders like that can't be rekeyed; they're considered "finalized", so when you add new devices to your account, those new devices can't access the old data.

You shouldn't get the warning if you, or your OS/apps, don't try to go into that folder.  You can also ignore it in the keybase app, or run `rmdir "/keybase/private/talgya,otheruser (files before otheruser account reset..."` (substituting the right folder name); then it won't show up in your list of folders anymore.

**Comment by tobyjaguar** [comment]
hmm, okay. So this doesn't have to do with my private folder, but a shared. Anyway of determining which folder to delete? I was just concerned that it might have been a key issue with my folder.

**Comment by strib** [comment]
I don't see any issues with your private folder.  If you can read it fine on that device, there are no issues.

I'll message you on Keybase with the exact folder name, I didn't want to expose it here.

**Comment by tobyjaguar** [comment]
thank you
