### ISSUE TITLE
Daily Crashes on Windows Server 2016

### ISSUE THREAD

**Issue by bradmurray** [keybase/client#14572]
Multiple times per day the client and KBFS mount just disappear. It worked fine for a good year before that.

my log id: 4506511613bf8eaff524991c

**Comment by zanderz** [comment]
@bradmurray The installation that happens behind the scenes on upgrade is failing with error 1625, which means "Installation forbidden by system policy." This could be because of a change in recent months to run all Keybase processes with normal user permissions, even if the installer was run elevated. If this is the case, uninstalling Keybase and installing again from https://keybase.io/docs/the_app/install_windows (unelevated) would be best. Your settings and device provisioning will remain.

If your administrator changed policies so that you are no longer allowed to update Keybase, it is not recommended to keep it on that computer, as it is important to always run the latest version.

**Comment by bradmurray** [comment]
Fixed this by manually reinstalling the app whenever it happens. It happens on every few releases.
