### ISSUE TITLE
RPM package signature check failure

### ISSUE THREAD

**Issue by pulmark** [keybase/client#14893]
I got email from Keybase to update keybase client. Downloaded the rpm package from their web site and run signature check that failed, error: digests SIGNATURES NOT OK.

Command sequence & output:
> sudo curl -O https://prerelease.keybase.io/keybase_amd64.rpm
> sudo rpm --checksig keybase_amd64.rpm
keybase_amd64.rpm: digests SIGNATURES NOT OK

**Comment by zapu** [comment]
`--checksig` works for me if I import Keybase code signing key using `rpm --import` first.
The key is here: https://keybase.io/docs/server_security/our_code_signing_key

```
» curl -O https://prerelease.keybase.io/keybase_amd64.rpm
» rpm -v --checksig keybase_amd64.rpm
keybase_amd64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 656d16c7: OK
    Header SHA1 digest: OK
    V4 RSA/SHA256 Signature, key ID 656d16c7: OK
    MD5 digest: OK
```

Your mileage may vary, because I'm on Ubuntu here and I don't even use RPM. So maybe the key management is different on rpm-based distributions.

**Comment by pulmark** [comment]
I also downloaded and then imported the Keybase code signing key into my key ring and the check signature works now. Problem solved.

>> gpg --import code_signing_key.asc
>> rpm --import code_signing_key.asc
>> rpm --checksig keybase_amd64.rpm
keybase_amd64.rpm: digests signatures OK
