### ISSUE TITLE
Cannot access private folder on one iOS device

### ISSUE THREAD

**Issue by maeveynot** [keybase/client#15157]
Hi,

I have three devices on my account - this computer (Linux), and two iOS devices (iPhone 8, iPhone 8 Plus), which I'll call the "old" one and the "new" one.

I am able to access my private folder on the Linux computer and the old iPhone, create files and see them show up on the other device, etc. Everything seems okay. However, on the new iPhone, I cannot open the private folder at all. A red bar pops up at the bottom of the content area which reads `Failed to list folder: maeve`.

I set up the new iPhone using the old iPhone, and it shows that when you click on it in the Devices listing. All my old devices are revoked. One revoked device was actually the old iPhone before I wiped and reinstalled it.

I have no idea how to fix this, and I am happy to have you delete the contents of the directory if that is necessary, as I've already moved the sensitive files to locally encrypted storage, so I'm copying the instructions found in https://github.com/keybase/client/issues/12285 and other issues:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkJcLRMo qLUoZVIoJJt1u7K 1iEtmLe4k5RRKDh 1VyvhCCD9Np7gNR 4IHaEDzUNfOu4v8 Snpn5vP6WIoz7An rCbKDO1FFeJWGyx 1UssyxCvD5dQx9c pSZzxOZSdQa4Hpb DktkeQMv8cPB28e C80KaeA6FymDmfQ aj6wWDtqDzZci5S gZQBq4RTteZz8OP eaPdVDnUMroughU m6WLVr23zTcpW3y 8asPlNIOLAodlq0 1YJNzdWa7Uy5bfj K1c3gDRAR4OBTtl oT0cGa70LKK1dkp sNo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrF9 t1GFjoZG7lhFRm. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
@maeveynot can you please send feedback with logs from your new iphone that's having the problem?  It's available from the in-app menu.  Mention me or this github issue in the feedback and I'll take a look.

On our side of things, everything seems fine -- all your current devices should have access to the folder.  It could be that the phone is still using an old version of the folder due to a caching bug, which will be fixed in the release that's coming out soon (today or tomorrow).

**Comment by maeveynot** [comment]
Sent!

**Comment by maeveynot** [comment]
Working now! Thank you.
