### ISSUE TITLE
KBFS: Download fails midway often for large files

### ISSUE THREAD

**Issue by arunsathiya** [keybase/client#15262]
I am trying to copy a 10GB file from KBFS to my local folder, and it keeps failing midway. Sometimes it fails at the 1.5GB mark, and sometimes at the 2-3GB mark.

What might be causing this? 

I am fairly certain I have a high-speed network and other services work fine.

my log id: 1e3f80badbcfd369b562e61c

**Comment by arunsathiya** [comment]
On a related note, downloads of files that weigh 700MB or so (small files) work fine.

**Comment by strib** [comment]
Thanks for the report.  The download failed because on macOS we constain our file system operations to complete within 19 seconds (due to OS restrictions).  This applies to each individual OS read call (which are pretty small), and so it's usually not a problem.  In this case, it took more than 19s to download a small piece of data from our servers.

I looked at your logs and our logs, and as far as I can tell that request was serviced very quickly by our servers.  So it seems like for some reason the time it took the data to travel from our servers to your device, and then get processed by your device, took something like 22s.  It's hard for me to diagnose why.  It could be that the download link on your network was very slow in that instant, or that the CPU was pegged on your device, or some unknown bug in our code prevented the processing for that long.  It's very hard for me to debug the root cause from the logs.

If this happens again, please let me know and we can try some more debugging steps on the live system to narrow down the cause.  Thanks!

**Comment by arunsathiya** [comment]
Thanks for checking and the detail, @strib! I shall give these downloads one more shot and see how it goes.

**Comment by arunsathiya** [comment]
I wanted to try this again, but I am stuck at not being able to see my files which I have logged here - https://github.com/keybase/client/issues/16474

**Comment by arunsathiya** [comment]
This is not an issue anymore.
