### ISSUE TITLE
K drive won't even mount anymore

### ISSUE THREAD

**Issue by SCOTT0852** [keybase/client#15342]
Last time I had kbfs problems, uninstalling & reinstalling Dokan would fix it. However, after kbfs broke again and I uninstalled/reinstalled even `keybase kbfsmount install` does absolutely nothing, Explorer doesn't even display an inaccessible K: drive. `Enable Keybase in Explorer` is stuck on, so I can't try toggling the feature to see if that would make it work.

my log id: 51b2c5020a3ca7324160f81c

**Comment by maxtaco** [comment]
Sorry for the bug 

Cc @zanderz @taruti

**Comment by taruti** [comment]
Hello, this seems to have been caused by a keepalive bug in the Dokan device driver. Installing the latest Dokan version from https://github.com/dokan-dev/dokany/releases/tag/v1.2.2.1000 should fix this. 

Please feel free to reopen the issue if this persists after installing the driver and rebooting.
