### ISSUE TITLE
ERROR First live link has to be eldest (got sibkey) (code 1014)

### ISSUE THREAD

**Issue by systemfifteen** [keybase/client#15518]
after installation I tried to log in with keybase login and received - ERROR First live link has to be eldest (got sibkey) (code 1014)
this was received after I tried to name a new device (there are no devices on my account yet)

my log id: 56ca14854b13d811f991341c

**Comment by maxtaco** [comment]
Sorry about this issue, we'll look into it. It's because you have a very old account it seems. But should handle this situation.

**Comment by maxtaco** [comment]
It might be easiest just to reset your account by the way. You can do that on the Website.

**Comment by systemfifteen** [comment]
> 
> 
> It might be easiest just to reset your account by the way. You can do that on the Website.
I'll probably reset it, but found out that some files were waiting for me :-) so I would like to recover those if possible. If that's not the way I'll reset account

**Comment by maxtaco** [comment]
oh ok, well in that case i'll ask around.

**Comment by zapu** [comment]
@systemfifteen we are slowly getting to the bottom of this issue. It turns out to be a combination of how your account is set up - with a PGP key but without sigchain, and how our sigchain rules evolved over time.

Can you explain to us what kind of files do you want to recover? Maybe there is a way despite account reset in your state. Because while we can fix it on our side, the quickest way here is account reset. But let us know first, let's figure it out.

**Comment by systemfifteen** [comment]
> 
> Can you explain to us what kind of files do you want to recover? Maybe there is a way despite account reset in your state. Because while we can fix it on our side, the quickest way here is to reset. But let us know first, let's figure it out.

I just found out after login on Keybase website that some files are waiting (screen attached) so that is why I installed Windows app and then Linux version :-) and then that error occurred while logging in. I assume those files are not important, and I do not know what kind of content it is. is it possible in this state to recover those? app was never installed before, everything was setup via browser and I have my private key. maybe there is a way to recover account with upgrade of my private key to version with sigchain (I do not know if this is possible)

![keybase_action](https://user-images.githubusercontent.com/45658661/51230512-89257900-1960-11e9-88b4-9d54d543c1b9.jpg)

**Comment by zapu** [comment]
OK - thank you for your explanation, we are going to look into this further and see what's the best way to proceed here. Sorry for the troubles.

**Comment by zapu** [comment]
sorry for the delay, we are still on this - I'll let you know shortly

**Comment by systemfifteen** [comment]
> 
> 
> sorry for the delay, we are still on this - I'll let you know shortly

Thanks a lot :-) Do you need some other information from my side?

**Comment by zapu** [comment]
@systemfifteen hey, sorry for the delay.

We have determined that you've been trapped in a combination of legacy systems, and it should be fine (and easiest) to reset and start from scratch with a Keybase client rather than PGP key. It can be added later, once device-backed sigchain is established.

Another symptom of that legacy behavior is the text that "files are waiting from rdvn" on the website - this is a leftover code and it's not exactly correct. We are certain that no one is sharing files with you right now so no data will be lost.

Let me know if there are any further issues.

**Comment by systemfifteen** [comment]
Thanks a lot for help :-) I reset my key and now it seems to be working OK
