### ISSUE TITLE
kbfs doesn't work on chromeos under the linux vm

### ISSUE THREAD

**Issue by seansummers** [keybase/client#15547]
On a ChromeOS device running the linux vm, keybase appears to be almost fully functional (including the graphical ui), but /keybase is empty, and there are no obvious errors or failures (kbfsfuse is running).

my log id: f230f264a983588df2d1a51c

**Comment by heronhaye** [comment]
It looks like FUSE is not supported on Chromium OS. 

https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md#FUSE

However, the issue it links to seems to have been resolved 4 days ago. I'm not sure if or when you'll get that update on ChromeOS though. What happens if you run `modprobe fuse`?

You should still be able to use `keybase fs` and KBFS in the GUI without a FUSE mount.

**Comment by seansummers** [comment]
I'd love to use `keybase fs` but I can't for the life of me figure out wtf a `KBFS path arguments` is, as there is no documentation or help to speak of....

> ssummers@penguin:~$ keybase fs ls kbfs:/seansummers
> Error parsing command line arguments: ls requires KBFS path arguments

Here's the output of `modprobe fuse`:

> ssummers@penguin:~$ sudo modprobe fuse
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.14.74-07776-gac52e5f750c8/modules.dep.bin'
> modprobe: FATAL: Module fuse not found in directory /lib/modules/4.14.74-07776-gac52e5f750c8

**Comment by heronhaye** [comment]
There are some docs at https://keybase.io/docs/kbfs/understanding_kbfs, e.g., `keybase fs ls /keybase/private/`.

**Comment by seansummers** [comment]
Excellent, your advice has been great!

It appears that the cli `KBFS path` is synonymous with the documented `Keybase path`, with minimum valid prefixes of `/keybase` before any error other than:
> Error parsing command line arguments: ls requires KBFS path arguments

and minimum valid prefixes of `/keybase/public` and `/keybase/private` before  any message other than
> ▶ ERROR Invalid remote path

is possible.

Is there a place I can open an issue or commit a patch to make more informative error messages (or improve the documentation to point out this obvious but non-documented requirement?

**Comment by heronhaye** [comment]
Thanks for the offer! The help string for `keybase fs` is at https://github.com/keybase/client/blob/master/go/client/cmd_simplefs.go#L30. You can make a PR and tag me, maybe just add a link to the KBFS doc and give an example command.

**Comment by espoelstra** [comment]
You can use `run_keybase -h` to see the supported options. One of them allows disabling KBFS which should allow you to at least use Keybase Chat functionality. Adding fuse to the crosvm was actually done recently by the Google developer team, so you should be able to install and use Keybase without too much issue (the GUI can be launched via `/opt/keybase/Keybase &` from the Terminal since the desktop shortcut is currently a little buggy).
