### ISSUE TITLE
Sync never finishing, looks like it hangs or is in a loop?

### ISSUE THREAD

**Issue by foss-** [keybase/client#15699]
Keybase GUI Version: 2.13.2-20190123014357+6bb157b5d0
macOS 10.13.6

screencast of what's going on (30 days available):
https://upload.disroot.org/r/KuXwdczQ#+3qgV1fQeP51y5UnSQzZ95muScSjWhfwfaLW8Lbqv/U=

Keybase client says 12 files to sync, 9 seconds, goes down to 5 or 4, and back to 9. repeat. this goes on for several hours without ever finishing.

Unsure how to resolve this or what's going wrong in the first place.

**Comment by strib** [comment]
@foss-  Please run `keybase log send` from that device, report the resulting log ID here, and we'll take a look.

**Comment by foss-** [comment]
Log ID is d10ca5581a6c5a4c9593381c
Thanks for looking into this.

**Comment by strib** [comment]
@foss- your device is stuck on a bug in our code, after hitting a "conflict" with data wrote on this device, vs. other data written to the folder by another device.  Now it can't get out of that conflict state, so it's not able to sync the data you wrote.

We are actively working on a better way to present this situation to you, and of course I'll look at the bug you hit and fix it.  In the meantime, we can get you out of this situation like this:

1. Make sure you back up any files that haven't been synced from that device.  Read the magic `.kbfs_status` file in your private keybase folder to see what files those are.
2. Quit the Keybase app completely, so that the file system mount disappears.
3.
```
mv "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/0120b8fd00cabbad097fe835d717ae3f3962-6559620317b3709f" "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/6559620317b3709f.bkp"
```
4. Restart the Keybase app.

At this point your device should be in sync with the server's view of the folder again, and you can re-add the files that haven't been synced.

Let me know how it goes, or if you have any other questions/concerns.  Sorry for the bad experience!

**Comment by foss-** [comment]
That did it. Thanks for bringing me back to working state. Good luck with the fix for the bug.
