### ISSUE TITLE
kbfsdokan.exe using 100% CPU and RAM usage

### ISSUE THREAD

**Issue by HyphenSam** [keybase/client#15723]
Was using the computer normally when this issue suddenly appeared. Last thing I remember doing was uploading a 3.5 GB file to my private folder, which was yesterday. I didn't have any performance problems back then.
It's still uploading because my Internet is slow, but that doesn't explain the sudden resource usage spike.

My log ID: 01085b7ba96116c9acab5a1c

**Comment by strib** [comment]
@HyphenSam your device is in a "conflict" state, which means you wrote data to your folder and when it tried to sync it with our servers, another device had written something to the same folder and beat it to the server.  In that case, your device tries to "resolve" the conflict automatically.  But here, there was so much data (I guess that 3.5 GB file) that it's having trouble and crashing due to running out of memory.

We are actively working on fixing this situation so it's not memory dependent.  In the meantime, you can fix this for yourself with the following steps:

1. Make sure you have a backed-up local copy of anything in your private folder (like that 3.5 GB file) that hasn't yet synced to our servers.
2. Completely quit the Keybase app, so the K: drive disappears.
3. Navigate to the local folder `%APPDATA%\Local\Keybase\kbfs_journal\v1\`, and rename the subdirectory `0120285832a31dc5f6671ddda247c7eaa3dd-bba6eaa30783f058` to something else, like `bba6eaa30783f058.bkp`.
4. Restart Keybase.

Now you should be synced with the main server again, and you can retry your 3.5 GB upload.  Sorry for the bad experience, hopefully we'll have this fixed soon.

**Comment by HyphenSam** [comment]
@strib Thank you, now I can use Keybase without my computer freaking out.
