### ISSUE TITLE
unable to load files in client

### ISSUE THREAD

**Issue by nfbarrett** [keybase/client#16055]
[write something useful and descriptive here]

my log id: 742d09038c3f3d4886f9f91c

![image](https://user-images.githubusercontent.com/286987/52810258-c52f2500-3057-11e9-893d-3bf0a1f8aa98.png)

**Comment by strib** [comment]
@nfbarrett hmm your KBFS process isn't running -- it seems like the dokan drivers went missing:

```
2019-02-06T09:53:52.558828-06:00 - [ERRO kbfs start.go:143] 0d1 Running KBFS without a filesystem mount due to: loadDokanDLL: cannot load Dokan DLL: The specified module could not be found.
```

Did you try to enable explorer integration and it failed?  Maybe you could uncheck that box in the settings and restart, since it should be able to run without dokan as long as explorer integration is turned off.

**Comment by nfbarrett** [comment]
> Did you try to enable explorer integration and it failed? Maybe you could uncheck that box in the settings and restart, since it should be able to run without dokan as long as explorer integration is turned off.

Yep looks like that did it!
