### ISSUE TITLE
Keybase gui no longer working in debian stretch -- missing GLIBC_2.27

### ISSUE THREAD

**Issue by sgrayban** [keybase/client#16163]
I updated from Jessie to Stretch this week and noticed that I can't get Keybase to open. It does run but nothing else. No icon in the systray and running keybase from the cli gives this....

$ run_keybase
Unmounting /run/user/1000/keybase/kbfs...
Unmounting and shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd...
Job for keybase.gui.service failed because the control process exited with error code.
See "systemctl status keybase.gui.service" and "journalctl -xe" for details.
Failed to launch GUI. Pass -g to prevent startup if on a machine without a graphical display.

**Comment by sgrayban** [comment]
Also this error....

$ systemctl status keybase.gui.service
Unit keybase.gui.service could not be found.

**Comment by sgrayban** [comment]
hmm just saw this error also

/opt/keybase/Keybase: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.27' not found

**Comment by heronhaye** [comment]
sorry, missed this.

are you perhaps on a 32bit system?

**Comment by sgrayban** [comment]
Yes

**Comment by heronhaye** [comment]
Sorry, Electron (which powers the GUI) does not seem to support 32 bit Linux anymore. See https://github.com/electron/electron/issues/16407.

You should be able to continue to use Keybase from the CLI as described in https://keybase.io/docs/linux-user-guide#example-commands. 

By the way, since keybase.gui is a user service, you need to do `systemctl --user status keybase.gui` (that suggestion without `--user` in the `run_keybase` output comes from systemd and appears to be just wrong in debian's systemd version).

**Comment by sgrayban** [comment]
Well crap... the same version ran in jessie just fine. So what changed ?

**Comment by heronhaye** [comment]
Sorry, I don't know the details. But you can ask on that issue or make a new issue in github.com/electron/electron.

**Comment by sgrayban** [comment]
Just out of curiosity will a older version of keybase work ?

**Comment by heronhaye** [comment]
Yes, but it is not recommended, because you won't have the latest security updates, bugfixes, and features.
