### ISSUE TITLE
Files do not load on the Mac app or on Finder

### ISSUE THREAD

**Issue by arunsathiya** [keybase/client#16474]
[write something useful and descriptive here]

my log id: e78f33484cba7c7b75b4831c

When I try to load my files on the Mac app, I see an error that reads `Failed to load TLF lists`. What might be wrong here?

<img width="800" alt="screenshot 2019-03-07 at 20 42 43" src="https://user-images.githubusercontent.com/18581859/53966698-a9c8ae80-4119-11e9-8dca-6a67639d6062.png">

Thanks for taking a look!

**Comment by arunsathiya** [comment]
If it helps analyse the situation better, I have Keybase app on another Mac computer as well and it loads fine on that computer.

**Comment by strib** [comment]
Hi @arunsathiya.  The mac you sent the logs from was stuck trying to connect to our servers due to some network connectivity issue between your client and our servers.  The error you're getting there is a timeout.

If the network otherwise seemed to be working at the time, perhaps you are behind some kind of firewall of VPN that restricts traffic to our servers?  I don't know of any downtime on our end.

**Comment by arunsathiya** [comment]
I am indeed using a VPN, but I am not sure of this blocking traffic to Keybase servers. It's good to know that nothing is off at your end though. I shall close this report for now, test and reopen as required. Thanks for taking a look!
