### ISSUE TITLE
Security: Flip should use modular addition instead of XOR

### ISSUE THREAD

**Issue by jwietelmann** [keybase/client#16529]
I wrote a little thing here: https://medium.com/revelry-labs/fair-random-numbers-on-the-blockchain-are-absolutely-possible-a70d8a3ea341

This is the relevant bit:

<img width="724" alt="Screen Shot 2019-03-11 at 2 41 37 PM" src="https://user-images.githubusercontent.com/550889/54149106-de838100-440b-11e9-962d-f48eb47732c3.png">

**Comment by maxtaco** [comment]
Bob and Charlie have to commit to a value before they see Alice's reveal, and therefore cannot base their reveal on hers unless they have broken the collision-resistant hash function.

**Comment by jwietelmann** [comment]
@maxtaco Please clarify: The reveal of what? I only have to see your hash in order to be able to commit to the same exact hash.

**Comment by jwietelmann** [comment]
* `X xor X` is always 0.
* `0 xor Y` is always Y.
* Alice submits `hash(X)`.
* Bob doesn't have to know Alice's `X`. He knows her `hash(X)`, and he can commit to it.
* This sets the flip to 0.
* Charlie's `hash(Y)` sets it to `Y`.
* This is all before the reveal step.

**Comment by maxtaco** [comment]
Can you send me an email at max@keyba.se?

**Comment by jwietelmann** [comment]
👍

**Comment by kirelagin** [comment]
Well, yes, it’s true that in current scheme a failed process can mirror the commitment of another process by being the last one to commit/reveal. This way one failed process can cancel out the input of any one other process, a coalition of `n/2` failed processes can force the seed to be zero, and a coalition of `n/2 + 1` failed processes can force any seed they like.

Two obvious ways to fix this are:

1. Include the identity of the process in the message it commits to; or
2. Make sure the commitments are revealed in reverse order, so that bad actors won’t be able to reveal the values they have not learned yet.

**Comment by maxtaco** [comment]
Hotfixes went out yesterday. Agreed on option (1), but it's not backwards-compatible with the current protocol, so we'd need a length migration period to roll out reader support, then deprecate the current version and launch the new version. Option (2) isn't great because we tried not to rely on ordering guarantees, aside from reveals only happen after all commitments are collected.  We put up a simple patch, which is to fail a flip if any commitment is duplicated: https://github.com/keybase/client/pull/16530
