### ISSUE TITLE
Packaging question: Keybase installed in /opt

### ISSUE THREAD

**Issue by LaurentTreguier** [keybase/client#16569]
On Linux systems, Keybase is installed in `/opt/keybase`.
Because of https://github.com/projectatomic/rpm-ostree/issues/233, this makes Keybase currently not installable via the Keybase RPMs on an OS making use of [rpm-ostree](https://github.com/projectatomic/rpm-ostree).

Although this is an issue with rpm-ostree and not Keybase itself, this led me to ask: why is Keybase installed in `/opt/keybase` rather than `/usr/share/keybase` ? `/usr/share` is where [Atom](https://github.com/atom/atom) and [Visual Studio Code](https://github.com/Microsoft/vscode) put most of their files. Both of them are based on Electron, like keybase; so this would seem like a natural place for Keybase to put its files as well.

Is there a specific reason to put files in `/opt` ? And if not, would it pose too many problems to move them to `/usr/share`, because of other things to consider regarding packaging ?

**Comment by heronhaye** [comment]
We install the Go binaries (service, CLI, KBFS) in `/usr/bin/` but put the Electron/GUI binary in `/opt/` because we do not integrate with system electron, if installed, but provide our own electron binary.

For example, in the Arch VSCode package https://aur.archlinux.org/packages/visual-studio-code-bin/?O=10&PP=10, which doesn't depend on the Arch electron package, the vscode binary is installed into `/opt/`.

**Comment by LaurentTreguier** [comment]
I see. The AUR package is unofficial though; the official VSCode deb and rpm packages on the other hand use `/usr/share/code`, this is where they put their own electron

**Comment by eli-schwartz** [comment]
The version of keybase-gui which is available in the Arch Linux community repository, uploaded by me, does in fact use `/usr/share`. But I am also taking advantage of the system electron package.

It is pretty common on Linux for applications that install fully relocatable prebuilt binaries in a totally standalone manner, to do so in `/opt`. Keybase is not unusual in this respect. This seems like a generally broad category of issue which rpm-ostree needs to handle.

Note: There appears to be an existing issue for this at https://github.com/keybase/keybase-issues/issues/3211

**Comment by eli-schwartz** [comment]
> I see. The AUR package is unofficial though; the official VSCode deb and rpm packages on the other hand use `/usr/share/code`, this is where they put their own electron

This is completely and utterly wrong, as /usr/share is arch-independent data and Debian at least has extremely strict rules against this -- it is explicitly incompatible with the entire concept of multi-arch.

**Comment by LaurentTreguier** [comment]
How is this utterly wrong ? I can `rpm -ql code` on my system and I do see it installed in `/usr/share/code`.
What I mean by "official" is officially released by Microsoft, not officially packaged by distro package maintainers.

**Comment by LaurentTreguier** [comment]
Anyway, I'm closing this as it's a duplicate of the issue you mentioned.

**Comment by eli-schwartz** [comment]
Because Debian officially supports multi-arch, which means it is *valid* to install both the i386 and amd64 packages simultaneously on one root filesystem, and therefore per policy they cannot install conflicting paths on a Debian system.

Arguably this means /opt is just as problematic, but in that case the use of /opt makes it quite plain that the software is not intended to conform to system-integrated packaging guidelines and certainly isn't multi-arch compliant.

It also violates the FHS even if Debian did not have policies about it, which is really a more pertinent point. You're supposed to use `/usr/share/${PACKAGE}` for arch-independent data files, and `/usr/lib/${PACKAGE}` for arch-dependent data like binaries.

**Comment by LaurentTreguier** [comment]
This was fixed with https://github.com/projectatomic/rpm-ostree/commit/a4c2df0bdfdc554f16ce19b446ae00cd2a60cdbc. On systems using rpm-ostree v2019.3 and onward, `/opt` will be redirected to `/usr/lib/opt` during installation; it's been tested with Google Chrome, but it should probably work with anything that's installed in `/opt`. The only caveat is that packages can't write to `/opt` at runtime, but Keybase doesn't do any such thing as far as I know.
