### ISSUE TITLE
`cd /keybase` Permission Denied on Mac after recent update (with files enabled in finder)

### ISSUE THREAD

**Issue by andrewhartwig** [keybase/client#16863]
Hey there, I recently updated my mac (Presently on 10.14.3) and since have not been able to use terminal to enter my keybase folders. I can access them from finder, I've ensured security settings are allowing it. This was working up until today with no hassle.

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by andrewhartwig** [comment]
e2edd5c637f5f317f7d5c71c 

There ya go!

**Comment by strib** [comment]
You're getting the same error code as in #11763 and #13352.  It indicates that macOS is blocking the loading of our kernel extension because it doesn't think you've authorized it.  Something about the upgrade must have reversed your earlier authorization silently, while still showing you that it's authorized.

Maybe try undoing the authorization and trying it again?  Or you can try some of the workarounds in those issues, specifically https://github.com/keybase/client/issues/11763#issuecomment-410790612 or https://github.com/keybase/client/issues/13352#issuecomment-414410866.

**Comment by andrewhartwig** [comment]
Well I'll be darned, those solutions fixed it (specifically using the keyboard nav to select the "Allow" button.).

How do people find that shit out!

Thanks mate :)
