### ISSUE TITLE
`/keybase` folder on Finder has disappeared

### ISSUE THREAD

**Issue by MyC-Greg** [keybase/client#16948]
Hi I have the same problem as @choiway but on my mac.
Keybase GUI Version: 3.2.1-20190410040938+61d9000f85
It started with a word document that could not be saved anymore, then an alert from keybase and then `/keybase` not being accessible.

_Originally posted by @MyC-Greg in https://github.com/keybase/client/issues/10873#issuecomment-481852458_

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, we can take a look.

**Comment by MyC-Greg** [comment]
Hi @strib, here is the ID: 
ef6386948866fc8ea4468a1c

**Comment by strib** [comment]
Strange.  The issue was that your directory intended to be your mountpoint (`/Volumes/Keybase ($USER)`) was missing when we tried to mount to it.  That's supposed to get created by our privileged helper process, and I don't see any errors in the logs around it, so I wonder if something on your system cleared out the `Volumes` directory after we created it?

In any case, I'm glad you got it working now by disabling and re-enabling finder integration.  Let us know if you have more issues.
