### ISSUE TITLE
ERROR Getting object {sha} failed: object not found

### ISSUE THREAD

**Issue by qrkourier** [keybase/client#17804]
```
❯ git push --quiet keybase master
Initializing Keybase... done.
Tip: this repo could be sped up with some garbage collection. Run this command:
        keybase git gc idrepo

❯ keybase git gc idrepo
This may take several minutes...
▶ ERROR Getting object 9ec64d62e728245a80d3c060d883442085cb40ad failed: object not found
```

my log id: 96633ee53e70e6f905b95d1c

**Comment by strib** [comment]
Thanks for the report.  Hmm that's strange.  I assume repeated attempts give the same error?  Does a fresh clone/checkout of the repo seem to work ok still?  And when you use the repo, does it still recommend a `gc`?

**Comment by qrkourier** [comment]
```❯ git clone -q keybase://private/kourier/idrepo /tmp/idrepo
Initializing Keybase... done.
Tip: this repo could be sped up with some garbage collection. Run this command:
        keybase git gc idrepo

❯ keybase git gc idrepo
This may take several minutes...
▶ ERROR Getting object 9ec64d62e728245a80d3c060d883442085cb40ad failed: object not found

```

**Comment by qrkourier** [comment]
```
❯ git ls-remote keybase://private/kourier/idrepo
Initializing Keybase... done.
Syncing with Keybase... done.
70f40a429026c087e3844c6be028a0bad91b5638        refs/heads/master
70f40a429026c087e3844c6be028a0bad91b5638        HEAD

```

**Comment by qrkourier** [comment]
```
❯ git ls-remote file:///tmp/idrepo
70f40a429026c087e3844c6be028a0bad91b5638        HEAD
70f40a429026c087e3844c6be028a0bad91b5638        refs/heads/master
70f40a429026c087e3844c6be028a0bad91b5638        refs/remotes/origin/HEAD
70f40a429026c087e3844c6be028a0bad91b5638        refs/remotes/origin/master
```

**Comment by strib** [comment]
@qrkourier does the repo include git submodules by any chance?

Also, what does this show within the repo?  Anything?
```sh
git ls-tree 70f40a429026c087e3844c6be028a0bad91b5638 | grep 9ec64d62e728245a80d3c060d883442085cb40ad
```
Anything?

**Comment by qrkourier** [comment]
```
❯ git remote -v show keybase
Initializing Keybase... done.
Syncing with Keybase... done.
* remote keybase
  Fetch URL: keybase://private/kourier/idrepo
  Push  URL: keybase://private/kourier/idrepo
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (up to date)

❯ git pull keybase master
Initializing Keybase... done.
Syncing with Keybase... done.
From keybase://private/kourier/idrepo
 * branch            master     -> FETCH_HEAD
Already up to date.

❯ git ls-tree 70f40a429026c087e3844c6be028a0bad91b5638 | grep 9ec64d62e728245a80d3c060d883442085cb40ad

❯ git submodule status --recursive
```

**Comment by subsetpark** [comment]
Hi @strib - just writing to add that I have the exact same issue described here. Happy to run any diagnostic commands if you like; it's been happening for me for many months, though usage of the repo on several machines is totally normal.

**Comment by taw00** [comment]
I got the same thing. Then ... it magically disappeared upon subsequent runs.
Note, I am usually on a very high latency network (Satellite, though the fastest money can buy for a civilian) and sometimes kbfs will do odd things and I have had git get hung at times.

Anyway. I hope those anecdotal datapoints add something.

**Comment by nstgc** [comment]
I've been having this issue for a couple of years. I'm just not getting around to looking into it because so far it's shown itself to be completely harmless. I just have to run `keybase git gc $repo` an extra time (even that probably isn't needed).

For what it's worth, I make heavy use of submodules.

Also, like taw00, sometimes I have issues and pushes and pulls get interrupted. Sometimes it was due to visiting my father who had satellite internet, and sometimes it's just my android tablet (I use Termux) acting up.

I am the sole committer to these repos.

The repos don't start off acting this way, but at some point, something causes this to happen. Once it starts, the only way to fix it is recreate the repo. So far, I haven't attempted to recreate a repo's full history, I merely make copy the heads of branches into branches in the new repo along with the branching and merge points.

This effects multiple repos of mine and in each, as has been mentioned, the object doesn't exist anywhere.
