### ISSUE TITLE
Can Not Search in Finder on OSX

### ISSUE THREAD

**Issue by dlumma** [keybase/client#18417]
Using the search bar in Finder on OSX for any file under the Keybase mounted drive returns no results. 

Please help.

**Comment by dlumma** [comment]
One piece of good news: from the Keybase native app, navigate to Files, search does seem to work correctly.

**Comment by dlumma** [comment]
Scratch that: Filter for a substring in the name of the file works, however, searching for a substring within the file does not.

**Comment by strib** [comment]
This is intentional.  If it was indexed by Finder, it would end up iterating over all the private, public and team folders you've ever visited, downloading every single file in all those directories, which would be very expensive.  We will eventually have our own solution for file search, but we don't have it yet.
