### ISSUE TITLE
Mac OSX Catalina KBFS issues

### ISSUE THREAD

**Issue by simpleauthority** [keybase/client#18528]
KBFS fails to load on boot, probably just due to Catalina being beta and their new perms changes but not sure. Take a look if you want to.

my log id: 04bbc783868519e4f944a01c

**Comment by luzmcosta** [comment]
Same here. Log ID 734cfe85534d2cfcb375af1c

**Comment by docdyhr** [comment]
Same here. my log id: 26db0aee55bee0925771231c

**Comment by strib** [comment]
Catalina support will be arriving in the next release, hopefully out next week sometime.

**Comment by strib** [comment]
Keybase 4.4.0 (out today) has better file system support for Catalina now.  Please let us know if you have more problems with it.  Note that the `/keybase` mount point is no longer viable on fresh installs of Catalina due to macOS namespace restrictions, so now we mount at `/Volumes/Keybase` if `/keybase` does not already exist.

**Comment by simpleauthority** [comment]
Fantastic. This has resolved my issue.
