### ISSUE TITLE
OSX: GPG error: exit status 2 Error code 218: GENERIC in method keybase.1.login.login`

### ISSUE THREAD

**Issue by glenjarvis** [keybase/client#18569]
I chose options: Login -> Password -> One time shell to GPG

And, then I received this error:

`GPG error: exit status 2 Error code 218: GENERIC in method keybase.1.login.login`

My PGP keys are encrypted and I was not prompted for a passphrase. Any terminal did not start.

I typically don't allow access to my GPG keys until I know what the client is doing. Please help me understand from this log data what is being attempted.

I would prefer to do these steps to validate my login from a command console and then take any artifact (e.g., something signed) and then importing into the client.

my log id: 18c868927a98fe475cf6f01c

**Comment by maxtaco** [comment]
Run `keybase status` to see where you log is, and then you can examine that.

It looks like GPG errored out `/usr/local/bin/gpg --no-tty --with-colons --fingerprint -K`, which is just printing the fingerprint of the secret keys that you have locally.  Your desktop client needs to sign a statement with your PGP key to transition from a Web-based account to one with device keys.  This is the first step in that process, since we are checking to see if the signing keys even exist on this computer.

**Comment by glenjarvis** [comment]
It could be that I keep a tighter security on my GPG than the GUI can "handle." I've decided not to use the keybase tool. You can close this issue.
