### ISSUE TITLE
Keybase Install Error

### ISSUE THREAD

**Issue by burakince** [keybase/client#19012]
**OS**:
macOS Mojave: `10.14.6`

**Error**:
```
Keybase Install Error

We were unable to load KBFS (Fuse kext). This may be due to a limitation in MacOS where there aren't any device slots available. Device slots can be taken up by apps such as VMWare, VirtualBox, anti-virus programs, VPN programs and Intel HAXM.

Please run `keybase log send` to report the error.
```

**Description**:
I have VirtualBox, but the Keybase worked without problem with VirtualBox for a long time.
This started to happen after macOS 10.14.x upgrade.

my log id: `371139c2ebb67e742f55261c`

**Comment by wieczorek1990** [comment]
I have the same problem after upgrading to macOS Catalina (10.15 Beta (19A536g)).
Finder integration does not want to be turned on.

**Comment by PReimers** [comment]
Same problem here, using `10.15 Beta (19A536g)`

My log id is: `0c49b4db6402b3b425dde41c`

I manually added full Harddisk permission but the error is still the same 😟

**Comment by strib** [comment]
Keybase 4.4.0 (out today) has better file system support for Catalina now.  Please let us know if you have more problems with it.  Note that the `/keybase` mount point is no longer viable on fresh installs of Catalina due to macOS namespace restrictions, so now we mount at `/Volumes/Keybase` if `/keybase` does not already exist.

(This doesn't address the original issue, which was about VirtualBox conflicts with osxfuse, which we can't really do anything about, sorry!)

**Comment by wieczorek1990** [comment]
Works for me.

**Comment by burakince** [comment]
I removed Intel HAXM from my system with this command;

```
sudo /Library/Extensions/intelhaxm.kext/Contents/Resources/uninstall.s
```

[Source of command](https://github.com/intel/haxm/wiki/Installation-Instructions-on-macOS#Removing_Intel_HAXM)

Also, I upgraded to the latest version of Keybase. It's better for now. Thanks for your support. 👍

**Comment by PReimers** [comment]
Worked for me after upgrading to the latest version of Keybase 👍
