### ISSUE TITLE
User folders not auto generated on initial install

### ISSUE THREAD

**Issue by quaz3l** [keybase/client#1940]
When I installed the app, it took me a few minutes to figure out that I needed to create a folder inside /public and /private named "samschooler". These folders were not create on install.

Keybase GUI Version: 1.0.9-20160205170011+ce05b7a

**Comment by simonjgreen** [comment]
Still present in new version. If you use the tray icon and click the folder name it creates the missing folders.

Keybase GUI Version: 1.0.10-20160208170011+01e1c79

**Comment by strib** [comment]
This is by design.  The GUI will show the folders for you, but KBFS does not automatically show these folders for you, it is up to you to navigate into them, which "favorites" them and then you'll see them from your account on all your devices.  It's currently our policy not to favorite anything for you automatically.
