### ISSUE TITLE
Copying to kbfs intermittently fails because some data can't be read/written

### ISSUE THREAD

**Issue by scotthammack** [keybase/client#1961]
When copying files into /keybase/public/shammack on OS X, the operation sometimes fails and pops up the Finder error:

> The Finder can’t complete the operation because some data in “x” can’t be read or written.
> (Error code -36)

This is intermittent, and I have eventually been able to successfully copy the same file after multiple attempts.

All the times I've seen this issue so far have been while copying video files (mp4 or mov) in the 10-20MB range.

my log id: 8bd20113faf81842a328da1c

**Comment by strib** [comment]
Thanks for the report.  "Error code -36" represents an "Input/output error", which is the generic catch-all error we use whenever something goes wrong.  (Future versions of KBFS will report better errors via our own GUI, rather than being stuck with file system error codes.)

In this case, it seems like your client had trouble sending data to our servers in a timely manner.  Due to limitations in the OSX file system interface we use, we time out operations after 19 seconds.  Here we buffered about 8 MB of write data, and then tried to write it all to the server.  However, that took about ~40 seconds.  In the meantime, your application was still trying to write, and that write timed out (resulting in an IO error) after 19 seconds.

We basically need better buffer control in KBFS to smooth out the writing experience a bit.  We have ideas on how to do this, but don't yet have a schedule for implementing them.  Hopefully soon!  I'll keep this open until it's done.  Thanks.

**Comment by bobinson** [comment]
similar issue & the error report:

```
cp: /keybase/public/bobinson/indieauth.txt: fchmod failed: Input/output error
cp: Documents/personal/freebird.in/indieauth.txt: could not copy extended attributes to /keybase/public/bobinson/indieauth.txt: Operation not permitted
cp: /keybase/public/bobinson/indieauth.txt: Input/output error
```

**Comment by strib** [comment]
Thanks @bobinson.  I can take a look if you do a `keybase log send` and report the log ID here.

**Comment by bobinson** [comment]
@strib  - there you go:

my log id: 55e76c2f2ca10946fb0b8f1c

**Comment by strib** [comment]
@bobinson: yeah it looks like this is the same issue.  You wrote a ~3MB image file that we weren't able to sync to our servers within your operating system's FS timeout, and other operations are erroring because of that.  For now, you can restart KBFS and try again on a better connection.  We'l have a fix out in the next few weeks I hope.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.

**Comment by bobinson** [comment]
ok  - will test when I install keybase again.
