### ISSUE TITLE
deleted issue

### ISSUE THREAD

**Issue by jull27** [keybase/client#19718]
nothing

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop

**Comment by qrlk** [comment]
I found out about this drop on 10th and asked 2 my friends to join too.  
As a result, both of them are still in but I got kicked out of the airdrop xD
It's clear for me that I should not "get mad at us if something goes wrong here", but just imagine how many people were not trying to cheat and still are now kicked out. Not fair. :-1:

**Comment by jull27** [comment]
> Some people try to creating a lot account to keybase and try to take down all keybase xlm air drop ... The people who register more than day 9 September will be automatically can't join this airdrop ... To same for real people who have registered at day 10 and they real person too and not a bot and they cry now 
> Very fair do from keybase from doing that



> See: https://twitter.com/malgorithms/status/1173785764544569345
> 
> > And just **had to turn off new GitHub Space Drop registrations also, due to bad actors**. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop
> 
> And public announcement at https://keybase.io/airdrop:
> 
> > UPDATE #2 September 16: HackerNews and GitHub were both under attack by bad actors who hoped to game this by stealing other users' accounts. In cooperation with both of those sites, **we've halted Space Drop registration for anyone who wasn't a Keybase user before Sept. 9**. SDF and Keybase will discuss, while whining and moaning, how this giveaway can continue. (COME ON PEOPLE OF THE INTERNET, STOP SUCKING SO MUCH!)

![Screenshot_2019-09-10-19-31-47-543_com android chrome](https://user-images.githubusercontent.com/47663663/65040371-6bd8fc80-d97e-11e9-8221-101d2ad5bac2.png)
![Screenshot_2019-09-17-18-52-35-603_com android chrome](https://user-images.githubusercontent.com/47663663/65040387-7bf0dc00-d97e-11e9-98ad-2399e7843990.png)



So sad that i was eleminated from the airdrop ... Thats the proof thats me was deleted from air drop

**Comment by jull27** [comment]
And need you know i was open keybase adn web everyday for see whats happen at it .... But if you kick me out its okay just i feel this only not fair and i disappointed with keybase 
Thank you sir 🙏

**Comment by bitcoinoplomo** [comment]
https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

> We reserve the right to blacklist users, even after registering. If you appear to use a bot or multiple accounts to sign up for Keybase, we'll blacklist you. Similarly, if you appear to use bot accounts on HN or Github, we'll blacklist you.

This not very clear!
I also recommend a few friends to join in if they had a github account registered before 9 September.
I think all of them are still in. 
But I got kicked out. 
I sent a email to keybase and I got this reply

> Solved: keybase/client/issues/19718

This is not a solution! 
Looks like keybase can blacklist who they want without any criteria.

![2019-09-17-133305_3840x1080_scrot](https://user-images.githubusercontent.com/35741715/65042995-f9eabe00-d951-11e9-8dfb-d15244761651.png)

And now this! 
So this kick out almost any new user.
The airdrop is not supposed to bring people to keybase? 

You guys need a better solution! 
And saying that because it's a gift anything goes is not fair.
The original terms should be thought better. 
If someone broke them and was kicked out at least has the right to complain.
I use keybase because is useful for find PGP keys and I have, PGP pub key, my twitter and github account on them. 
Keybase needs a better solution to find bad actors abusing the airdrop.

**Comment by sengmangan** [comment]
whats

**Comment by coofercat** [comment]
I've still got this problem (see #19818) - This issue is referenced as the solution to similar problems reported by other people, but what steps do I need to take to resolve the problem?

**Comment by shadow87qft** [comment]
> 
> 
> I've still got this problem (see #19818) - This issue is referenced as the solution to similar problems reported by other people, but what steps do I need to take to resolve the problem?

would like to know that too, since i just ran into the same problem

**Comment by zveroboy48** [comment]
Error CODE 4206- Sorry ,you do not qualify.in method stellar.1.local.airdropRegisterLocal
