### ISSUE TITLE
-36 Finder error when copying ~400 files into public

### ISSUE THREAD

**Issue by rodbegbie** [keybase/client#1981]
Stress-testing by dragging my collection of image macros into /keybase/public/rodbegbie/ -- After 7 files, failed with error -36.

my log id: a7f9cfffc386e891ab8e671c

**Comment by strib** [comment]
Whoa, I've never seen this error before:

```
71580 2016-02-10T16:58:43.212234 ▶ [DEBU kbfs(BSR) bserver_remote.go:215] 1175d AddBlockReference id=019cd790167ef56ffe056ed5476c85b55ef0026e94739b095cbb1ca00369cacd45 uid=9ac028119adc92b16a1fb9669d2b2a00 err=AddRef to block with wrong status (1) [tags:FID=obERQ_EFalHoOMVkoQhtUA]
```

This might be related to another block reference bug that came in today (#1973).  I'll try to take a look in more detail tonight.

**Comment by rodbegbie** [comment]
I started it again, and it got further, before stopping with the same Finder error.

New Log ID 5bc82ee1e876903ad29ec01c

(Also, there are now a bunch of 0 byte files in my public/rodbegbie/macros/ -- everything with a filename beginning with n–z is 0 bytes)

**Comment by strib** [comment]
Yeah, I think this was similar to #1973 -- a race condition in our servers, that I think we just fixed.  Can you please try your test again when you get a chance?

(Note, depending on the size of the files and the throughput/speed of your connection to our servers, I wouldn't be surprised if you hit errors due to timeouts on OSX -- it would look the same to you, but the underlying cause would be different. So if you see the same error, please upload new logs.)

**Comment by rodbegbie** [comment]
Thanks! Got the Error -36 again.  New logs: f677175d9f48903bbcd9051c

**Comment by strib** [comment]
Cool.  The good news is that the original error didn't recur (it was a race, so that doesn't mean much, but it is encouraging).

The -36 error was indeed an I/O resulting from a timeout while flushing a file over the network:

```
2016-02-11T19:09:16.476098 ▶ [DEBU kbfs(FBO 99a6186b) folder_branch_ops.go:4154]
 1c58 Sync 0xc8213f62d0 [tags:FID=jfYLACwpuG47ArosCeSpLQ]
...
2016-02-11T19:09:35.528337 ▶ [DEBU kbfsfuse file.go:108] 1cb5 context deadline exceeded [tags:FID=jfYLACwpuG47ArosCeSpLQ]
2016-02-11T19:09:35.528473 ▶ [DEBU FUSE serve.go:817] 1cb8 -> [ID=0x8] Flush error=EIO: context deadline exceeded
```

This wasn't actually much data though -- we know we have a lot to optimize on the sending data side still, but this might have been the result of a temporary network/DNS hiccup, hard to tell.

But the good news is that the background process finished sync'ing the file for you in the background, so I think those files should be in your public folder successfully now.  Let me know if that isn't the case.  Thanks!

**Comment by jonalmeida** [comment]
I've seen this error as well when just trying to open one/two files with coffee shop wifi. Unfortunately, the internet was too bad to send logs, so I'm just adding this note here as a reminder for me to add it when I can reproduce the issue again.

Keybase GUI Version: 1.0.14-20160302170014+fa02591

**Comment by strib** [comment]
@jonalmeida you were just trying to open/read files, not write them?  I'm guessing your internet was slower trying to download the files than your file system timeout.  (Maybe there was a popup error saying "Operation timed out"?)  That may be slightly different than the write issue described earlier in this ticket.

**Comment by jonalmeida** [comment]
@strib I was trying to edit the file iirc through vim. If I repro this while only reading, I'll open a new ticket then. Thanks!

**Comment by strib** [comment]
The latest versions of KBFS for Linux and OS X (`1.0.16-20160627110020+11e6f10` and higher) include both performance improvements, and timeout avoidance, so it should be possible now to upload large amounts of data on all but the worst network connections without seeing an error.  Performance will still be pretty slow, since it involves synchronous round trips to our servers, but it should be a bit faster than before, and more importantly error-free.

Please try it out when you get a chance and let me know if things seem better.  Thanks!

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
