### ISSUE TITLE
How i can add github account to keybase?!

### ISSUE THREAD

**Issue by openpass1** [keybase/client#19833]
Hello!
I create project in github with name: keybase.md and create file keybase.md (inserting confirmation code from feybase), but "your proof could not be found..."
ok, i add new gist (i don't know that is it)) and give name keybase.md and insert code, saved this and "your proof could not be found..."
WTF? How i can confirm my github account on keybase?

**Comment by antonio-gil** [comment]
Considering all what has been happening in the last week, perhaps your issue is _somewhat_ related to the fact that (**AFAIK**) it is not possible, for the time being, add either GitHub or HackerNews accounts to your Keybase profile.

Or course, I can be wrong and your issue is something unrelated, but it can be a possibility.

**Comment by plttn** [comment]
You can add GitHub accounts no problem, they're just not eligible for airdrop.
