### ISSUE TITLE
All operations time out with I/O error

### ISSUE THREAD

**Issue by rrwright** [keybase/client#1993]
All operations seem to time out with an Input/output error.

e.g.: `touch /keybase/public/rrwright/public.file`
`touch: /keybase/public/rrwright/public.file: Input/output error`

my log id: 68478d54c0fb5ca7c0a9ad1c

**Comment by strib** [comment]
I'm guessing you're not having any other internet connectivity errors?

About 1.5 hours ago we had a minor outage of our servers, but that seems to be cleared up now.  Hmmm.  It seems like your operations aren't making it to our servers for some reason.

Do you have any issues pinging `mdserver.kbfs.keybase.io`?

**Comment by hadronzoo** [comment]
I'm also seeing this error with larger files (~600 MB). Smaller files appear to work fine.

**Comment by strib** [comment]
Yeah, depending on network conditions, large file writes can overwhelm our buffers and cause timeouts.  We have ideas for getting around this, but are focusing in other areas right now.  We'll get to it soon I hope.

The original poster was getting IO errors on every operation, not just file writes, so I think the issue was different.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
