### ISSUE TITLE
Cannot enable Finder integration

### ISSUE THREAD

**Issue by reece-bennett** [keybase/client#20093]
Tried checking "Enable Keybase in Finder" in Settings -> Files. 

Nothing happens for a while, then "/keybase is unavailable. Please try again." shows at the top of the Keybase app.

Close and re-open the Keybase app then the following error appears:

![Screenshot 2019-10-03 at 11 33 58 am](https://user-images.githubusercontent.com/6674785/66120368-9c51a500-e5d2-11e9-98e3-b568c8f10d3a.png)

`/keybase` contains just `KBFS_NOT_RUNNING`

my log id: f18787542222b949e86da71c

**Comment by strib** [comment]
@reece-bennett I think the problem is that the name of your local account on macOS includes an `@`.  The finder integration tries to use `/Volumes/Keybase <local-user-name>` as the mount point for the file system (and `/keybase` serves as a redirector mountpoint in case there are multiple local users on your system running Keybase).  However, our code isn't expecting an `@` since in the local user name -- for security reasons we whitelist the characters that are allowed to be in the mountpoint name, and `@` isn't one of them. (See https://github.com/keybase/client/blob/89317cf5ea6f2e1b09e5d515149bc77325e5a3ec/osx/KBKit/KBKit/Component/KBComponent.m#L53 if you want the nitty gritty details.)  cc @cjb.

Perhaps we should allow that character, but it would take a while to get a release out with that change.  But it's pretty easy for you to change the mountpoint yourself.  For example, you can do this from a terminal:

```sh
keybase config set mountdir /Volumes/Keybase\ \(me\)
```

And then restart the Keybase app, and see if that helps.  It doesn't really matter what the mount point is, as long as it's not `/keybase` or `/Volumes/Keybase`.  (We discourage you from putting it in your home directory, as that will slow down or confuse programs that back up or crawl your home directory.)

**Comment by reece-bennett** [comment]
@strib Thanks, that seems to have worked!
