### ISSUE TITLE
KBFS is producing very much IO and network traffic

### ISSUE THREAD

**Issue by KizzyCode** [keybase/client#20106]
Keybase is producing extremely high read/writes over time (more than 100GB/100GB after a day), the same goes for network traffic (even in constrained mode).

My current OS is macOS Catalina 10.15 Beta (19A578c), my log ID is `f805cb040890db72b028e21c`

**Comment by strib** [comment]
@KizzyCode Looks like you have a new, large file in a shared private folder with another user.  Your device is trying to prefetch it, but is running out of space in the cache because it hit the limit of available space we let it use up on the local disk.  It's supposed to be canceling the prefetch in that case, but there seems to be a bug that's preventing it, and it keeps trying over and over -- and when Keybase restarts, it starts again.  I'll look into that.

In the meantime, you can ask whoever wrote that large file (I'm not sure if it was you, or the other person), to put at least 10 new files in the folder.  It's dumb, but that should prevent the prefetching of the large file.

As for "constrained mode" -- you're not running in constrained mode.  There's no way to configure constrained mode for macOS right now.  If you're going by the instructions in https://keybase.io/docs/kbfs/understanding_kbfs, note that that's for 4.6.0 or above, which isn't released yet.

**Comment by KizzyCode** [comment]
Ah, ok; I should have checked the version number in the doc 🙈
Ok, I've created 20 empty files (``for i in `seq 0 19`; do touch "IgnoreMe.$i"; done``), and so far this seemed to work; thank you :)

**Comment by strib** [comment]
Great!  Sorry about the doc confusion, I jumped the gun because I was worried I'd forget to update it after the release.  Let me know if you have more issues.

**Comment by KizzyCode** [comment]
How long will it take until 4.6.0 is released? No offense, but honestly the entire "prefetch" "I know what you want", "Hehe, 2.7GB kbfs_block_cache" stuff is driving me crazy :D

**Comment by strib** [comment]
Scheduled for next week, but no promises.
