### ISSUE TITLE
KBFS reset request

### ISSUE THREAD

**Issue by diddledan** [keybase/client#20131]
Please can you perform a server-side reset of my KBFS folders. I am unable to access private/diddledan.

my log id: ec8c9f2880e7344cfc47b41c

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8xj0dl VlvFZoT0Q9wznoI cYcPz7LxyNIUgFL C3ch99EVeP5FMAt Dva3w65cg0564A3 IGwexkTd8mejhJk 9Zd2LDBSEXeMMsO MKUq3cwgGLdKSqT 3URI2DmhD7OR8Gw x2bTtATJuX24QZr 4KqCrco8hbW4aI1 PBeBya96Nlf5nKK rOirt4K3ad7Pnoo RhYuz7g2oviCdzj l4KVaaZBSn4DVBb DwPZkvDEkm49lwe Tj6OI0sinHFxWIg sg4tkuhnUHcShha NBVWaD726plLYkV MR861g3iihO2jEn Owu1y4K9RPEuwLp 6Xu4xVI1y0mLBb9 8NEAb0OCuqva2ra PKq9uJ0nNsRmCPS . END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I already messaged you directly on Keybase since I saw the log before I saw the github email, sorry about that.  I put up a PR to solve the particular issue you're seeing with an already-reset folder: #20135.

I can give you a custom build with that fix, or you can wait for the next release (should be coming next week).

**Comment by diddledan** [comment]
This is now fixed - I managed to issue a manual reset with the updated client. Many thanks :-)
