### ISSUE TITLE
KBFS can't load folders

### ISSUE THREAD

**Issue by jakehead20** [keybase/client#20353]
Version: 4.6.0-20191010021431+134c2d892b
I've seen issues that were closed talking about the folders' data being in a corrupted state, and I've had keybase for a while, so that's most likely the case. What process do I need to take to reset it?
Edit: The issue's only with my private folder (keybase/private/veren)

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by jakehead20** [comment]
Here's the ID: 363dfc0493cfe6643f90741c

**Comment by strib** [comment]
It seems that, about a month ago, you hit an old bug (since fixed in the latest version) that basically let you upload incomplete data when initializing your private folder.  It looks like you hadn't written much (or maybe any) data to it yet, but if there's something in there you need to recover, let me know and I can look harder into recovery options.  Otherwise, I can reset it for you.  Please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/veren because all the devices that have access have been revoked."
```

and post the results here.

**Comment by jakehead20** [comment]
Nah I've got nothing on it, so I'll take that quick reset. Thanks!
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkFpHun1 UuUmd1213jRXxXX RK1AFUDPa0cl2Rr oCujvg3WLC364pf dCP2MmE2GD3boGB SVnLfmRyvlalPIu lQUREJ57zj8z0i8 FHmloIfZGHdktgM Qfl7j5rwnRDHb6i qAm8vbwzrT4a5Bj rcUNT25drAjEflp LbuwOUQDYuaqUtb 1UWgs5Ip2z3bTjI 31jnoO2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49opC RftRbFrIINlBGZl u19OjxPn2WQlO81 BykXXvEuptz5lap H7h9TQNUDCol0LZ tRptM1Y2X3T6eXr 75mDIRppSSSLlP1 xwCHW. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok cool, I've reset it on our end. Now do this on one of your current devices and you should be good to go:

```sh
keybase fs reset /keybase/private/veren
```

(Might requite a Keybase restart on other devices.)

**Comment by jakehead20** [comment]
It's been resolved. Thank you so much for your time!
