### ISSUE TITLE
Logged in but can't view my private directories

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#2108]
```
Ryans-MBP:ryan_singer ryan$ ls
ls: .: Permission denied
```
```
Desktop app:
    status:    running
    version:   1.0.13-20160223170009+a3f3559
    log:       /Users/ryan/Library/Logs/Keybase.app.log

Config path:   /Users/ryan/Library/Application Support/Keybase/config.json
Default user:  ryan_singer
Other users:   blockchainhealth
```

my log id: 1b690402eb7ceb3e600afa1c

**Comment by strib** [comment]
Hi @RyanSinger -- this looks like a rekey issue.  That is, you added the device `Ryan's MBP` to your account today, but your private folder isn't yet keyed for that device, so the device can't read the contents.  

Usually, when you use your paper key to provision a device, KBFS will start up right away, and have access to that paper key, and use it to rekey all your folders.  In your case it looks like that didn't happen.  I would guess it's due to logging in and out of multiple accounts, which probably flushed the paper key out of memory before KBFS had a chance to try to rekey the folders.

Another problem is that it's supposed to pop up an automatic paper key prompt for you after 10 minutes if your folder still isn't unlocked.  Not sure why that didn't work in this case, looking into it.

The folders should get rekeyed as soon as you power on another device in your account that could previously access the folder.  Right now we don't have a manual way to unlock the paper key.

**Comment by RyanSinger** [comment]
The reason I created Ryan's MBP was because of the earlier bug involving multiple accounts. It's the same laptop, and I never deleted any keys. Could I force it to use the other set?

**Comment by RyanSinger** [comment]
Also, Is John's problem on https://github.com/keybase/client/issues/2109 the same one or a different one? The symptoms are the same to us, but you may have more insight from the logs. He didn't rekey his primary account, he only added the new one and then switched back.

**Comment by RyanSinger** [comment]
Ok. Your fix worked. John's is going to be harder, though, because his only devices are the local copy that seems to be screwed up and the paper key.

**Comment by strib** [comment]
Once you re-provisioned your device, the old keys are gone.  In fact you should probably revoke them from your sigchain.

#2109 is different, I will respond there.

**Comment by strib** [comment]
I found the issue that was preventing the paper key prompt from coming up after 10 minutes.  In code review now.

**Comment by strib** [comment]
The fix for prompting for your paper key after 10 minutes is in today's current release.
