### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by oleshka311** [keybase/client#21112]
Why can not I take part in the airdrop?

**Comment by oleshka311** [comment]
My username zzzoleh

**Comment by trixxyz** [comment]
The airdrop goes in alphabetical order so you’ll be reallllllly late on getting your drop, they haven’t gotten to me yet and I’m a Tr

**Comment by Parameso** [comment]
i have a badge and my username is roxiel but i dont recieve nothing :( why?

**Comment by trixxyz** [comment]
How do you check if you have your badge?

**Comment by Parameso** [comment]
i check on my profile where is my picture profile ! Where it has always been :(

**Comment by trixxyz** [comment]
If it's saying qualified and then unqualified it means you're banned :/ Apparently they banned tons of account in the process banning all accounts that have used a vpn, so if you were signed into to keybase on your phone app and turned a vpn on it blacklisted you, same with your pc. Keybase staff won't reach out to anyone about this issue :/

**Comment by Parameso** [comment]
Go on, have you seen the trending theme where a person is called Ugamez,
Ugamezz, Ugamezzz, Ugamezzzz?  to that if they have given it to me, I have
gone from legal and I have joined many of my friends since October, uni
github when it was more difficult so I was "pre-verified" it is impossible
for me to be blacklisted because I still have my  medal, however my letter
"r" has passed and I have not received mada, however the bot is stupid and
has not recognized some names that are sure to be multi-accounts, this is
badly done and this is not professional.
