### ISSUE TITLE
Airdrop not received 

### ISSUE THREAD

**Issue by FrederickE** [keybase/client#21168]
My kebase username is fredo342. I joined the airdrop since October never created two accounts except that I have a laptop, a phone and a desktop in my office connected.
I was disqualified for no reason and even when I rejoined the airdrop on the 15th of November, I have till now received no airdrop.
If you have a system that can scrutinise my account, please run a check on my account and you will see I never created any double account. 
Please be fair to all. That's all I ask.

**Comment by munnamizan1494** [comment]
Same problem here bro

**Comment by barbagallopaolo** [comment]
Hi , not reciver airdrop in my wallet, VERY VERY FAKE.

**Comment by barbagallopaolo** [comment]
![FAA73E7B-5F5E-4983-AA80-F1331AA589CF](https://user-images.githubusercontent.com/51059933/69382360-35d63280-0cb7-11ea-99ac-31c8ff64ec57.png)

@barbagallopaolo - an update!

:tada: :tada: :tada: :tada: :tada:

The Stellar Space Drop program is back on. You are still registered; **there is nothing for you to do.** The first distribution will happen November 15, and you should expect more Lumens every month.

**Why November 15?**

In case you missed it, we were forced to shut down registrations due to a swarm of bad actors. GitHub and HackerNews were both under attack and reached out to us.  No one could then join. YOU squeaked in, though. So you're in.

So: **we have spent the last month making it easier to participate**. Now your friends and family qualify. Even if they’re not programmers.

If you'd like to invite anyone:

  • click "New chat" from your inbox
  • invite them by phone number
  • chat with them (encrypted!) while you both await November

And apologies for the delay. But 100 million Lumens will be going out shortly. You will get your share.

:heart: @spacedrop

P.S. Stats & Info: https://keybase.io/airdrop


FAKE FAKE FAKE  SCAM

**Comment by busterman** [comment]
My name is Edward Baton, account edbaton@gmail.com. September 9th 2019 i received a notice I was receiving free xlms and would receive them each month until alwereas gave away. October I did not receive any lumens, I check my account, it showed three green check marks I was qualified, thinking everything is ok, I would be included in the airdrop for November. I never received any lumens in November. WHY? This is very unfair by Stellar and Keybase to arbitrary cancel someones without any explanation as to why their account has been disqualified. I only have one account with the correct phone number; October I check all of my account info, all is correct. I received lumens during the first airdrop and can't figure out what I've done wrong, not to receive any lumens in November? Someone from Keybase or Stellar, please let me know what I've done wrong so I can correct it.
Thank you.

If you need my phone number or any other information to check my account for qualifications, please let me know.
