### ISSUE TITLE
I can not join the airdrop

### ISSUE THREAD

**Issue by sredov** [keybase/client#21170]
Hey.  What can be connected with the fact that I can not join the drop?  I have a UK country.  Number confirmed.  But he will not let him drop.

**Comment by yann-Solol** [comment]
Same from France since more than 3 monthes. I first think about airdrop was just blocked but there is no answer despite some bug reports, I don't understand, I get success verification message, and as I click on Join, I get 'sorry you're not qualified " and on both Android, PC, and professional PC...
