### ISSUE TITLE
Please reset my filesystem

### ISSUE THREAD

**Issue by iflowfor8hours** [keybase/client#21609]
I cannot view my files from any keybase authorized device.

my log id: 33d9308f0ef85194609c841c

**Comment by strib** [comment]
Hi, yes it looks like you've been locked out of your folder since 2016, likely due to an ancient bug that has since been fixed.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/iflowfor8hours because all the devices that have access have been revoked."
```

and post the results here.

**Comment by iflowfor8hours** [comment]
```
[matt@toolbox]~% keybase sign -m "`date` Please reset folder /keybase/private/iflowfor8hours because all the devices that have access have been revoked."  

▶ INFO Starting background server with pid=45826
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkJDB220 qeOR5BpVCs2Prld 3pA1aBblqRpG4Gq 3R9oI31YxMVQlQ9 uL3eYwnnC9fJhKt NteeiR4JATdJ3aW 5wGmM4Vgaxpf1dn dVDY6A1EuJ0FFnV 6RYy4Co4O9G7Ib6 JyQeFubk62GpLwl PaQWnRHRN1OJFCI WjKzxQlFDUSz7LD HNa7DnI6BWrUCb8 VO8upJwpE12wejQ hcERQrPOM2RGBgE elgJQIu5rQ3zly0 mriN6jN0RDxFNpN mwaim5i1hbjlWTd IPWvqB9FIzIdRfg DRMY7NYlmIv9YAA PZ5O6MMiOLsEj2O 4ZWwa2URqVAZjH3 yn094uSV5nLWQaL pGBwL5iqClybja. END KEYBASE SALTPACK SIGNED MESSAGE.

```

**Comment by iflowfor8hours** [comment]
Apologies for this falling off my radar @strib.

**Comment by strib** [comment]
Sorry for the delay, I was on vacation.  I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by hoodieless** [comment]
hi there @strib , i don't know if this issue is still being tracked, but I fell for the same issue and was hoping to get some help. I have followed the steps listed above and changed as needed.

keybase.exe sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/hoodieless because all the devices that have access have been revoked."                                                                        BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkEbWUdx EZt0YE2Lv7FdqRz WJ1xkhSvKElSWLr ujmjFh5OaMrcZBT kx4UTl4v9G2gIjZ 0o623BXriqEj6Do TdAcpOiRY9UP65m cuiBk6Lhmb9VWge fhEwwW3Z1v6rQqi R3RZzRxg2g14hyv Zfqso9hAuKQVF6o 7lsSfu7Je63DH35 kiqhrW6sTKWdRO3 A8B3DNym8qH9bGJ ihi1VdaGUF9fbPF CbfzTsaFLZVEMoR dfTOlPz7w4lu4SB vcl9pcH6a2DGbEL hWwDl77A06qKiBM 3O3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
@hoodieless can you please open a new ticket, do a `keybase log send` from the device having the problem, and put the log ID in the new ticket?  I don't like to mix users, and I need to see a log to make sure this is the right problem to fix.  Thanks!

**Comment by iflowfor8hours** [comment]
great, this worked, and it was completed ages ago. Thanks for addressing it, @strib
