### ISSUE TITLE
December Airdrop not recieved

### ISSUE THREAD

**Issue by 101010101010101** [keybase/client#21620]
Hey guys, I didn't receive my final XLM airdrop. Please assist. Thanks

**Comment by miss-evelina** [comment]
Same here but my husband got his airdrop 😔 Feels a bit strange

**Comment by 101010101010101** [comment]
Yeah, that's definitely strange. And there isn't any official way to contact them directly.

**Comment by waggzbtc** [comment]
Keybase has cancelled the Space Drop. They claim that it’s because of fake accounts. I’m calling BS. They cancelled everyone after the 1st 200k accounts no matter what. Then say they split the remaining funds up evenly. But...Something is fishy. I’m looking through keybase’s payments. And it seems their source wallet has been creating new wallets and depositing the exact amount in each new one that should have been deposited in existing accounts. 

And conveniently, Keybase admins won’t address anyone’s questions on this page and continue to ignore everyone. 

My account is real and verified. But keybase unverified me (so that I wouldnt get paid) and left my account open (must NOT be one of the accounts that they find to be unworthy of staying open, just not worthy of being paid). 

Read their BS excuse here: https://keybase.io/a/i/r/d/r/o/p/spacedrop2019
