### ISSUE TITLE
filesystem failing on MacOS startup

### ISSUE THREAD

**Issue by hoffmang9** [keybase/client#21907]
On MacOS start up, I continually have the local filesystem drivers fail. It seems to recover with an application restart

May be related to #20234

my log id: a40b46f73e8e8f7d21eca61c

**Comment by strib** [comment]
Can you please provide more details about what the failure looks like to you?  Nothing is standing out in the logs at first glance.  Thanks!

**Comment by strib** [comment]
Is it the same error message at #20234?

**Comment by hoffmang9** [comment]
It was not the same error specifically. I received a dialog box that was to the effect of "Could not start filesystem, restart Keybase shortly and it should work." I did that and it appeared to work but I went into the Keybase App UI and chose a /keybase/private/hoffmang,otheruser/ and selected "Sync on this device" and I got a kernel panic in watchdog and was forced to restart. It came back normally and I restarted to see if I could pop the dialog box, but now everything is working.

Game to try to help hunt the problem down.

**Comment by strib** [comment]
Did you get this error just before submitting the log?  It's weird, I don't see any errors like that recorded in the log since December 12th.  I guess maybe the kernel panic could have prevented the logs from being flushed?

Do you think the panic was related to Keybase at all, or was that something else coincidental?

But in general, that error happens when we try to load our "redirector" process that mounts KBFS for all local users at `/keybase` or `/Volumes/Keybase`, depending on your OS version.  The process of starting the redirector requires reading and verifying a signature on a binary file, which can be slow on some systems due to CPU or disk slowness (esp. when lots of other things are starting at the same time), and if it takes more than a minute, we just time out and ask to retry later when the system will hopefully be less loaded.  It's annoying, but I'm not sure we have a better solution in mind right now.  Does that sound like it's what can be going on?

**Comment by hoffmang9** [comment]
Your description of the underlying reason makes perfect sense as I've been seeing this iMac boot slowly enough that I'm about to investigate the filesystem.

I'll close this for now and re-open if I see it happen again in any way that doesn't correctly recover per the method above.
