### ISSUE TITLE
cannot create any files: No such file or directory (Windows, cygwin)

### ISSUE THREAD

**Issue by jczimm** [keybase/client#2199]
Keybase GUI Version: 1.0.14-20160302142729+f684ffa

I cannot create any files in my public or private directory.

```sh
{ public }  » touch file                                                /cygdrive/k/public
touch: cannot touch ‘file’: No such file or directory
```

Also, saving files from applications (e.g. Notepad), I get a similiar "File not found" error.

**Comment by maxtaco** [comment]
Try `/cygdrive/k/public/<yourname>`  or `/cygdrive/k/private/<yourname>`

**Comment by jczimm** [comment]
Apologies.

However, after some trials (attempts to access), k: is now unavailable altogether.

**Comment by maxtaco** [comment]
Thanks for your feedback, can you perform a `keybase log send`?

CC: @zanderz  and @taruti

**Comment by jczimm** [comment]
Not sure if the log was sent successfully, but my id is 246dc66dd8b59b7b8ededf1c.

```sh
- WARNING error opening log "C:\\Users\\Jacob\\AppData\\Roaming\\Keybase/keybase.kbfs.log": open C:\Users\Jacob\AppData\Roaming\Keybase/keybase.kbfs.log: The system cannot find the file specified.
- WARNING error opening log "C:\\Users\\Jacob\\AppData\\Roaming\\Keybase/Keybase.app.log": open C:\Users\Jacob\AppData\Roaming\Keybase/Keybase.app.log: The system cannot find the file specified.
```

**Comment by maxtaco** [comment]
Looks like `log send` is broken on windows too, we have a few things to look into. Thanks @jczimm!

**Comment by jczimm** [comment]
Oh ok.  No problem!

**Comment by taruti** [comment]
Probably we should pre-allocate some favorites for new users? That would make things less confusing.

As for the log situation with the current code the log is probably `keybase.log` instead of e.g. `keybase.service.log`. To get kbfsdokan logs the right way currently is to run it with `-debug` and it will log to stderr. After the new logging stuff is in and in kbfs-repo getting it to log into a log file should be doable.

**Comment by taruti** [comment]
Probably we should pre-allocate some favorites for new users? That would make things less confusing.

As for the log situation with the current code the log is probably keybase.log instead of e.g. keybase.service.log. To get kbfs logs the right way currently is to run it with -debug and it will log to stderr. After the new logging stuff is in and in kbfs-repo getting it to log into a log file should be doable.

**Comment by strib** [comment]
> Probably we should pre-allocate some favorites for new users? That would make things less confusing.

@taruti: yep, we are planning to do this for the next milestone.

**Comment by jczimm** [comment]
I installed the newest version and things seem to be fine now.  Thanks!
