### ISSUE TITLE
Can't open a shared folder

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#2219]
```
Ryans-MacBook-Pro:blockchainhealth,jgcrossman2,ryan_singer ryan$ ls
ls: .: Input/output error
```

my log id: 0c88e9ee44c82f725361561c

**Comment by cjb** [comment]
Sounds like there's something wrong with the proofs/tracker statement of blockchainhealth or jgcrossman2 -- try:
```
keybase track blockchainhealth
keybase track jgcrossman2
```
agree to retrack if prompted and try again

**Comment by strib** [comment]
Hi @RyanSinger.  The error is being caused by:

KBFS:
```
Lookup error=EIO: 1 track component failed
```

Keybase service:
```
91729 2016-03-03T22:32:46.409499 ▶ [DEBU keybase identify2_with_uid.go:362] 1253 - runIdentifyUI(blockchainhealth) -> 1 track component failed
```
Looks like your tracking statement for `blockchainhealth` is out of date or broken.

@cjb, why didn't he get a tracker popup window?

**Comment by cjb** [comment]
@strib Good question, don't know, can't tell from the log. @chrisnojima, could the `breaksTracking` bool changes have broken this?

**Comment by cjb** [comment]
@RyanSinger Our theory is that blockchainhealth is currently broken for tracking -- you had an HTTPS file proof, that file no longer exists on your server, and that's why KBFS denied the share.  You should be able to see this for yourself by running `keybase id blockchainhealth`.

However!  Our GUI should have popped up a tracker window when it failed, allowing you to retrack with the missing proofs.  Did you see any tracker popups when it started failing?

**Comment by RyanSinger** [comment]
That fixed it.

**Comment by cjb** [comment]
@RyanSinger FWIW, still curious to know whether you saw a tracker popup for blockchainhealth at the time it was broken.

**Comment by RyanSinger** [comment]
Nope.
