### ISSUE TITLE
Issue creating a private shared folder between a friend of mine and me

### ISSUE THREAD

**Issue by tuxnco** [keybase/client#2220]
Keybase helper keeps notifying me with the message:
**`KBFS: Verifying and downloading errored`**
`objects is not a Keybase user.`

my log id: `831f2629159b492a48165e1c`

**Comment by tuxnco** [comment]
For instance the shared folder exists and is working OK.

**Comment by strib** [comment]
That happens when you are trying to access a folder via `/keybase/private/objects` or `/keybase/public/objects`.  Your log shows that you (or something running on your machine) is trying to access those paths.  They imply that you are trying to find the public or private folder for a Keybase user named "objects", which doesn't exist.  If you want to look at a private shared folder, you need to access `/keybase/private/<yourname>,<yourfriendsname>`.  Does that work?

**Comment by cjb** [comment]
@strib Hm, since there's a lookup for ".git" 1ms before there's a lookup for "objects", it seems straightforward that it's a `.git/objects` type of dir that's being looked up automatically (for some reason).

**Comment by cjb** [comment]
@strib (just reserved keybase username "objects")

**Comment by strib** [comment]
Hmm, yeah, good catch, that makes sense.  Shells are weird.

@tuxnco: what private shared folder were you looking up exactly?  Was there any error on the command line, or just that popup error (which is likely unrelated)?

**Comment by tuxnco** [comment]
Hi @strib, exactly, I was lookup up for `/keybase/private/tuxnco,tristan0x` , the first (and only) private keybase share I created. I had accessed `/keybase/private/tuxnco` successfully just before that.

**Comment by strib** [comment]
Ok great.  As far as I can tell, `/keybase/private/tuxnco,tristan0x` worked perfectly fine for you.  The popup error was unrelated.  Maybe it's just an empty directory.  Unless you saw an error on the command line, I think you are all set.

**Comment by strib** [comment]
(We will suppress the bad popup error in a near-future release.)

**Comment by tuxnco** [comment]
Ok great, we're all set and can close the issue I guess :)

**Comment by strib** [comment]
Great!
