### ISSUE TITLE
need file system reset.

### ISSUE THREAD

**Issue by mauilion** [keybase/client#22346]
I think I have managed to maroon my file system access as the devices previous to the current set are all revoked now :( 

Can you please reset my kbfs stuffs?

my log id: d30e4fc6d3cdfe9cdd167a1c

**Comment by strib** [comment]
Your KBFS folder has been out of commission since early 2017.  I think the only devices that had access are now revoked.  We had some old bugs back then that under certain timings when you added/revoked devices, you could lose access to the folder. Those should all be fixed now.

I can reset the folder now, but I need a signed statement from you to do so.  Please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>:  Please reset folder /keybase/private/mauilion because all the devices that have access have been revoked."
```

and post the results here.

**Comment by mauilion** [comment]
Thanks issue is resolved!
