### ISSUE TITLE
[Docker slim] wait is not a valid ctl command

### ISSUE THREAD

**Issue by vladionescu** [keybase/client#22681]
https://github.com/keybase/client/blob/e4baaaacbc13b6861afe4dde27e43c2bc25cb6e8/packaging/linux/docker/slim/entrypoint.sh#L27

In the slim Docker container's entrypoint it calls `keybase ctl wait` but as of keybase v5.2.0 'wait' is not a valid command to 'ctl'.

This results in the error `No help topic for 'wait'`.

I am only encountering this issue when trying to run the container in Google Cloud Run. Running it locally on Docker (macOS) you don't notice the error.

**Comment by vladionescu** [comment]
It worked fine when I changed that line to `keybase ctl start`.

**Comment by pzduniak** [comment]
Did you build the images yourself? `wait` was introduced, I believe, in 5.3.x.

**Comment by vladionescu** [comment]
I'm building an image on top of `keybaseio/client:stable-slim`.

A slightly out of date Dockerfile is here: https://gist.github.com/vladionescu/a1d666f3b8fc6fdffdbcdd59bf122b59

**Comment by Daniel-Wang** [comment]
Hi @vladionescu, the wait command isn't in the release v5.2.0, which would be the version you have from `keybaseio/client:stable-slim`, it was added to the source code right after we cut a release from master. So if you build an image from source, you should get the wait command working, otherwise it will be in the next release

Thanks for the notice though!
