### ISSUE TITLE
Logged out with weird prompts?

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#2281]
Keybase GUI Version: 1.0.14-20160310170037+a2e4734

Not sure what was up, but just had the following notifications appear on my Mac, along with a popup window giving me information on @malgorithms. Tapping into the Keybase menu bar app let me know I was now logged out, and logging back in via command line seemed to resolve.

This is probably some sort of expected issue, but wanted to report. Didn't take any action, was just browsing Safari and got these messages.

![screen shot 2016-03-10 at 11 57 54 am](https://cloud.githubusercontent.com/assets/611354/13679100/a6fb56c2-e6b7-11e5-9107-96b52acac8ad.png)
![screen shot 2016-03-10 at 11 57 49 am](https://cloud.githubusercontent.com/assets/611354/13679103/a882504a-e6b7-11e5-8699-6f53f7c408f6.png)

**Comment by malgorithms** [comment]
Weird, I just got this too, with the latest update. I accepted the update, and when it restarted I got the above popup window too. I was less surprised because it was me (!) but I hadn't seen it before after a restart. here's my log...which I captured right after the update:

20783a04530657faf01ec41c

also, perhaps related, I was surprised to be logged out, since I was using OSX keychain...

**Comment by maxtaco** [comment]
All of this changed yesterday with Patrick's latest changes to login.  The
login 2x2 still haunting us no doubt. @patrickxb can you take a look?

**Comment by patrickxb** [comment]
Looking

**Comment by patrickxb** [comment]
If the service restarts, you will completely lose your api server session.  That is new. 

And when the service starts, it will try to auto login with secret store.  I did test this with OS X keychain and it worked.

I have no idea why either of these changes would cause a tracker popup for chris.

In my patrickxb/CORE-2635-1 branch I am in the process of fixing the 2x2, and have gotten rid of the LoggedIn*Load() functions so far.  I have a feeling that could be contributing to this...

**Comment by CameronBanga** [comment]
Adding on here, continuing to receive similar notifications to what I received yesterday, but not being logged out this time. If there's anything else I can do to diagnose, let me know. For some reason, my GitHub notifications aren't working in this thread, so if you need something, send me an email, address is in my profile.

![screen shot 2016-03-11 at 10 48 15 am](https://cloud.githubusercontent.com/assets/611354/13708935/da19c61e-e776-11e5-9a2f-4c45389bdf0e.png)

**Comment by strib** [comment]
Hi @CameronBanga, thanks for the report.  There are two things going on here.

1) The "context deadline exceeded" error means that some single file system operation took more than 19 seconds, which is the timeout we have for OSX file system operations.  In this case I looked at the log you left over in #2297 (68c4f4f671e601a3a932061c), and it looks like this happened when you were loading `chris`'s public folder for the first time.  Looking at the service log, it seems that loading his sigchain took nearly 15 seconds!

```
2016-03-11T09:49:51.228963 ▶ [DEBU keybase sig_chain.go:869] 22b - SigChainLoader.Load(23260c2ce19420f97b58d7d95b68ca00) -> (true, ok)
2016-03-11T09:49:51.228986 ▶ [DEBU keybase loaduser.go:126] 22c * SigChainLoader.Load: chris: 14.460860805s
2016-03-11T09:49:51.229014 ▶ [DEBU keybase loaduser.go:126] 22d * LoadSigChains: chris: 14.460891306s
```

^ @maxtaco.  I'm not sure why this would happen, unless you had a really bad network connection, or maybe you had an interactive popup window that you were slow to respond to (but I can't think of what that would be).

2) The "/keybase/DCIM" error is because some program on your machine seems to be looking for a digital picture subfolder under the `/keybase` mountpoint.  The popup is intended to instruct users how to use `/keybase`, but it doesn't work too well for automated programs like that.  I'll add "DCIM" to the list of exceptions we have that won't pop up the error.

**Comment by maxtaco** [comment]
cc: @patrickxb 

chris does have a big sigchain.  there should be some finer-grained timers in there too as to what was taking the time...

**Comment by epaga** [comment]
FWIW I get this, too ("Keybase.app is not a Keybase folder").

Log id: 3f74cae412b8ca916116f91c

**Comment by strib** [comment]
Yep, see #2314.  That is fixed in master and will be fixed in a released build soon.
