### ISSUE TITLE
Error messages on Ubuntu

### ISSUE THREAD

**Issue by dhgwilliam** [keybase/client#2283]
I am now getting two notifications pretty frequently as I navigate my /keybase folders. Previously I tried opening a bunch of my tracked users' public folders to see who was using the KBFS alpha but now when I try to go in to a folder which has no content I get this:
![2016-03-10-105009_1407x89_scrot](https://cloud.githubusercontent.com/assets/36499/13680562/f2049d7c-e6ad-11e5-9b94-01ad1c5c50fb.png)

And when I go in to a folder that _does_ have content I get this:
![2016-03-10-104942_1421x100_scrot](https://cloud.githubusercontent.com/assets/36499/13680563/f206603a-e6ad-11e5-961d-21fa7566916b.png)

my log id: e332b58e09aa81cbaab0711c

**Comment by strib** [comment]
Ah, the "HEAD" one is definitely the fault of something I pushed yesterday.  I will fix it, and look into the write access issue.

**Comment by strib** [comment]
Thanks for the report @dhgwilliam.  Both will be fixed in the next kbfs build.  For the record, the first one wasn't new; it would happen any time you tried to do a lookup (as opposed to just a readdir) in an empty public folder.  (E.g., bash completion or custom shell lookups.)  The second one is probably due to a git shell looking up HEAD in parent directories up to the root, and tickled a new error popup that wasn't exempting that particular lookup name.
