### ISSUE TITLE
Saltpack documentation inconsistency

### ISSUE THREAD

**Issue by Phaiax** [keybase/client#2294]
https://github.com/keybase/client/blob/master/go/saltpack/specs/saltpack_armor.md
In the example at top

BEGIN SALTPACK SIGNED MESSAGE

is used. At the end of the page

BEGIN([a-zA-Z0-9]+ )?SALTPACK(ENCRYPTEDMESSAGE)|(SIGNEDMESSAGE)|(DETACHEDSIGNATURE)

is given as regex. See missing spaces.

**Comment by oconnor663** [comment]
The missing spaces in the [framing section of the spec](https://github.com/keybase/client/blob/master/go/saltpack/specs/saltpack_armor.md#framing-the-basex-payload) are because we strip all the whitespace in step 1, so what we match against the regex in step 3 won't have any spaces left. I *think* this is right, but let me know if it still looks wrong to you.

For what it's worth, I don't think the code in our implementation exactly matches the rules here. We [still have the spaces in our regex](https://github.com/keybase/client/blob/master/go/libkb/stream_classifier.go#L220).
