### ISSUE TITLE
I tried editing Chris's public files in Sublime Text and all I got was a crummy beach ball.

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#2297]
Probably very much expected, but wanted to log and place here.

Viewed @malgorithms's whoa it worked.txt file in Sublime Text using OS X. Added a new line and hit save, just because I hadn't done this and was curious what would happen.

Was prompted for my account credentials, went ahead because YOLO, and was presented with a spinning beach ball for about 3 minutes before I finally force quit Sublime Text. 

my log id: 68c4f4f671e601a3a932061c

**Comment by strib** [comment]
Hi @CameronBanga, thanks for the report.  Sublime acts very strangely with the file system.  We've run into similar problems before, though I've never seen the epic 3-minute beach ball.

As far as I can tell, when sublime sees that you don't have permissions to edit a particular file, it tries to run as root (hence being prompted for your account credentials), since of course root should be able to edit any file on the computer.  But in KBFS, that isn't the case -- not even root can edit someone else's public files.  So, when Sublime tries to edit the file as root, KBFS sends an error back.  Unfortunately, Sublime appears to just ignore all errors when in root mode.  At least, the last time I tested this, Sublime actually seemed to succeed when editing the file.  (I didn't get the beach ball, just a success.)

In your log, I see KBFS returning the correct error:

```
97426 2016-03-11T11:49:53.337099 ▶ [DEBU kbfs(FBO 7f4f5b66) folder_branch_ops.go:3542] 37f3 Truncate 0xc82ee5c820 0 [tags:FID=wugIXgBdSYtKInFGZMBYJA]
97427 2016-03-11T11:49:53.337821 ▶ [DEBU kbfs(FBO 7f4f5b66) folder_branch_ops.go:3543] 37f4 Done: cameron does not have write access to directory /keybase/public/chris [tags:FID=wugIXgBdSYtKInFGZMBYJA]
97428 2016-03-11T11:49:53.338602 ▶ [DEBU kbfsfuse file.go:113] 37f5 cameron does not have write access to directory /keybase/public/chris [tags:FID=wugIXgBdSYtKInFGZMBYJA]
97429 2016-03-11T11:49:53.338641 ▶ [DEBU FUSE serve.go:838] 37f6 -> [ID=0x9] Setattr error=permission denied: cameron does not have write access to directory /keybase/public/chris
```

After that, I see a bunch of periodic `Access` and some `Getxattr` calls to the file, but it doesn't look like KBFS ever hangs.  I guess Sublime is just really not happy about something, but hard to know what.  I suspect it just isn't coded to handle errors in root mode, and unpredictable things happen.

Sorry about the bad experience!  We should probably file a bug against Sublime at some point, if we can narrow it down a little more.
