### ISSUE TITLE
Time out when reading large file in keybase files

### ISSUE THREAD

**Issue by rohitdatta** [keybase/client#23354]
I tried to download a 4.7 GB file from keybase files, and compute an md5 hash on the file and it timed out

my log id: f622a62e0425eede199af11c

**Comment by strib** [comment]
Hi!  From the log I'm not totally sure what happened  It looks like everything was going along fine, and then it suddenly took like 20s to either read some data over the network, or read/write some data to disk.  macOS forces us to have a 19s timeout on file system operations, so that's when it timed out.  Maybe just a fluke network/hardware hiccup?  I'd try it again and see if it's any better.

**Comment by rohitdatta** [comment]
Yeah looks like it was just a fluke, tried again and it worked.
