### ISSUE TITLE
Lost access to private KBFS

### ISSUE THREAD

**Issue by Tunas1337** [keybase/client#23968]
I have lost access to my private KBFS due to what I assume was a botched upload of files to it. I can only open it on the computer from which I initiated the upload, but not on my phone anymore, and not on any newly-added device afterwards. My access to the folder from the device that had the botched upload is quite sporadic, slow and full of errors (see log id below).

My signed statement of this is below:
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkClGC36 M9HjdNSPVxDfOu6 4zE3GBHgr1qPXMm gyKqfmMYjy3WORj Ar89vF7t0DefoXi XpSvfskdIXWdmB4 KHnbaTxniRwjc8S HJtwjbwXsKylBCp fta9d8ZOJBTd417 6OAOeCDedbLVsy3 11GbZxQNO8uLBpt P46myZ2pba4xFk4 oyej8OIOrJSFBq0 QX1kXNZDSs6vM0F ec6hNmZ4u86fw3R DfXVVCDPE7V2bx9 LQGQBdBW1NaNjLp A6b0F534L69fPiY 5iUfSddKKilB4Y7 sO3U7J8dFLxsRND M02k5CFmpjgdbW3 JhapZ44Zki295MQ QG2auwXNRDOde4W quyecVa2aYk5NBm fT5rck9HavTsRXJ 3vJHSl4Oevg5ZEb uwdES7CLIQWSaGB PMl8p5VmvQ0pqkG 0l5ZWlNLY4wvnXv F. END KEYBASE SALTPACK SIGNED MESSAGE.

My keybase account, Xnopyt, is tied to my GitHub account which should verify that I am the account holder.

I have two unrevoked devices and a paper key.

The log ID from the computer which has access is 6cb5cd253d3f8bc46b2c251c .

Is there anything I can do to fix this? If not, can you reset the folder so I can reupload whatever I have back into it?
Thanks in advance.

**Comment by Tunas1337** [comment]
Update: `keybase rekey` says that `TLFs need rekeying: private/xnopyt`. I tried `keybase rekey paper` with my paper key but it did nothing.

**Comment by strib** [comment]
It looks like the device from which you sent the logs is stuck in "conflict mode", and KBFS keeps getting restarted for some reason when trying to resolve the conflict.  In the logs, there's no indication why the restarts are happening -- maybe the OS is doing it due to memory usage or something?

It also seems like maybe some important files were deleted out from under it at some point, from one of the keybase directories in your local home directory.  Not sure how that could have happened.

To fix the local device, you should do something like this:
* If you need to, try to copy out any data from the folder that you don't have saved anywhere else.
* Shut down Keybase and KBFS completely.
* Run this from a terminal:
```sh
mv $HOME/.local/share/keybase/kbfs_journal/v1/012030be231b98383911045e5dae0bb2ec91-f7457bf8da5988be $HOME/.local/share/keybase/kbfs_journal/v1/f7457bf8da5988be.bkp
```
* Then restart everything.  At that point, your local view of the folder will be whatever is on our servers.

Of course, since your phone cannot access the folder either, this might not be too helpful.  Can you please also send logs from your phone after you try to access the folder, and reference this issue or my username in the feedback description, and I'll take a look at what's going on there.

**Comment by Tunas1337** [comment]
@strib Done; you should be able to see it. I referenced both the issue number and your username, just to be sure :P

Also, I moved out the journal and the filesystem seems to be stable now (i.e. it doesn't take 30 seconds to open and doesn't error out).

**Comment by strib** [comment]
Great!  Now that it's fixed on your computer, does your phone work?  Looks to me like it might have been properly rekeyed now.

**Comment by Tunas1337** [comment]
After a bit of an initial wait, it now opens on the phone! Thanks a lot, I appreciate it!
I'll close this issue, but I have a bit of an unrelated question while I have you: if I hadn't logged onto Keybase for a very long time, and thus never claimed the Lumens from the airdrops, then I reset my account, is there some way for the spacedrop bot to let me back in? I never read its initial message and of course, the private key for the wallet is now completely new after the reset. I'm hoping that since I never claimed them I can still do so. Is that possible?
