### ISSUE TITLE
kbfs: first impressions; not a bug report, just some feedback

### ISSUE THREAD

**Issue by gklyne** [keybase/client#2397]
I've just started using kbfs on a new install of El Capitan, mainly as a way of saving private data as a backup and for access on other systems (I know you don't guarantee preservation, but it's not the only backup).  Behaviour has been flawless, no bugs or glitches.

As you warned, performance isn't sparkling, but for simple text notes is quite adequate.

I tried switching my Notational Velocity to use the keybase private file area, and for the time being it's not really quick enough - it tends to make the system freeze for several seconds at a time while typing.  I'll hold off using notational velocity routinely in this way, but as an additional route for backup/sharing across systems it seems just fine.

For me, the interface (file system) works really well, and the lack of a GUI is not an impediment.  If anything, a simple "login" app might smooth the way, but beyond that the file system interface seems to work a treat.

Mostly: great work!  I look forward too seeing how this evolves - I can see it being really useful.

my log id: e3ddcea0be5f2ca79ae0f51c

**Comment by cjb** [comment]
Thanks for the feedback!  We have plans for fixing both of these:

1) In the medium-term, we plan to use write caching so that the operating system returns success to your apps straight away and then syncs in the background, eliminating lag.  It'll take a while to get this right.

2) In the short-term, we're adding a GUI for login to the app.
