### ISSUE TITLE
can't login to another device

### ISSUE THREAD

**Issue by lolifamily** [keybase/client#24281]
![846139F2-0ED1-4DB2-83FF-391979FDA9CF](https://user-images.githubusercontent.com/47876607/88456453-7b837480-ceb0-11ea-8f7d-b7219496d5e3.png)

_Originally posted by @lolifamily in https://github.com/keybase/client/issues/24276#issuecomment-663846792_

**Comment by lolifamily** [comment]
@chrisnojima

**Comment by lolifamily** [comment]
my account id is `lolifamily`

**Comment by techmagus** [comment]
I'm experiencing this as well.

I reset my iPhone a few days ago and I've been trying to log back in. The error is the same as shown in the OP's screenshot.

* iPhone 6S
* iOS 13.6
* VPN: tried both on and off
* Internet: mobile connection (no wifi/wired internet)
* Revoked old device: yes same error; tried it before revoking, same error
* Tested on Android: Nope, I don't want to logout, I might not be able to log back in again.
* Tested on another iPhone: Nope, I only have one. But I was logged-in before I did a reset on the phone unit.

**Comment by techmagus** [comment]
Apologies, update: it finally worked.

On the 3rd or 4th reinstall (after I deleted iCloud data, virtually empty since I don't use it but just in case some old Keybase app was being restored automatically), it finally went through and I was able to approve the iPhone device.

Maybe the same process might work for you @lolifamily (some cache or something).

**Comment by big-banger** [comment]
I’m sorry maybe I missed this part but are you using C browser add-on or the standalone file?--11.08.2020, 02:03, "ᜌᜒᜃᜓ (Yuki|雪亮)" <notifications@github.com>:
Apologies, update: it finally worked.
On the 3rd or 4th reinstall (after I deleted iCloud data, virtually empty since I don't use it but just in case some old Keybase app was being restored automatically), it finally went through and I was able to approve the iPhone device.
Maybe the same process might work for you @lolifamily (some cache or something).
