### ISSUE TITLE
Failed to launch keybase

### ISSUE THREAD

**Issue by federicoon** [keybase/client#24410]
I installed keybase on Ubuntu 20.10 via snap.

```
$ keybase version
Client:  1.0.47
Service: 1.0.47

```
Tried _run_keybase_: command not found

I can't start the GUI, only command line client seem to exist.

my log id: fd11afed52c38586aaa8401c

**Comment by Rudi9719** [comment]
That version # is why it won't start. Keybase current is 5.X.X. Please follow the [installation instructions](https://keybase.io/docs/the_app/install_linux) on the keybase.io website rather than installing a [random snap](https://snapcraft.io/keybase) that was published by Leo Arias (elopio) as a Finance application back in 2018.

**Comment by federicoon** [comment]
Thank you. I stumbled on that snap version as I could not find any Ubuntu repo but only the .deb package to be installed manually.
Isn't there any repo to install the official Keybase version from? How are updates managed?

**Comment by Rudi9719** [comment]
Please do some reading before you install things to your system! That snap clearly isn't related to this Keybase, based on the points I mentioned above. Who knows what you installed!


As for not finding it in the repos, did you follow the installation instructions on Keybase's website? That should answer your question about repos, and updates :smile:

**Comment by federicoon** [comment]
I did some search and reading.. but missed that point about the repo and update. Thank you for your support, I'll delete that broken version and download the .deb package, then.
