### ISSUE TITLE
### Keybase proof


### ISSUE THREAD

**Issue by vostephens** [keybase/client#25247]
### Keybase proof

I hereby claim:

  * I am vostephens on github.
  * I am vostephens (https://keybase.io/vostephens) on keybase.
  * I have a public key ASC1ALFOJTFRGnlcuXSzmIcqrpXEdM50wlSAx4aGAThtGQo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "0120b500b14e2531511a795cb974b398872aae95c474ce74c25480c7868601386d190a",
      "host": "keybase.io",
      "kid": "0120b500b14e2531511a795cb974b398872aae95c474ce74c25480c7868601386d190a",
      "uid": "e1f41377ccc907c467ed35cd5e967819",
      "username": "vostephens"
    },
    "merkle_root": {
      "ctime": 1667721450,
      "hash": "f337fab0a3629d5b0d94df537e135c3773461a7ff6d1c7ead587454b0d5c956bafbdcb6faa6c2bd3b3c3f84cc21e8cefd1be4256098f71566b47c3c564dfd23f",
      "hash_meta": "7588d683c7d33b4a2aec6b6b2bd30be89fc780ee4dad37407d551f6dc3046d3a",
      "seqno": 23497203
    },
    "service": {
      "entropy": "X6OzerIbJNRYN/MtrJ0PdNT0",
      "name": "github",
      "username": "vostephens"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "6.0.1"
  },
  "ctime": 1667721495,
  "expire_in": 504576000,
  "prev": "5a4d9bebd6d861f1931cedf055aa416f2680bfe88bbe154934427e941a5dbfba",
  "seqno": 17,
  "tag": "signature"
}
```

with the key [ASC1ALFOJTFRGnlcuXSzmIcqrpXEdM50wlSAx4aGAThtGQo](https://keybase.io/vostephens), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgtQCxTiUxURp5XLl0s5iHKq6VxHTOdMJUgMeGhgE4bRkKp3BheWxvYWTESpcCEcQgWk2b69bYYfGTHO3wVapBbyaAv+iLvhVJNEJ+lBpdv7rEIEIUdJ1B/FuoVScT9XPUrmgL6q9nG1/SAU4zIkeEdcgEAgHCo3NpZ8RA+A2Rf+1hMnMbbeU87fqK8U7k//O5WK6fCnlYnvkCvkuEwCXZd50m7YKvREFqUdwvB8BJuHgTUqRhN1eMwAUVAKhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIC/4CBHxiza8wcSx3EPlOIMeR0twORqHbVSKHYKJVJRVo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/vostephens

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id vostephens
```

**Comment by chindraba-work** [comment]
@vostephens Still the wrong place, just a different version of the last one. Go to https://gist.github.com/vostephens and look for a small "+" next to your avatar in the top right corner. That will let you make a new gist - _in your own account_. Name it `keybase.md` and put all this in that. **Then** you will have proved that you own that account. Anyone can post here, even me, so placing that here proves nothing. Posting it someplace where only _you_ can post proves that you own the account. All the crypto stuff just proves that it's also linked to your Keybase account, because you have the keys to prove _that_.

**Comment by vostephens** [comment]
@chindraba-work , thanks a lot! You are a life saver 🙌

**Comment by chindraba-work** [comment]
Welcome.
Though it's  my inbox I'm saving.
