### ISSUE TITLE
kbfs not compatible with macOS Sonoma

### ISSUE THREAD

**Issue by rex4539** [keybase/client#25718]

**Comment by jms1voalte** [comment]
Here we go again ... 😏

**Comment by GwynethLlewelyn** [comment]
Yep. It's always the same story, over and over again :-)

**Comment by GwynethLlewelyn** [comment]
Oh, just for the record... let me paraphrase myself:

> This is very likely a duplicate issue of https://github.com/keybase/client/issues/24366.
>
>See also related issues https://github.com/keybase/client/pull/3969, https://github.com/keybase/client/issues/24376, https://github.com/keybase/client/issues/25379.
>
>This is a well-known issue (and reported multiple times), requiring the Keybase developers to fix their bundled Keybase FUSE component. macFUSE has no issues whatsoever with older and newer kernels; Keybase's own fork used to mirror macFUSE's code very closely, but, alas, someone at Keybase made a small mistake and deleted the support for older kernels (possibly around 2022/12/12 with request https://github.com/keybase/client/pull/25338).

@chrisnojima keeps publishing PRs non-stop, which means that at least he's keeping himself busy, so, who knows, maybe he'll take a look at this persistent issue _again_.

Also note that [macFUSE already has experimental support for Sonoma](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.5.0). One would think that all it takes is to keep KBFS in sync with their repo 😀 and at least _this_ issue would never pop up again (since macFUSE is kept so well up to date).

Wait, I forgot — macFUSE uses an external, proprietary component (free, but closed source), and that's one of the main reasons why the Keybase devs don't like it. It's a pity, though. At the very least, it _should_ be an option. Keybase _can_ be installed with the open-source-only ancient version of FUSE for macOS — sidestepping Keybase's own fork — but, alas, that ancient version is even more outdated.

Oh well. I guess we're stuck with this FUSE variant for ever and ever. Unless, of course, Apple steps in and includes direct support of FUSE in its own kernel (like Linux & [others](https://freebsdfoundation.org/blog/fuse-driver-update/) have been doing for a while now). But that is quite unlikely to happen...

**Comment by rex4539** [comment]
It has been released.

Type `keybase update check` in Terminal to get it.
