### ISSUE TITLE
Windows 10 - Insufficient System Resources

### ISSUE THREAD

**Issue by blandco** [keybase/client#2588]
When attempting to open K:\public\blandco\ using Windows Explorer I'm receiving the following error dialog:

----

`K:\public\blandco is not accessible.`
`Insufficient system resources exist to complete the requested service.`

----

![kbfs_insufficient_resources](https://cloud.githubusercontent.com/assets/17562808/14468286/9f9b2748-00a4-11e6-9f4a-c3456c4a0176.jpg)

----

Here's a snapshot of my system resources at the time of the error:

![kbfs_resources](https://cloud.githubusercontent.com/assets/17562808/14468324/bbc99d50-00a4-11e6-83bb-1d3e64a6ec6e.jpg)

my log id: f30e5961d00de4614d99241c

**Comment by strib** [comment]
The "insufficient resources" error is just the generic Windows error -- it just means the file system couldn't perform some operation, and that was the best way for us to represent the error to the operating system.  It doesn't mean anything about the actual resources.  Sorry that's so confusing.

In your case, there was a period of time when you were unable to connect to our backend servers, due to a certificate problem:

```
238 2016-04-11T16:54:54.449376 - [WARN kbfs connection.go:248] 0ee (CONN BlockServerRemote c6d7d4da) Connection: error dialing transport: x509.UnknownAuthorityError{cert:(*x509.Certificate)(0x138446c0), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}
...
1202 2016-04-12T11:38:27.549125 - [WARN kbfs connection.go:248] 21a (CONN BlockServerRemote 55b8fb90) Connection: error dialing transport: x509.UnknownAuthorityError{cert:(*x509.Certificate)(0x135cc6c0), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}
```

That's very strange.  Is there any chance you were using a proxy that attempted to man-in-the-middle TLS connections?  Our certificate is hard-coded into our software, so there's not really any chance for misconfiguration on your client, and as far as I know our servers haven't had any issues.

However, at the very end of your log, the connections seems to have succeeded:

```
1230 2016-04-12T11:38:50.507269 - [DEBU kbfs connection.go:271] 236 (CONN BlockServerRemote 55b8fb90) Connection: connected
```

And a directory listing succeeds.  Does it appear to be working now?

**Comment by blandco** [comment]
@strib Yes, I'm behind a Secure Web Gateway which performs SSL interception. And yes, everything appears to be working now. Thanks!

**Comment by strib** [comment]
Awesome, good to hear.  Let us know if you have any other issues.
