### ISSUE TITLE
Keybase: Possibly revoked data detected

### ISSUE THREAD

**Issue by foltzwerk** [keybase/client#2673]
The Keybase UI has been giving me the following notification:

Keybase: Possibly revoked data detected

So I sent the log. Hope this helps.

my log id: 322fecc382a8b6eec581411c

**Comment by strib** [comment]
Hi @foltzwerk: what's the history of your keybase account?  It looks like you completely reset your account a few days ago.  Had you written to your private KBFS directory before that?  If so, that data is now lost since you completely reset the account.  We don't have a good automatic procedure for that yet, but if you want us to reset that folder to be empty so you can use it again, we can do that.

We just need your explicit, signed permission.  So please run this command and post the output here if that's what you ant.  Please substitute the current date and time where indicated:

```
keybase sign -m "<DATE AND TIME>: Please reset folder /keybase/private/foltz because I reset the Keybase account foltz."
```

And if there are other folders that need a reset too (like your public folder?), add those too.

**Comment by foltzwerk** [comment]
Hi Jeremy,

Yes, I reset my keys and proofs the other day.


2016-04-23-095430 PDT: Please reset folder /keybase/private/foltz because I reset the Keybase account foltz.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsF67Phi pOHvASu3D9fNmQm zGhXbphJPqzhcCU git0eDe1vywqliS usYW9EI8ZSsTxlt A8HjWJKwzDI5r8m YtJDqpSYfwPgKYS 0yu9J6cWvQloqMB QRY3SKoAHN2eLrq NRZrxwh6wATIML6 4nJ7J2oIrfbB43X 7qarp6VWKmgRAU5 BImEUrPUPXG1Ut6 kdG0uJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVknOG6BJ G5NMT6eUU29DMCE vGbMBwQhzl4ui7s xO3sonCHN8AbPjp xeWoNfc3EzSiNfS flClptU5iXDWQle RpDwWScpOfR51u3 5yGcpEGq2DJWcpc XSWDd0RFR4PeOPT 7L2WEJ2ZtmFysxw ncfV62mZYGSQEjT ge. END KEYBASE SALTPACK SIGNED MESSAGE.


Thanks.

**Comment by strib** [comment]
Thanks @foltzwerk, your private folder should be reset now.  Please try it again.

**Comment by foltzwerk** [comment]
Hi Jeremy,

I missed this last part of your previous email: "And if there are other folders that need a reset too (like your public folder?), add those too.”

Adding them now. No rush. Thanks.


2016-04-23-125000 PDT: Please reset folder /keybase/public/foltz because I reset the Keybase account foltz.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsF67Phi pOHvASu3D9fNmQm zGhXbphJPqzhcCU git0eDe1vyWBPFJ 3OoricDUaeeAIGx d0MJhbL9q30TCzB UhK42jmgWWRr4rv tZuxwwoGv1yCnA9 cSeDOr2ckhllYFW qn1Ts15Ibl2PypC G4sVnuHSM7sbXEr Zi11ktO7H8LTDVV yHCqthcq4fuXblP d3lOSJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pvOPhsZfX5Ed4ve CeEarhKnK701g3g ag0ypHTvtugGs87 3SmbWfBw3JlRNQI lgpTfwiyJ0vzrIm 8N93KQ6HVX3xZXq oAgvYZjW1Skbr0K nrTEHqHDEOroKJr PibtdelYQhtJ5ps EXYfIHkQKegFLwr 74DytUY1U9CcdKB U. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok, your public folder is reset too.

**Comment by foltzwerk** [comment]
Hi Jeremy,

I made changes to the index.md in my public folder but the old version must be cached in the web server. https://foltz.keybase.pub <https://foltz.keybase.pub/>



I attached the index.md from my current /keybase/public/foltz directory so you can see the difference.

Is there something I’m doing wrong on my end?

Thanks,

David

**Comment by strib** [comment]
Because our reset protocol isn't automated yet, there are some loose ends.  Internally we track folders with a monotonically-increasing revision number, and when we reset your folder it dropped to 0, but keybase.pub probably thinks it is still at the old value (I think ~1800).

I just fixed it by restarting keybase.pub.

**Comment by foltzwerk** [comment]
Thank you.

I am enjoying Keybase. It rekindled my interest in using PGP for email. The last time I tried GPGmail on Mac OS, about a year ago, it would crash Mail.app every time. Now it works nearly perfectly. I know that Keybase and GPGTools aren’t related but for the first time I feel like Pretty Good Privacy is within reach of average users. Maybe Keybase can accellerate its adoption. Anyway, I think you’re working on cool stuff.

David
