### ISSUE TITLE
Github proof not working

### ISSUE THREAD

**Issue by apapatzis** [keybase/client#27499]
Hey guys,

i've been trying few times to get the github proof to work but the Windows-Client says its unreachable.

Here's this proof: https://keybase.io/apapatzis/sigchain#fbf7a430c76a3edb725aab9efcc7aec73d21ff99d9d923f21082f3e6130674080f

This gist was created as public from the go: https://gist.github.com/apapatzis/de29d727bb027d919567743ae278891c

Any help would be appreciated.

Kind regards

**Comment by grubbbethroach** [comment]
A couple of months ago, I faced a significant issue with a transaction I made from my Binance account to my Liberty wallet. Due to an error on my end, the transaction failed, and I was unable to resolve the problem through the support team of my wallet provider. Despite numerous attempts to fix the situation, it seemed as though my funds might be permanently lost, and I was growing increasingly concerned. In my quest for a solution, I discovered Cyber Constable Intelligence, a company renowned for its expertise in resolving issues related to failed or stuck cryptocurrency transactions. I decided to reach out to them for assistance, and from my very first interaction with their team, I was struck by their professionalism and understanding. Cyber Constable Intelligence quickly grasped the nature of my problem and reassured me that it was solvable. Their clear and knowledgeable explanations were a welcome relief amid my mounting frustration. They carefully outlined the steps that would be taken to address the issue and provided me with detailed instructions to keep me informed throughout the process. The support I received from Cyber Constable Intelligence was nothing short of exceptional. They maintained open lines of communication, offering online support whenever I had questions or needed updates. Their approach was not only professional but also incredibly courteous, which made a stressful situation far more manageable. It was clear that they were genuinely committed to resolving my issue and recovering my funds. Throughout the process, the team demonstrated a high level of expertise and dedication. Their meticulous attention to detail and thorough understanding of the technical aspects of cryptocurrency transactions were crucial in successfully resolving the problem. Thanks to their efforts, the transaction was completed, and my funds were safely recovered. I am immensely grateful to Cyber Constable Intelligence for their outstanding support. Their ability to handle complex issues with such efficiency and professionalism exceeded my expectations. It is rare to find a service that combines exceptional technical skills with excellent customer service, but Cyber Constable Intelligence achieved this balance perfectly. I wholeheartedly recommend Cyber Constable Intelligence  to anyone facing similar challenges with cryptocurrency transactions. Their expertise and commitment to resolving issues are unparalleled, and they provided me with invaluable assistance during a difficult time. Thanks to their help, I am now able to proceed with my investments and transactions with renewed confidence. Thank you so much Cyber Constable Intelligence, for your exceptional support and for helping me recover my money.

CYBER CONSTABLE INTELLIGENCE INFO:
Website: w w  w. cyber constable intelligence....  com
What Sapp Info: 1. (2. 5. 2. ) 3. 7. 8. 7. 6. 1. 1.
Email Info : support (@) cyber constable intelligence... com
Best Regard,
Beth Roach Grubb.
