### ISSUE TITLE
No access to my public folder (kbfs)

### ISSUE THREAD

**Issue by DarthWed** [keybase/client#2795]
Getting error that some revoked data detected when writing to my public folder.

my log id: eba86bb5fddcd49cf73b8f1c

**Comment by strib** [comment]
@DarthWed it appears you reset your Keybase account today, which revokes all of your previous keys, making it impossible to read the old data since it was signed by now-bad keys.

We are working on something that will automatically fix your folders for this case, but it's not done yet.  In the meantime, we have to manually clear out your old folders, to make way for fresh ones with your new keys.  (e.g. #2780.)

But we need your signed, public permission to reset those folders.  If you want us to do that, please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/wed and /keybase/public/wed because I reset my Keybase account."
```

and post the output here. Thanks!

**Comment by DarthWed** [comment]
Hey strib.

05/10/2016 - 08:45 AM CEST: Please completely reset folders /keybase/private/wed and /keybase/public/wed because I reset my Keybase account.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs41bK3H gDDr6tn3UR2BxSK 0jaccCKrxN0JGaX lnkNEkbjlm2P76J LXgO2fyRD6JbLrK BE0zR576sLtCr9j RNp8OXmroYlKITA vNhR8586PvYao14 wz9p6ulToBlJlE9 kI1zPCCSTDFbTIv ZyyYPITRMNP8ri1 C4ikaUxTDM1JTQ0 kCFZViHrnZ68fDZ G7VApGREKYp5uyL CykIsOSFFCCbySj r4KuRQjifQj5Scl LzgNo2IVsOmlRAr AlAZY4A99DaJm8P ZlUR5xyb2vzs6fW tO3sonCHNAwL9ZK jD6NPQc6Qbkyy1d xnH0mFu8a5caLVR XJ2EcUlWgsOGS38 r1nPtgm2PabTe13 WYmoQB6pbdcO1dW Dr61YEb1onzeSRQ xOHyZ6FolYBUPOn EezICGd3VYiLdQH uHkrAaq04ahFRcD AED9acJ2WsBYLFg . END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you very much! :-)

**Comment by strib** [comment]
@DarthWed these are now reset.  Sorry for the delay!  Give those folders a try again and please close this issue if they work now.

**Comment by DarthWed** [comment]
Working great, thank you very much!
