### ISSUE TITLE
Constant KBFS notification for nonexisting user

### ISSUE THREAD

**Issue by qntmpkts** [keybase/client#2869]
![kbfs_usernotfound](https://cloud.githubusercontent.com/assets/19355612/15489951/d3c2bc8e-2129-11e6-9483-39f633cc4782.jpg)

If a user's name is misspelled while, for instance, cd'ing to a public directory, since they do not exist, a notification appears and re-appears. There is no way to remove them from favorites to prevent the notification. Example of notification attached (intentionally misspelled).

**Comment by strib** [comment]
Hi @qntmpkts.  The notification happens only when you (or something on your computer) tries to access the directory.  It should not be happening constantly for no reason.  It's supposed to be informative.  Just having the name in your favorites doesn't cause a notification.  In fact, a folder of a non-existent keybase user shouldn't even be able to get into your favorites in the first place.

If you do have a bad favorite (under `/keybase/public` for example), you can remove it with `rmdir /keybase/public/usernaem`.

If you'd like us to look into it more, you can do a `keybase log send` to give us your logs.  Otherwise, I'm not sure what the actual problem is.

**Comment by qntmpkts** [comment]
It would seem this was a result of a misconfiguration that was indeed attempting to access the misnamed file. Fixing that caused the notification to go away.
