### ISSUE TITLE
Too many processes spawned

### ISSUE THREAD

**Issue by Walkersneps** [keybase/client#3057]
On system boot keybase spawns 6 processes:
* 2x `keybase` (one has a capital K)
* 3x `Keybase Helper`
* 1x `keybase.Helper`

![Screenshot](https://cloud.githubusercontent.com/assets/7949250/15978847/f939069a-2f60-11e6-8e0a-3ba34f5f266b.png)

My log id: db4af68d16923c5c0849a71c

**Comment by gabriel** [comment]
We use [Electron](http://electron.atom.io/) for the UI and it is a little heavier than a native UI app would be. The current process breakdown is:

- `Keybase` and `Keybase Helper` (x3) are from Electron. These are heaviest, since they are UI related.
- The `keybase.Helper` is the [privileged helper tool](https://developer.apple.com/library/mac/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html) which takes care of our privileged tasks.
- The `keybase` process is the keybase service which runs in the background (the UI communicates with this process).

Memory usage and CPU are something we are aware of and are thinking about. Currently we're not looking to optimize these types of things yet but down the road we will.

Thanks for your feedback.

**Comment by gabriel** [comment]
A little more details on the privileged helper tool for those who are interested. This is the appropriate and recommended way to perform privileged tasks in OS X (see [Elevating Privileges Safely](https://developer.apple.com/library/mac/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html) for more info.

The source for the privileged helper tool is [here](https://github.com/keybase/client/blob/master/osx/Helper/KBHelper.m). The tasks it performs are:
- Installing or upgrading Fuse (kext)
- Installing the command line symlink or adding to path
- Creating the root `/keybase` folder

Only the Keybase signed apps (like the bundled KeybaseInstaller.app) is authorized to perform these tasks. This authorization is done by the OS itself. :)

**Comment by Walkersneps** [comment]
Good to know. Thanks for the comprehensive explanation :)
