### ISSUE TITLE
"Config is not a keybase user"

### ISSUE THREAD

**Issue by martindevans** [keybase/client#3158]
I've just installed the new windows client for keybase (i.e. it's clean, I haven't fiddled with any settings or created any folders). When I'm clicking around the keybase FS directories I get a notification pop up:

![untitled](https://cloud.githubusercontent.com/assets/177519/16252457/4620aabc-3826-11e6-81ff-f190c732997b.png)

So there are three issues here:

Firstly this message is unclear, I *guess* this is saying it can't find a user named "config"?

Secondly it pops up whenever I open *any* directory in my KBFS (e.g. I just navigated to K:/public/martindevans and got that popup). It probably shouldn't be quite so spammy (if it's a problem with one specific share in my KBFS maybe just put an alert in the Keybase client app).

Thirdly, since this is a clean install the only directories in my KBFS are the autogenerated ones (for myself) and ones which other people have created with me in (and if they did that, they're obviously a user which exists!), so the message just seems to be plain wrong. Here's a complete directory listing of my KBFS:

```
PS K:\> ls -R

    Directory: K:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       1754-08-30     23:43                private
d-----       1754-08-30     23:43                public

    Directory: K:\private

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       1754-08-30     23:43                martindevans
d-----       1754-08-30     23:43                martindevans,quantumplation

    Directory: K:\private\martindevans,quantumplation

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------       2016-06-22     02:56             21 hi

    Directory: K:\public

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       1754-08-30     23:43                martindevans
```

**Comment by strib** [comment]
Hi @martindevans, those notifications are generated by some program on your device that is trying to lookup the name "config" under `K:\private\` or `K:\keybase\public`. We show you those notifications to help teach you how to use Keybase, but we understand that when it's some other program on your computer, it can be confusing when you see popups for no reason. Unfortunately, we can't tell the difference between you doing something and your device doing it in the background.

Since you said it happens in any directory, it is likely something in your shell environment that tries to look up something in every component of your working directory, and so it ends up looking it up in `K:\private` or `K:\public`, causing the notification.  git shells do something similar with ".git", and we whitelist that name so it doesn't show a notification.

We can potentially do the same thing for "config", but I'd like to know what program is causing the problem first.  Do you know what program could be doing it?

**Comment by martindevans** [comment]
That makes sense, in fact I had a very similar problem when I was building my own dokan FS!

Can I suggest you can the message to highlight the name more clearly, perhaps just:

> "config" is not a keybase user

Your guess about shell extensions appears to be right. I did some trawling through procmon and found that explorer.exe is repeatedly trying to open the file 'config':

```
Operation: CreateFile
Result: NAME NOT FOUND
Path: K:\private\config
Desired Access:	Read Attributes
Disposition:	Open
Options:	Open Reparse Point
Attributes:	n/a
ShareMode:	Read, Write, Delete
AllocationSize:	n/a
```

Unfortunately since shell extensions seems to run as part of the explorer.exe process I can't determine exactly which shell extension is causing this. Here's a list of shell extensions I have installed, if you're inclined to install them and test which one is causing problems:

 - 7-Zip
 - Notepad++
 - EPP (windows defender shell extension, I assume this is a default part of all windows installs)
 - TortoiseGit
 - TortoiseHg
 - WinRAR
 - NvCplDesktopContext (This appears to be an nvidia thing, I guess it comes with my graphics drivers)
 - PDF Shell Extension

Of these I would *guess* tortoiseHg is the most likely to be causing problems, since it's by far the most complex extension.

**Comment by aschmahmann** [comment]
+1 From me, after poking around with ShellExView (http://www.nirsoft.net/utils/shexview.html) I'm pretty sure 7-zip is the culprit here. There aren't a ton of common shell extensions that could cause these problems, but if it continues to come up then maybe allow for local whitelists and note that people should submit their whitelists to the keybase team.

If you're thinking about adding shell extensions to the KBFS system and want to talk to someone who has spent some time dealing with these problems feel free to reach out.

**Comment by strib** [comment]
Notifications for "Config" will now be suppressed, starting in the next release.

**Comment by martindevans** [comment]
Presumably the release which *just* popped up on my computer as I clicked that thumbs up :D
