### ISSUE TITLE
Linux client mounts /keybase as root, but every file under it is also owned by root

### ISSUE THREAD

**Issue by iandouglas** [keybase/client#3262]
It seems maybe you don't allow setuid bits on the files, but it'd be more reassuring if you could set the owner/group of any files under private or public folders to be that of the logged in and authenticated user, maybe? Feels like a possible security vector to be aware of, perhaps?

**Comment by strib** [comment]
Thanks for the feedback!  Agreed it probably makes sense to show the files as owned by the local user account that mounted the file system (we can't show the authenticated Keybase user, since that doesn't necessarily correspond to a proper account on the computer).

However, I'm not aware of any security issues with not doing so.  The FUSE mountpoint won't let anyone besides the user look into the mount (try `sudo ls /keybase/`), and I don't know how else the owner/group of a file could be used to escalate privilege.  But if I'm missing something, please let me know and we can prioritize this.

**Comment by strib** [comment]
Files under `/keybase` are now owned by the user who ran `run_keybase`.
