### ISSUE TITLE
Keybase Not Accessible

### ISSUE THREAD

**Issue by lherlitz** [keybase/client#3309]
Keybase GUI Version: 1.0.16-20160630135211+c643773

log 1: e3775715bf603b2e83d4f81c
log 2: 232d3e4dc48e30c85ff1641c

Neither of my computers can access my keybase folders/files.  One is on macOS 10.12 beta the other is on 10.11.4 El Capitan

**Comment by strib** [comment]
We have done no work to support the macOS beta, so I wouldn't be surprised if it doesn't work there.

On El Cap:

```
mount helper error: mount_kbfuse: failed to mount /keybase@/dev/kbfuse0: Operation not permitted
```

Maybe you're acting as a user without admin privileges, or you've switched users from the one who originally installed keybase?

**Comment by lherlitz** [comment]
I don't think that was the case, but I'll check.

**Comment by ringods** [comment]
@strib I'm in a similar situation: the admin user was used to install Keybase using `brew cask install keybase`, while I run it from my non-admin account. Why doesn't this work?

**Comment by strib** [comment]
I have no clue about the `brew` stuff, sorry.  @gabriel?

**Comment by ringods** [comment]
@strib @gabriel I don't think Homebrew is the culprit here. It just automates the "drag-and-drop" to the Applications folder but in a command line command. I'm using this with other DMG based apps before without any problem.

Having searched further in the issue list, I understand that Keybase doesn't function well from a user account which does not have admin rights. With Keybase going over security, I find it hard to believe that you would require a user account with admin permissions.

**Comment by gabriel** [comment]
Keybase can now update from non-admin accounts (even from brew). This is an old issue, and should be resolved.
