### ISSUE TITLE
Can't open /keybase/public/USER after reset identity

### ISSUE THREAD

**Issue by lingz** [keybase/client#3357]
Not sure if this is intended or not, but I reset my identity and now my filesystem is not able to read /keybase/public/MY_USER

An ls operation returns:
```
$ ls
ls: cannot open directory .: Input/output error
```

Don't mind resetting the folder, but I think it would need to be done manually?

my log id: ca0d8198492a6f3465ce701c

**Comment by strib** [comment]
Yes, we're working on an automatic way but it's not ready yet.  We can reset it manually (do you want your private one reset too?), but we need your signed, public permission. If you want us to do that, please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/lingz and /keybase/public/lingz because I reset my Keybase account."
```

and post the output here. Thanks!

**Comment by lingz** [comment]
The output is below. Yeah resetting all would be good. Thanks for your help.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsD2BUKj DAZrR2FM7TwP975 71AXBkAT38FHQqI unnyqpgz8muzUkr YF1SNIByK3yfjBc QA0AXxYWfVvzS2Q jeUvyPKS9VCBXms VDNnWYKEWCwRRXS xW8wubROaG0EhbJ ueflzeFnRXYKDHP FMW6rsObUb46iZb 9ff7flo1oSVbmvQ aSQwUZB8w1coAL1 YJNgrN6jMxIKqi9 FKo85HVH4yarriZ XrGVDFlCE2lrCNg KRhSmbWfBwEksAP 1mMwCIjN4H511Yg u2cN60RZaSu959e fBFSNENXRjFCASG TrTuvp2PdEIZbFe Zg6oNQlmtqxBY97 enRhaio1HeTU28H e1pPo3Cy82c4G2P ACRgzoYQqSykMR2 mlMgzMFtbTwubUA TzFQLVWosmecJ28 KQDTdX8DjK4Fvey PS9tAJZMG5JZfop uqZwbnE2KW. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok I reset your public folder.  It doesn't look like you have a single-user private folder created yet, so `/keybase/private/lingz` should work ok too without me doing anything.

I notices you have a shared private folder with another user (not saying the name here for privacy reasons), and that one was unreadable now as well after the account reset. I went ahead and reset that one too, since it looked like it didn't contain any data yet.

Please check it out, and close this issue if everything looks good.

**Comment by lingz** [comment]
Awesome can confirm it worked. thanks a lot for the fast support!
