### ISSUE TITLE
Repeatedly being told "node_modules is not a keybase user"

### ISSUE THREAD

**Issue by brianm** [keybase/client#3455]
The FS is slick, but I keep getting desktop notifications that node_modules is not a user :-(

my log id: 7307f891bec0f8275d27391c

**Comment by strib** [comment]
These notifications are meant to help people who type the wrong thing in `/keybase` and `/keybase/{private,public}` figure out how to use KBFS, but I know it can be confusing when some background task patrolling your file system causes the popup.

You must have something in your shell environment that looks up `node_modules` on every component of your current working directory?  Do you know what that could be?  It might indicate something dangerous, since depending on what it does with those directories it finds, someone might be able to trick you into running some code you don't want to run.

**Comment by brianm** [comment]
Ah, yep, I found the problem, shell was in a "working on a node project" state. Grr npm stuff.

**Comment by strib** [comment]
keybase/kbfs#155 suppresses this notification, starting in the next release.
