### ISSUE TITLE
Cannot delete file (Input / Out Error) - Ubuntu Linux

### ISSUE THREAD

**Issue by borisg1995** [keybase/client#3473]
Cannot delete file in public directory. 

Can rename file without issue (strangely) - but cannot delete from UI or command line (as root or logged in user).

File shows on keybase.pub file index -but returns a 404 error. Opening the file locally results in an I/O error.

File name in question: 'fubar' 

my log id: 847bc00726698b79e99e4b1c

**Comment by strib** [comment]
Hi @borisg1995 -- we found and fixed some bugs recently (in keybase/kbfs#144 and keybase/kbfs#150) that could have resulted in this situation (being unable to read a supposedly live file).  And in the KBFS version you're running, once it's unreadable, it's also undeletable.

This last thing is fixed in the newest KBFS release (`1.0.2-20160714160113+6e84d03`), so if you upgrade you should be able to delete the follow.  If that works, please close this out.  Thanks and sorry for the inconvenience.

**Comment by borisg1995** [comment]
Many thanks for your quick reply @strib 

I've upgrade the Keybass app via apt-get and this has resolve the issue and allowed me to delete the file. In also correctly no longer appears in my .pub index.

Many thanks for your help and keep up the good work!

0x69 0x610x6d 0x690x6e0x760x690x6e0x630x690x620x6c0x65

Boris G.
