### ISSUE TITLE
zsh autocompletion and kbfs 

### ISSUE THREAD

**Issue by Faedrivin** [keybase/client#3503]
When cd'ing into /keybase/public for just looking at the folders and trying an ls there it shows up multiple (instead of one) directories: `sh`, `sho`, `shoe`, `shoeffner`. I assume there's a problem with zsh's autocompletion feature. 
I also get error messages that "rmd" was no valid user when trying to delete those folders via `rmdir`. When running the normal shell sh it seems to work (also when trying to run failed commands by rerunning them without retyping them).
Similar issues also appear when I try to run keybase commands: "keyb" is not a valid user, "k" is not a keybase directory and so on and so forth.

These issues truly break kbfs for now for me, since I never use the finder and even `open /keybase/public/shoeffner` with tab completion motivates keybase to happily create the `sh, sho, shoe` directories. Also I don't want to switch shells.

my log id: 9ae6c28263a5156ee35d7a1c

**Comment by strib** [comment]
Sigh, sorry about this.  This is due to a relatively recent change, to try to make it so that `mkdir /keybase/public/foo` added `foo` to your favorites list.  But the only way we found how to do that was to make the `lookup` system call add whatever you're looking up to your favorites list, which interacts badly with autocomplete.

@songgao, @malgorithms -- we may need to back this out, and just give up on `mkdir` for now.

@Faedrivin -- I know it doesn't solve your problem, but you can remove these partial favorites with `rmdir`.  However, I would be worried about that issue with keybase commands.  It might indicate that `.` is in your $PATH, which would make it easy for someone to trick you into executing arbitrary code, i.e. by putting an `ls` executable in their public directory.

**Comment by Faedrivin** [comment]
@strib Thanks for the comment. I double checked my path and there is definitely no `.` in it:

    echo $PATH
    /usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

And it's tough to remove the partial directories via rmdir due to the error messages popping up.

I now disabled everything in my .zshrc to check if some of my plugins or extensions causes this.
It turns out the culprit for actually creating the directories is the [syntax-highlighting plugin](https://github.com/zsh-users/zsh-syntax-highlighting) which I enable with: `source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`.
None of my plugins (git brew gem **compleat** mvn pip python vagrant vi-mode wd virtualenvwrapper) or any other auto completion features seemed to cause this:

    zstyle ':completion:*:(rm|kill|diff):*' ignore-line yes
    autoload -Uz compinit bashcompinit
    compinit
    bashcompinit
    source /usr/local/share/x86_64-osx-ghc-8.0.1/compleat-1.0/compleat_setup

So maybe it's not worth removing the feature, as I assume only a small number of people uses zsh-syntax-highlighting - it looks like auto completion itself works fine.

I hope this helps you a little bit to track down the problem. I will for now just disable syntax highlighting if I want to work with keybase. And I might need to check whether it somehow implicitly adds `.` to my $PATH, thanks for the heads up on that.

**Comment by awmottaz** [comment]
@shoeffner it's been a few years, have you found a good workaround for this? I'm running into this same issue, also using the zsh-syntax-highlighting plugin.

**Comment by shoeffner** [comment]
Sorry, I have not looked deeper into this. In fact, I am not using kbfs at
all at the moment.
