### ISSUE TITLE
Uploading a 1gb folder

### ISSUE THREAD

**Issue by dangidank** [keybase/client#3574]
Tried to upload a 1gb folder with a lot of different files, got a timeout because it took to long.

my log id: 8dbbcdc023dc9ece36bdb21c

**Comment by maxtaco** [comment]
@strib he/she is running "1.0.2-20160715110059+1fb05f3"

**Comment by strib** [comment]
Looks like you got into "conflict resolution" mode (likely due to known issues we've been debugging internally this week), and I'm guessing that caused excess pressure on your network connection to our servers in a way we didn't respond to fast enough.  Unfortunately the log that got uploaded had recently been rotated, so I can't see the whole history of what happened, but based on other things we've seen recently I have a decent guess for what happened.

The good news is that it looks like conflict resolution completed eventually, so things should hopefully be working again!

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
