### ISSUE TITLE
Tray icon, app menu not working on Windows 10

### ISSUE THREAD

**Issue by soderluk** [keybase/client#3592]
Using Keybase GUI Version: 1.0.16-20160713110836+a1c00b3 on Windows 10:
Steps to reproduce:
- Open up the tray by clicking on the keybase icon
- Click "New private folder" button, OR "Open public folder"  button
- Nothing happens
- The menu in the top-left corner doesn't open anymore

I need to kill the tray process and start the app again to get the menu working. Other than that the whole keybase GUI on Windows doesn't really work.

**Comment by soderluk** [comment]
Same issue as #3549

**Comment by iFreilicht** [comment]
This seems to have been fixed in version 1.0.16-20160726182036+0c2a52a, update was rolled out today. All clickable UI elements seem to now work as intended. Please check whether this fixes it for you and close the issue if that's the case.

**Comment by soderluk** [comment]
Thanks for the update! Checked, and at least the menu now seems to work again, even when clicking around the tray window.
No folders are opening though, when clicking on the "Open public folder"-button.

**Comment by iFreilicht** [comment]
That's not what "Open public folder" does. You should see that if you press that button, a text box appears in its place where you can input a comma-separated list of users that have writing access to that folder. It's named misleadingly, I'll give you that. "New private folder" and "Open public folder" are doing the exact same thing, one for private, one for public folders.

To open your own public folder, click on the entry right below that button with your keybase username and profile picture on it. That didn't work either previously, but was fixed in the update.

**Comment by soderluk** [comment]
Ah, OK, thanks for the clarification.

I had to restart the app to get the open folder to work. Seems to work now, so I'll close this ticket.

Keep up the great work!
