### ISSUE TITLE
Keybase doesn't seem to work after restart from killing via task manager

### ISSUE THREAD

**Issue by sohjsolwin** [keybase/client#3642]
Keybase GUI Version: 1.0.16-20160713110836+a1c00b3
Windows 10

I just installed the keybase app, went through setup and everything seemed fine. Tried opening powershell to do things in the public/private folders, navigated to K:/private/sohjsolwin and tried running just 'keybase'. Seemed to freeze and become unresponsive. I waited for a while then killed all keybase related things through the task manager. Upon restarting the keybase app, I was asked to log in again, but the app seems to be stuck at the "is this a valid username" screen. The button is just spinning with no change in the last 10 minutes. 
![image](https://cloud.githubusercontent.com/assets/1836390/17215511/14efbab8-54ab-11e6-9372-1364a9a2dcc2.png)

**Comment by juanminm** [comment]
If you killed everything Keybase related, then you most likely killed the service as well. When you install Keybase, you get two start up entries, one for the services (which calls the service itself, dokany and other process) and the GUI. To start the service again, you have to type `keybase ctl watchdog2` in the Keybase shell. The problem is, if you kill the shell, you kill the service. So to make it not kill itself, you have to tell "runquiet" to start up keybase by typing `runquiet keybase ctl watchdog2`.

You can find out about the correct command if you go to the Task Manager > Start tab, then add the column "Command Line" and search for both runquiet.exe entries. Here's the example:
![captura](https://cloud.githubusercontent.com/assets/14891772/17215999/2e0e1ccc-54df-11e6-8ea5-3b95df4421a7.PNG)

**Comment by zanderz** [comment]
If you still have trouble, please issue `keybase log send` if able and post the resulting log id here. Thanks!

**Comment by sohjsolwin** [comment]
@juanminm interesting. Thanks for the information. I'll keep this in mind for the future. I had to restart due to updates anyway and everything seems to have restarted correctly after the reboot (which is expected, but worth mentioning anyway).
