### ISSUE TITLE
Permission denied when accessing kbfs private folder

### ISSUE THREAD

**Issue by rmartinho** [keybase/client#3682]
I'm just trying to run `ls` in /keybase/private/rmf (my folder) and I get a permission denied message.

my log id: 13b81fe4f0040d60f2ee451c

The same occurs when trying to create a file on my public folder (`ls` there works). (log: e08d87732ae50c0fe914c31c)

I have another machine where I can use kbfs just fine.

**Comment by strib** [comment]
@aalness: the server was complaining about "token expired" for this device (see debug tag `xkFs3Rak7LcjT3qZmSyCwg`).  Any ideas?

**Comment by strib** [comment]
Hi @rmartinho.  We looked into this a bit on our end -- looks like you uncovered a race in our system where our servers didn't yet know about your newly-provisioned device, and locked you out for a while.  (I think everything should be working now.)

We'll open an internal issue about this, but if you encounter it again, maybe try restarting KBFS or bouncing your internet connection.  Sorry for the inconvenience.

**Comment by rmartinho** [comment]
It works now, thanks!

**Comment by szaffarano** [comment]
Hi, I have the same problem. When I try to enter or doing a ls in /keybase/private/szaffarano I get a "permission denied" message:

```
$ ls -l /keybase/private/szaffarano
ls: cannot open directory '/keybase/private/szaffarano': Permission denied
```

My log id is "c48bdb03c07a50da39764d1c".  Thank you

**Comment by strib** [comment]
@szaffarano: Looks like you're in a very different situation.  I'm guessing you've revoked all your devices and added new ones since the last time you accessed your folder?  If the new devices didn't overlap i time with the old devices, you've lost access to all the data and it's unrecoverable.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/szaffarano because all the devices that have access have been revoked."
```

and post the results here.

**Comment by szaffarano** [comment]
@strib Yes, you are right! I've revoked all my devices and added new ones.  Here it's the result of run the command you said me:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkPrlIXr mTzcTNuhGDezXcm TG3GaRhOy7sXTBZ KFCB98H3jegwwje wM827sHnVkG3bzQ 1zIFUlwS0SfM3RG S8uhTtYUn4uGxA7 HLQtb5Rauqyu2o4 L9ZlxoaUYqihaUn HKEQPrD0EXldMsW vce6C5RY6WGD0pz VCiH9yoGKOS961r 4O2jvcPZmlGxYL6 ooKFUJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVknYAH3x BZTuxUjFc1ZmDvS IXlF8kRCXtAeTni SNo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrF9 t1GFjoZG7lhFRm. END KEYBASE SALTPACK SIGNED MESSAGE.
```

Thank you!

**Comment by strib** [comment]
@szaffarano: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by szaffarano** [comment]
@strib Thank you! It's working fine now

**Comment by smileisak** [comment]
`keybase sign -m "Tue Jan  1 16:44:03 CET 2019: Please reset folder /keybase/private/smileisak because all the devices that have access have been revoked because i am a moron."`

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkPByaWh tIVbk4lgNjuz2OM Q5hT4FldrBlIsGF zNLy9PczZ3Gvj39 wSuGn69a037rm8U qNzrFA0UXlOzxhT XRt5pmzNqCYJsh2 EYYoS5pkg68Adn1 uSFihQhyphqHV5Z awem4yZJghuMT0l 6jmcfxRreWg1fQ3 8CnSM3vQLViptvP zqkWWfFxdyzcXxh V2HkTJwpE12weoB 4fb2tOy66FBrUiR y9EtHbBfMZNWBPn VzFNKP0Ss2D3ic4 AgfQZ90walgJDPP tkIgmX5kaAuuFNM fPi2KPMPiffaCQP 8ILux5gPyRAfPxJ 8iVcpfWYYGU86yO kcEVTqnoSWzGjxz sP8ZwRqAGMAXrtM teBt6iI5aYWf0fn rBofw8U. END KEYBASE SALTPACK SIGNED MESSAGE.
