### ISSUE TITLE
Cannot exclude private directory from Spotlight indexing on Mac OS

### ISSUE THREAD

**Issue by JoeNyland** [keybase/client#3870]
I'm trying to add `/keybase/private` to the excluded list of directories for Spotlight so that my private and confidential files are not indexed by Spotlight.

On adding the private directory to this list in System Preferences, I get the following error:

![screen shot 2016-08-12 at 14 17 09](https://cloud.githubusercontent.com/assets/7666402/17623392/b51986ac-6097-11e6-95e4-3bb9515aaf9b.png)

**Comment by cjb** [comment]
Thanks for the report.  Could you confirm that Spotlight was already indexing your Keybase mount?  I had the impression it didn't, but could easily be mistaken.

CC @gabriel

**Comment by MasterRoot24** [comment]
I can't confirm that, no. But part of Keybase is about privacy, so I would naturally want to exclude my files contained in KBFS from Spotlight and I can't do that.

Regardless of whether it's technically impossible for Spotlight to index KBFS, Finder/System Preferences shouldn't error when adding the KBFS mount to the exclude list. I can add other files or directories to the exclude list, just not KBFS.

**Comment by strib** [comment]
I believe spotlight can't see your files because they are not accessible by root, but I haven't confirmed that 100%.  Likely that's the same reason for that error -- it doesn't even have permission to look inside the directory.

@MasterRoot24 if you try that action again and do a `keybase log send` and let us know the ID, I can try to confirm.

**Comment by MasterRoot24** [comment]
@strib `8399d4938c6c8195344c271c`

**Comment by gabriel** [comment]
We do exclude the /keybase directory when we create it:
https://github.com/keybase/client/blob/master/osx/Helper/KBHelper.m#L123

I think you can check the status of spotlight on a volume, but for me says unknown, maybe because it is a fuse mount. 

```
mdutil /keybase -s
/keybase:
	Error: unknown indexing state.
```

You could try to see if spotlight is returning any results for searching for files:
```
mdfind -name somefileinprivate
```

I really doubt Spotlight will index /keybase even without the exclude but I'd have to double check that.

**Comment by MasterRoot24** [comment]
Thanks @gabriel, I'm happy to believe you that `/keybase` isn't indexed.

The view point I was coming from was: "What would I think if I was a new user who tried to do what I did?"

I feel that a new user who is inexperienced in Keybase, FUSE and Mac OS filesystem mounting would think that something has gone wrong when they see such an error message. After all, I have an understanding of the above technologies, but I still didn't have enough to decipher the message and had to come here to establish if Spotlight was able to index KBFS.

I feel that at some point in the future (low priority) it would be worth trying to get KBFS to play nice with the indexing settings for Spotlight, so that users can exclude or allow their KBFS to be indexed by Spotlight.

**Comment by gabriel** [comment]
Yeah it's something we'll definitely investigate. Thanks!

**Comment by MasterRoot24** [comment]
FYI: This is what's displayed in macOS Sierra:

<img width="698" alt="screen shot 2016-11-12 at 5 28 05 pm" src="https://cloud.githubusercontent.com/assets/7666402/20239664/765a24c2-a8fd-11e6-814f-8275f08abc9a.png">

😕

**Comment by gabriel** [comment]
We don't currently support spotlight indexing, since it's a remote volume (and also for security reasons).

**Comment by MasterRoot24** [comment]
I know, but the error displayed is just nonsense to users that don't understand the way that KBFS is mounted/installed.

I was providing the screen shot to keep this issue up to date with the current situation.

**Comment by strib** [comment]
It's likely because we don't allow `root` to access your files, and a lot of macOS programs just can't deal with that.  (The error message isn't coming directly from us.)

**Comment by gabriel** [comment]
Thanks for reporting the funky error message. Yeah thats coming from the OS but good to know about it, maybe there is a workaround to get it to show something sane.

**Comment by MasterRoot24** [comment]
@gabriel No worries. I'm not a macOS dev, so I don't know of any workarounds to get a meaningful message to be displayed there, sorry.

I understand why the message would be displayed, if root can't even access the contents of `/keybase`, but I'm a dev so I have an understanding of the way this works.

My concern is that privacy conscious users may want to explicitly (attempt) to ignore their private files from indexing by Spotlight and would stumble upon this error and assume that something was broken.

It's an edge case, I admit. But it's nice to at least get these edge cases flagged up. Feel free to close this if you think that's best, but I just wanted to let you know.

**Comment by JoeNyland** [comment]
Closing this as I no longer use Keybase and given how old this is it's likely no longer an issue.
