### ISSUE TITLE
error running keybase status

### ISSUE THREAD

**Issue by the4ndy** [keybase/client#3889]
i get the following error

thesheriff@CTCLP13:~$ keybase status
▶ INFO Forking background server with pid=31792
▶ ERROR dial unix /home/thesheriff/.config/keybase/keybased.sock: setsockopt: invalid argument

my log id: 70b6d5cb1459f737557a051c

**Comment by maxtaco** [comment]
cc: @oconnor663 ?

**Comment by oconnor663** [comment]
Hmm, could be unrelated, but I notice your socket file is at `~/.config/keybase/keybased.sock` instead of `/run/user/.../keybase/...`. Have you done something interesting with `XDG_RUNTIME_DIR` or something like that? Could you give me the output of `ls -lh /home/thesheriff/.config/keybase/keybased.sock` and `file /home/thesheriff/.config/keybase/keybased.sock` please?

**Comment by gglanzani** [comment]
@oconnor663 I have the same issue but there is no `keybased.sock` file in `~/.config/keybase`

**Comment by oconnor663** [comment]
@gglanzani could you run `keybase log send` for us please? What distro / desktop are you running?

**Comment by gglanzani** [comment]
@oconnor663 I should probably mention that I'm using Bash on Windows, and that seems to be a general issue with the go library. See https://github.com/Microsoft/BashOnWindows/issues/832

This issue seems to have been fixed in the not yet released update to Bash on Windows. Unfortunately I cannot yet test it. I think it's probably safe to close it here.

I can still send the log though!

**Comment by averagejoey2000** [comment]
I am also running windows bash, and I have the same problem.

**Comment by oconnor663** [comment]
Got it, thanks for clarifying. Yeah we haven't tested bash-on-windows at all. @gglanzani, let me know if you get any interesting results after MS releases that fix.

**Comment by oconnor663** [comment]
(Unless you've been testing it, @zanderz?)

**Comment by gglanzani** [comment]
@oconnor663 @averagejoey2000 @maxtaco @the4ndy This is fixed in the latest Slow ring release. I'm afraid you'll have to wait a bit to get that outside Insiders previews.
