### ISSUE TITLE
Error Cannot find the corresponding private key

### ISSUE THREAD

**Issue by oliver602** [keybase/client#3988]
When I try` keybase login` I get 
> ERROR Sorry, your account is already established with a PGP public key, but this utility cannot find the corresponding private key on this machine.

`gpg -K --fingerprint` shows a fingerprint that matches the one displayed in the error message above.

I'm using Ubuntu 16.04.

my log id: fe3bd16dd5f6f4e78ad0b41c

**Comment by juanminm** [comment]
@oliver602 I see that you are using Ubuntu 16.04, can you use `gpg2 -K --fingerprint`?

If there is no output, then that means Keybase is excepting `gpg2` instaed of `gpg`, and because of gpg2 is using version >=2.1.0 as of 16.04 LTS, the secret keyring differs.

To solve it, you'll have to use `gpg --export-secret-keys {UID|KeyID|Fingerprint} | gpg2 --import`

**Comment by oliver602** [comment]
Thanks @juanminm this did solve my problem. I had been using gpg 1.4.X

**Comment by maxtaco** [comment]
Thanks for the help @juanminm. It's too bad version 2.0 and version 2.1 are incompatible while versions 1.4 and 2.0 are compatible.  Makes it very tricky to workaround...
