### ISSUE TITLE
I/O Timeout (error 1601)

### ISSUE THREAD

**Issue by searsaw** [keybase/client#4071]
I'm trying to interact with the keybase server using the CLI. However, I can't do any commands that require connecting with the servers. I am behind a corporate proxy. I'm not sure if the connection is being block or if the CLI is not picking up the environment variables typically used to direct traffic to my local proxy that then points to the corporate proxy. The environment variables that are being set are as follows:

http_proxy
https_proxy
ftp_proxy
rsync_proxy
HTTP_PROXY
HTTPS_PROXY
FTP_PROXY
RSYNC_PROXY

Is there a way to enter proxy settings into the keybase CLI?

my log id: 45e98dc3a0b6d0772449581c

**Comment by cjb** [comment]
@searsaw Ah, we do respect HTTP_PROXY, but there's a long-running `keybase service` process that needs to be the process that gets the environment variable set. Since you're on macOS, the easiest way might be:
```
launchctl setenv HTTP_PROXY http://asdjopjop
```
and then restart Keybase or your machine to get it picked up. But that's a global change to your system, so you should confirm that you're comfortable with every launchd process getting that envvar..

**Comment by patrickxb** [comment]
You can set it in the keybase config file just for keybase:

    keybase config set proxy http://asdfasfd

I'm not sure if you need to restart the service after that, but it can't hurt:

    keybase ctl restart

Like @cjb said, keybase will respect the HTTP_PROXY env variable, but you can use the config file just to change the setting for keybase.

**Comment by searsaw** [comment]
Thanks for the help, but it didn't fix it. I'm assuming our proxy is just blocking it. I appreciate it!
