### ISSUE TITLE
So many write failures

### ISSUE THREAD

**Issue by FesterCluck** [keybase/client#4175]
Write failures, the horror.

my log id: 500afad767ad3452e87eea1c

**Comment by strib** [comment]
Looks like you might have been having network/DNS issues for a while?  I see a lot of this:

```
98674 2016-09-03T17:54:06.293578 - [WARN kbfs connection.go:519] 2557 MDServerRemote: connection error: "dial tcp: lookup mdserver.kbfs.keybase.io: getaddrinfow: No such host is known."; retrying in 302.630087ms
```

This goes for a while, starting around 17:29 (your local time) until 19:54, on and off.  Is it possible your network is flaky?

Otherwise, I'm not sure what to look for.  Can you be a little more specific about what exact problem you had and when it was approximately?  Thanks for the report!

**Comment by FesterCluck** [comment]
I'm on solid network, but that may indeed have been the case. Please close and I'll report with more detail if I see it again.
