### ISSUE TITLE
Error while copying files using Caja (Debian 8, Mate Desktop)

### ISSUE THREAD

**Issue by lucasrca** [keybase/client#4254]
**# Error while copying files using Caja, Mate Desktop file manager.**
_This error occurs randomly, with different file sizes and types._

**uname -a**: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
**Desktop**: Mate.
**Keybase Client**:  1.0.17-20160908193355+c2873a5
**Keybase Service**: 1.0.17-20160908193355+c2873a5
**Message**: "Error closing file: Input/output error".

**my log id: 546e557b8951bc3dba1b931c**

**Comment by lucasrca** [comment]
Update:
Using command line;
cp: error writing ‘/keybase/private/lucasrca/backups/file.gpg’: Input/output error
cp: failed to extend ‘/keybase/private/lucasrca/backups/file.gpg’: Input/output error

**Comment by strib** [comment]
Thanks @lucasrca.  Can you please do a new `keybase log send`?  Will be easier to track down the error when I know the file names involved.  I didn't see anything obvious at a first glance through your first logsend, diving deeper now but it would be easier with a new one.  Thanks!

**Comment by lucasrca** [comment]
@strib , 570c2901a282ea7c2e4ea61c

Filename: 20160912144401.backup.tar.gz.gpg (240.5 MB)

**Comment by strib** [comment]
Hmm.  I'm seeing messages that make it seem like write operations were canceled after a little more than a second.  (Seems like your throughput to our backend servers is a bit slow, so writes are taking a long time.) But I don't imagine `cp` would be cancelling anything.  You're not hitting ctrl-C on the `cp`, right?

Perhaps Caja (or some other process) might be cancelling things, and KBFS is propagating those cancels to the `cp` process.  In fact that seems somewhat likely.  Do you happen to know offhand if Caja has hard timeout limits on file system operations?

(For the record, we're in the middle of re-architecting our write workflow so that it doesn't depend on your network connection, which should make issues like this go away for most people.)

**Comment by lucasrca** [comment]
@strib 
Let's see:
- I didn't cancel the operation. In fact, I saw this error three times.
- I'm using a very slow network connection right now (20 Mbps / 20 Mbps with ~1000 users. No joke).
- I've tested the same file with Caja and shell (cp) directly.
- I don't know if Caja has hard timeout limits. I'm using Mate because I've got tired of using Gnome shell. Never saw this error using SMB shares, rsync or scp, for example.

Don't worry. I'm just trying to contribute to this project.
Can I close this issue or do you want to keep it open?

**Comment by strib** [comment]
Thanks, I really appreciate the reports and the extra info!

Let's keep this open, if only because I do not know where the cancels came from.  I'm worried it might be something internal that we added recently, since there doesn't seem to be any interrupts coming through FUSE from the application at all.

But without more to go on I'll probably just wait and see if we get more repros, and in the meantime keep my eyes open in the code for things that could possibly cause this.

**Comment by lucasrca** [comment]
@strib , OK. I'll try to trace and log the next copy with a better network connection. I'll post here if I find something new.
Thanks.
