### ISSUE TITLE
Issue with sign-up

### ISSUE THREAD

**Issue by KasiaCat** [keybase/client#4302]
Hello, 

I;m unable to sign-up. During signup, I put e-mail, login,  my invitation code and received an error: FAILED to get getpin greeting : EOF

my log id: 4bff1b70a8d44df0aed1771c

**Comment by maxtaco** [comment]
CC: @cjb and @oconnor663, looks like electron didn't start up properly, and also pinentry is failing!

**Comment by maxtaco** [comment]
For now you might try:
```
keybase ctl stop
export KEYBASE_PINENTRY=none
keybase ctl start
```

**Comment by maxtaco** [comment]
and then try to login again

**Comment by cjb** [comment]
Hi @KasiaCat, it looks like the GUI (in your menubar) quit about five minutes after it started.. it started at 16:09, quit at 16:13, and then you were trying to log in at 16:06 (before it ran) and 16:27 (after it had quit).  If the GUI isn't running we try to use pinentry, but you're on Debian so that's probably not available.

Please could you try running:

`run_keybase`

and then use the GUI window to do the signup?  If anything doesn't work, run `keybase log send` again and let us know the new ID and what happened.  Thanks!

**Comment by KasiaCat** [comment]
Hi,

Solution sent to me by Maxwell Krohn worked.
Thank you Maxwell and Chris for all your help and timing.

I'm so happy that you worked the solution so fast.

Thank you!

Regards,
Katarzyna

2016-09-16 21:58 GMT+02:00 Chris Ball <notifications@github.com>:
