### ISSUE TITLE
Users public folders re-appear after delete (Windows)

### ISSUE THREAD

**Issue by bkimminich** [keybase/client#4316]
Keybase GUI Version: 1.0.17-20160822153555+692af12

When deleting another user's folder from `/public` in KBFS on Windows 10 it is simply downloaded again after a few moments. It does not seem to matter if I delete via `cmd.exe` or Explorer.

**Comment by juanminm** [comment]
That is because another program has it cached and pings the folder making it reappear. I would recommend closing Keybase GUI and try to `rmdir` it. If after that it doesn't work try doing this: https://github.com/keybase/client/issues/3958#issuecomment-241266058

One cause can be RuntimeBroker (used for Windows App like Time, Photos, etc...), killing the process (harmless), then `rmdir` the public folder should make it disappear, that is if RuntimeBroker is the cause.

As a last resort doing the same but with a reboot after removing could help it.

**Comment by taruti** [comment]
The issue is that accessing a folder adds it back.

The most common issue is some application (such as explorer or a browser) having a file in "recent files" and trying to access it.

**Comment by bkimminich** [comment]
Killing Keybase GUI, RuntimeBroker and Explorer and doing `rmdir` via Commandline did the trick! Thanks!

**Comment by villasv** [comment]
This happened to me too. Is there a way to avoid this in the future? Or am I going to go through this every time I want to get rid of some public folder?
