### ISSUE TITLE
Freezing on MacOS Sierra

### ISSUE THREAD

**Issue by Khillo81** [keybase/client#4380]
Keybase GUI Version: 1.0.17-20160913233827+18b5a25: 

Hi guys,

It seems that the program is facing problems on MacOS Sierra: upon mounting any network drives or running Parallels, the app freezes and causes problems with Finder. Yesterday, I tried to mount a network drive and the spinning wheel appeared for several minutes without anything happening. Finder then froze and I had to boot the machine several times before the problem was resolved (I knew it was Keybase because the problems continued until the Keybase drive appeared on the desktop after which everything worked normally. I could even mount my network drive thereafter). Today, upon launching Parallels 11, the same problem happened and until now the drive refuses to mount. I have quit Keybase for the moment so I can continue working.

**Comment by cjb** [comment]
Hi, thanks for the report, we're already trying to get this fixed.  It seems to be a bad interaction with Time Machine; if you disable Time Machine the hangs go away.

We'll push out a build that disables KBFS on Sierra while it's being worked out.

**Comment by gabriel** [comment]
Thanks for submitting an issue.

We've pushed out an update a few hours ago, https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160922174631%2Bf87e42c.dmg which temporarily disables KBFS in Sierra, while we work on a fix.

You can also remove Keybase.app from startup (via System Preferences, User, Login Items) and if you are on an older version and `~/Library/LaunchAgents/keybase.kbfs.plist` is still around after quitting Keybase, you should remove that too.

Will close this (as dupe) so that discussion continues at https://github.com/keybase/client/issues/4237
