### ISSUE TITLE
unable to edit/delete old files after "start from scratch"

### ISSUE THREAD

**Issue by suhz** [keybase/client#4519]
I am playing around with keybase, everything works fine until I do "reset my keys & start from scratch".

What I've done
1. I clicked on "reset my keys & start from scratch"
2. I generate new gpg keypair on my mac & put it to keybase.io
3. Log in to keybase apps on my mac, add new device, then I saw a folder named **"suhz (files before account reset 2016-10-04)"** which I cannot edit or delete the folder or files in it. It keep saying that I need to rekey 

```
Suhaimis-MacBook-Air:public suhaimi$ rm -fr "suhz (files before account reset 2016-10-04)"
rm: suhz (files before account reset 2016-10-04)/index.md: Input/output error
rm: suhz (files before account reset 2016-10-04)/suhz.jpg: Input/output error
rm: suhz (files before account reset 2016-10-04)/._index.md: Input/output error
rm: suhz (files before account reset 2016-10-04)/._suhz.jpg: Input/output error
```

my files on keybase.pub is also not updated or is not pointing to my correct public folder. https://keybase.pub/suhz/

my log id: 7d773ac302bd8e8d2b4d701c

**Comment by strib** [comment]
These "files before reset" are read-only.  There's no safe way for us to allow anyone to edit those now that your account is closed.  We make them available in a read-only way so you can copy them into your new public folder if you want.  So that part's intentional.

Seems like the real issue is that keybase.pub hasn't updated your public folder due to a known bug.  I'll restart keybase.pub tomorrow morning to make sure it picks up your new folder.  Sorry for the inconvenience!

**Comment by strib** [comment]
Ok, I restarted keybase.pub and your folder looks correct now.

By the way, if you're trying to remove that old folder from your favorites list, you can do it via the GUI or with `rmdir "/keybase/public/suhz (files before account reset 2016-10-04)".

Please close this if everything looks ok.

**Comment by suhz** [comment]
I can see my folder correctly now, thanks
