### ISSUE TITLE
Un-rekeyable folder in KBFS

### ISSUE THREAD

**Issue by sdigit** [keybase/client#4657]
I've still got a folder in KBFS that I cannot rekey; I tried to force it to rekey similarly to how I did another folder (by creating a new file in it), however that did not work. I got EIO from `touch` on the directory in question. Nobody other than myself ever touched the folder to my knowledge, and there is nothing in it I need to save so it can be blown away if necessary.

Sorry to bring this one back up!

my log id: 44fccd3dc6d29aac7e6eeb1c

**Comment by strib** [comment]
Ah, I see.  The client is trying to verify an update to the folder that was written back in April, by a device of yours that has since been revoked when you reset your account.  This is all handled automatically now, but back in April we still had some live bugs that affected the folder.  Sorry about that!

If you'd like us to reset the folder, please run the following command on one of your devices, and substitute the current date, time, and folder users as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folder /keybase/private/<FOLDER USERS> because I cannot rekey it due to an old KBFS bug."
```

and post the output here.  However, since this is a private folder containing other user names, you might want to keep it secret.  In that case, feel free to encrypt the whole thing for me personally before posting it with `keybase encrypt ... strib@github`, or just put it in `/keybase/private/dive,strib@github`.  Thanks!

**Comment by sdigit** [comment]
File is now in /keybase/private/dive,strib@github :)

I wasn't positive whether you meant sign it and put that output there, or just put the message itself there, so the file `git4657` is the saltpack signed message. Thanks again!

**Comment by sdigit** [comment]
I've also created `git4657.2` in the same directory since I forgot to include the time. TZ is US/Central.

**Comment by strib** [comment]
Perfect thanks, I wanted the saltpack signed message, so we could prove to ourselves or any auditors at a later date that someone associated with the folder wanted it reset.

I reset the folder -- please close this out if everything looks ok.  Thanks, and sorry for the inconvenience.

**Comment by sdigit** [comment]
Don't apologize for the inconvenience, if I expected 100% stability I wouldn't be playing around as an early adopter :smiley:

Closing this out now, thanks again!
