### ISSUE TITLE
conflicted directory handling fail

### ISSUE THREAD

**Issue by drammock** [keybase/client#4659]
userA and userB are sitting in the same office.
- userA invited userB to keybase, by creating directory `/keybase/private/userA,userB@github` and putting `foo.txt` in it.
- userB signed up, followed userA, then created directory `/keybase/private/userB,userA` and created `bar.txt` in it.
- userB proved his GitHub identity.
- userA saw his shared folder name change to have `(conflicted copy {TIMESTAMP})`, userB saw a popup notification about a conflicted copy, but his foldername didn't change.
- userA still saw only `foo.txt` in the terminal
- userA opened the keybase app, and saw two folders: `userA,userB` and `userA,userB (conflicted copy {TIMESTAMP})`
- userA opened the conflicted folder in Thunar, and moved his original file into the non-conflicted folder.
- userA did a right-click-delete of the conflicted folder, at which point ***the non-conflicted folder disappeared in Thunar, along with the files inside it, leaving only the (empty) conflicted folder.***
- userA exclaims "WTF" and heads for the documentation, which says

> When both devices create a directory with the same name, they will be intelligently merged (dealing with children conflicts recursively).

- userB reports that he can see both `foo.txt` and `bar.txt`, userA can see neither.
- userA sends log and creates this issue report.
- after sending log, userA tries: 

```bash
$ cd /keybase/private
bash: cd: /keybase/private: Transport endpoint is not connected
```

my log id: b2719e555a3d191e50e8bf1c

**Comment by strib** [comment]
Thanks for the report! There's a lot to unpack here.  First:

> userA exclaims "WTF" and heads for the documentation, which says
When both devices create a directory with the same name, they will be intelligently merged (dealing with children conflicts recursively).

I agree this is confusing -- this is talking about a directory _within_ what we call a top-level folder (TLF).   (We avoid calling a TLF a "directory" anywhere in our documentation, though it's certainly understandable to make that association.) A TLF is the unit of encryption in KBFS, and corresponding to an entry under `/keybase/private` or `/keybase/public`.  When there are conflicts at the TLF-naming level, which happened when userB created `/keybase/private/userB,userA` before proving their github identify, we don't do any auto-merging (mostly because we can't do anything atomically across two TLFs without risking data loss).

> userB saw a popup notification about a conflicted copy, but his foldername didn't change.

Yes, this is intentional.  We don't auto-favorite the conflicted folder for anyone who didn't have it already.  userB could explicitly navigate to it on the command line if they choose to.  Eventually, we will have auto emails that explain this and show how to find the conflicted copy without it appearing in your favorites.

> userA did a right-click-delete of the conflicted folder, at which point the non-conflicted folder disappeared in Thunar, along with the files inside it, leaving only the (empty) conflicted folder.

This is definitely an issue.  But I'm having a hard time finding these events in the log.  I see a TLF that becomes conflicted.  But then I don't see any actions being done to files in that folder, other than listing it.  In particular, I don't see any files being deleted, and I don't see any accesses to the corresponding non-conflicting folder.

Are these logs from userA, and from the same device on which `foo.txt` was moved between the folders? (And sent after that operation?)  If not, can I please get a `keybase log send` from that device?

Also, just to be explicit, userA ran keybase using the included `run_keybase` script, and not with any manual commands (which might have put the relevant logs somewhere else), right?

> after sending log, userA tries:
> $ cd /keybase/private
> bash: cd: /keybase/private: Transport endpoint is not connected

This is scary, but it looks like the `log send` didn't capture whatever happened here.  Can userA please do another `keybase log send` and post the ID here?

**Comment by drammock** [comment]
> Are these logs from userA, and from the same device on which `foo.txt` was moved between the folders? 

Yes.

> (And sent after that operation?)

Pretty sure yes, but just in case: 5c29c128665728198939f61c
(note that a lot of other stuff has gone wrong in the meantime; see #4661)

> userA ran keybase using the included `run_keybase` script, and not with any manual commands

Yes.

Eventually I went to my laptop, which showed both conflicted and unconflicted folders, and showed both `foo.txt` and `bar.txt` in the unconflicted one.  Deleting the conflicted folder with `rmdir` on the laptop worked.

**Comment by strib** [comment]
Ah thanks, those logs have more info.  We found the issue, and a fix is in review.

It doesn't seem like you lost any data, so that's a win!  Restarting kbfs on any clients that still see the wrong folders should fix the issue for you.  Sorry for the inconvenience.

**Comment by drammock** [comment]
thanks @strib

**Comment by strib** [comment]
The client fix is merged and will be in the next release.  Thanks again for the report!
