### ISSUE TITLE
/keybase directory in root

### ISSUE THREAD

**Issue by ptman** [keybase/client#4739]
What is it doing there?

**Comment by strib** [comment]
https://keybase.io/docs/kbfs

**Comment by ptman** [comment]
Ok, so a FUSE-filesystem? Why does it have to be in the root, as a world-writable directory?

**Comment by strib** [comment]
It's not world writeable, it's not even writeable by root.  Just by the user who ran keybase.  (The owners you see in `ls -l` don't mean anything, FUSE enforces other permissions.)

It's in root because we want to have global pathnames, i.e., you can send a path to a file to a friend, and they will see it in the same place on their file system.  More details: https://keybase.io/docs/kbfs/understanding_kbfs.

Please close this out if that's enough info.

**Comment by ptman** [comment]
Is there a way to permanently disable it?

**Comment by strib** [comment]
No supported way, but if you tell us what platform you're on we might be able to give you advice about how to turn it off.

If it is causing any real problems for you, please let us know the specifics and maybe we can fix them.

**Comment by oconnor663** [comment]
@ptman at some point we'll have a wider variety of packages available, so that you can install just the command-line-identity-proving tools without pulling in the GUI and KBFS. We haven't gotten to that yet, so in the meantime the surgery you need to do to disable any particular component is a little dirty.

**Comment by ptman** [comment]
Thank you for considering splitting it out. How is it started? How do I prevent it from starting automatically? Should I see it if I pgrep kbfs? What creates /keybase? dpkg -S /keybase doesn't tell me that it belong to the package.

**Comment by oconnor663** [comment]
`/keybase` gets created by a postinstall script that runs during package installation, `/opt/keybase/post_install.sh`. We do that because it needs to be writable by all users, to allow FUSE mounts. (Note that the FUSE mounts that go over it are _not_ writable by all users though, thankfully.)

Keybase gets started by `~/.config/autostart/keybase_autostart.desktop`. The keybase client itself creates that desktop entry when it runs, if the entry is missing. If you want to disable it, there are instructions inside it about what to comment out. The command that autostart executes to launch Keybase is `/usr/bin/run_keybase`.

**Comment by scruss** [comment]
Please never ever ever create anything in the / folder; you're just lucky that this system doesn't have a usual tiny r/o root filesystem. Now, how do I delete /keybase/?

**Comment by strib** [comment]
We don't use any space in your root directory.  `/keybase` is just a mountpoint to a different kind of filesystem.

**Comment by Wolf480pl** [comment]
Is there any blog post or something explaining how you considered other options and came to the conclusion that `/keybase` directory is a good idea?
As far as I understand it, it has a few significant disadvantages:
* when no kbfs is mounted, everyone can write anything they want to the /keybase directory
* two simultaneously logged in users can't both use kbfs at the same time
* it violates filesystem hierarchy standard of about every distro

**Comment by strib** [comment]
@Wolf480pl: there's a longer discussion here: keybase/keybase-issues#2306.

**Comment by libBletchley** [comment]
@strib 
> It's not world writeable, it's not even writeable by root. Just by the user who ran keybase. (The owners you see in ls -l don't mean anything, FUSE enforces other permissions.)

A mountpoint does not block access to a directory.  When a mountpoint hides a directory, the underlying directory can still be accessed by creating a bind mount.  Furthermore, `/keybase` is vulnerable even without a bind mount during the time the mountpoint is not mounted (which is permanent for users who have opted not to trust the servers that run continuously).

> We don't use any space in your root directory. /keybase is just a mountpoint to a different kind of filesystem.

Why isn't it in `/mnt/`, `/media/`, or `/run/media/`?

**Comment by Wolf480pl** [comment]
@libBletchley 
>If the directory were to store data, it should be in `/var/lib/`. But since it's just a mountpoint, why isn't it in `/mnt/`, `/media/`, `/run/media/`, or `$HOME/mnt`?

Yeah, exactly.
Also, AFAIK the most standards-compliant location would be `/run/media/$USER/keybase`

**Comment by kotnik** [comment]
If creating `/keybase` directory is the best idea you got, I can only imagine the other shortcuts you took in other parts of your software.

Please disable this by default, or use saner default, imagine if every application created its own `/` directory for Important Stuff.

**Comment by atdt** [comment]
Dear Librarians,

Thank you for purchasing a copy of my latest novel for your collection. Please be advised that copies of my new book are to be placed on a dedicated pedestal at the entrance of each library branch. This is not for my self-glorification; it's for the convenience of my readers. You see, instead of forcing readers to figure out the vagaries of the library classification system you employ, the call-number you assign to my book, and the shelf this call-number is consigned to -- all of which vary by system and branch! -- I am providing my readers with a simple, consistent, and universal experience: no matter where they are in the world, my book will be on a pedestal at the entrance. No need to browse the catalog or ask the librarian for direction. If a loyal reader wants to recommend my book to a friend in another city or country, she can simply tell her friend: "it's that book on a pedestal at the entrance". I am sure you will agree this is a better experience for readers!

Thanks in advance.

**Comment by atdt** [comment]
_Applications must never create or require special files or subdirectories in the root directory. Other locations in the FHS hierarchy provide more than enough flexibility for any package._ - The Filesystem Hierarchy Standard ([section 3.1, purpose of the root filesystem](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03.html#purpose2)).

Folks, I appreciate your mission and your work, but I am uninstalling Keybase and advising others to do the same. The single-minded focus on Keybase convenience coupled with flagrant disregard for norms about how a well-mannered utility ought to behave, unwillingness (or ambivalence) about giving users control of their system, and a galling deaf ear to over a year's worth of users expressing frustration and outrage -- these do not inspire confidence in the future of the platform.

**Comment by oconnor663** [comment]
Minor update: Now that we launch KBFS via the systemd `kbfs.service` user unit when possible, one way to change the mountpoint is to override the `ExecStart` arguments using `systemctl --user edit kbfs.service`.

**Comment by simonvanderveldt** [comment]
Has there been any progress on this? This issue is already over a year old.
Code wise the change seems to be pretty small, so what needs to happen to change this?

**Comment by oconnor663** [comment]
@simonvanderveldt see the discussion linked above, https://github.com/keybase/keybase-issues/issues/2306.

**Comment by flotwig** [comment]
When will this issue be addressed? It's annoying and, as many people in this thread have noted, there's no logical reason why this application follows this behavior.

If this issue still exists with this app after 2 years, I wonder what other sorts of issues exist in Keybase that have not been discovered. It is extremely concerning that an application that purports to have a solid, secure codebase still has mistakes in the codebase like this.

**Comment by strib** [comment]
We've addressed this on other similar threads, but I guess not here.  See the "Root redirector" section of https://keybase.io/docs/kbfs/understanding_kbfs for how to turn this off if you don't want it.

**Comment by strib** [comment]
> Why is it still the default?

Because it gives our users the best, most consistent cross-platform experience.

**Comment by flotwig** [comment]
> > Why is it still the default?
> 
> Because it gives our users the best, most consistent cross-platform experience.

Can you explain how? Isn't part of the cross-platform experience using the conventional directories that users expect?

**Comment by antony** [comment]
It appears that something happens to the keybase directory which completely breaks system updates, and causes every single filesystem operation by the user to take ~60 seconds to complete (or in the case of `ls` in `/`, completely fail unless I use sudo).

I appreciate the decision to create this file, but Linux is a multi-user system, where it is not acceptable to just stick things in the root of the system hierarchy.

It's a poor default. I realise that I can turn it off, but it should be opt-in, not opt-out.
