### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by b264** [keybase/client#5060]
Keybase GUI Version: 1.0.18-20161205170037+abed0df

Newest update for Ubuntu 14.04 now says:
```
Error opening file '/keybase/private/user_name/filename.txt': Transport endpoint is not connected

The file on disk may now be truncated!
```
when attempting to save an open file (not open a new file) from a text editor.  It appears the `/keybase` folder no longer exists on the filesystem.

here is bash: (non-relevant items removed)
```
user@hostname:/$ ls -al
ls: cannot access keybase: Transport endpoint is not connected
total 120
drwxr-xr-x  26 root root  4096 Dec  7 13:05 .
drwxr-xr-x  26 root root  4096 Dec  7 13:05 ..
d?????????   ? ?    ?        ?            ? keybase
```

**Comment by strib** [comment]
Hi @b264, could you please do a `keybase log send` and post the resulting log ID here, so we can see what's going on?  Thanks, and sorry for the inconvenience.

You can probably get it going again by re-running `run_keybase`.

**Comment by b264** [comment]
```Success! Your log ID is:

  cbf1f0f3aba9ef5711a7a01c```

**Comment by strib** [comment]
Thanks.  Looks like our servers thought you were logged out, possibly due to a known race we haven't tracked down yet.  That triggered an intentional crash on our end so we can debug issues like that.

Looks like you restarted, are things working ok now?  Probably just a fluke that we'll be working on soon.

**Comment by b264** [comment]
Yes; `run_keybase` in bash did resolve my issue.  Closing issue.

**Comment by AlexisWilke** [comment]
Note that I ran into this problem today.

I'm wondering why it would not timeout. When I tried to run `df` in this case, it blocks forever. Actually, any software that uses the `statvfv()` function will block until you restart keybase. I don't think that's a good way to handle this case (although it may be an OS problem rather than your direct problem?)

**Comment by totedati** [comment]
On systemd enabled distros, like is my kubuntu bionic beaver 18.04, you should simply restart kbfs filesystem:
`systemctl --user restart kbfs.service`

Can be done from user console terminal no need for root acces because kbfs is a fuse fs anyway

Look like when you do a logout/login round kbfs filesystem is left in an inconsistent state and any `cd /keybase` console command spite this strange error 

> /keybase: Transport endpoint is not connected

In `file $(which run_keybase)` you can see all this commands but for 

> Transport endpoint is not connected

error a full keybase restart i think is too much, on my case gui applet is here and i can open main keybase gui app windows, only kbfs is fluffy
