### ISSUE TITLE
It told me to upload stuff

### ISSUE THREAD

**Issue by JamieH** [keybase/client#5132]
I uploaded my log for you - I tried to upload 2 folders on my Mac via KBFS - I cancelled 1 of the operations and then tried to cancel the other one and the whole thing locked up :(

my log id: 563afc673b7e187b2bfe011c

**Comment by strib** [comment]
Hi @JamieH, thanks for the report.  The uploads failed because KBFS was trying to upload more than it could handle in the file system timeout imposed by macOS.  We have a fix in the work for that which is almost ready, but in the meantime you might not be able to upload large amounts of data on slowish connections.  Sorry about that.

I'm more worried by "and the whole thing locked up".  Can you please explain how you were uploading (i.e., was it drag and drop with Finder, using `cp` or `rsync`, etc) what you did to cancel it (ctrl-C?), and exactly what locked up (your whole OS? a tab in your terminal?).  Thanks!

**Comment by JamieH** [comment]
It only processed about 6KB over 5 seconds though, is that expected? I'm on a reasonably fast connection too.

I was using drag and drop with finder, I cancelled by clicking the x button on the progress window on the transfer, and then Finder locked up.

**Comment by strib** [comment]
According to the logs it took over 16s to transfer 8 MB of data to our servers.  Some of that time is our server's processing time, but likely a lot of it was either congestion in your network to our servers, or high CPU usage by some other process on your device.  Its hard for me to tell the exact cause from the logs.

I'm sorry about the lockup, I can't find any clues in our logs about that.  I'll open an internal ticket for us to try to reproduce.

**Comment by JamieH** [comment]
The Finder UI certainly didn't reflect that. I think the highest I saw it at was 16KB. I'll respond if I get it to do the same again

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
