### ISSUE TITLE
Centos 6.8 64 bit - no /keybase folders accessible.

### ISSUE THREAD

**Issue by sot001** [keybase/client#5283]
Hi

I've just installed (plus tried reinstalling a few times) and it hasn't mounted my /keybase directory from what I can see. The directory is there but isn't accessible.

The keybase service is running, but not the KBFS (not sure if its supposed to be);

KBFS:
    status:    not running
Service:
    status:    running

my log id: 9be6528e22ee4cbb1f3a031c

thanks
K

**Comment by sot001** [comment]
forgot to add the GUI doesn't appear for me either, however that may have to do with the fact I'm accessing the server via NX

**Comment by maxtaco** [comment]
Try 'run_keybase'

**Comment by sot001** [comment]
yep, tried that a few times;
$ run_keybase
Shutting down keybase service...
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!

(plus the squirrel) 

but still no GUI or (more importantly) the /keybase mount. Mount point is there but no folders beneath it.

thanks for the suggestion though, willing to try anything

**Comment by maxtaco** [comment]
cc: @oconnor663

**Comment by oconnor663** [comment]
Thanks for the log dump, the errors pop out in there. (If you want to see these logs yourself, look in `~/.cache/keybase/*.log`.)

The KBFS log shows `fusermount: fork/exec /bin/fusermount: permission denied`. I'm not familiar with all the ways that FUSE works on different distros, but you might need to add the user in question to some fuse-related group? Please let me know what you need to do on your machine, since we might need to document it.

The GUI log shows `/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /opt/keybase/Keybase), /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /opt/keybase/Keybase)`. I assume that's to do with your server not being a regular desktop machine? Curious if you know more.

**Comment by cjb** [comment]
@oconnor663 I'd guess it's because CentOS 6 is based on RHEL 6, which was released in 2010, forked from Fedora 12, still ships a 2.6.32 kernel even in the latest 6.8 update.

I don't think we should support non-current versions of CentOS or RHEL.

**Comment by sot001** [comment]
@oconnor663 I saw the permission denied errors so then tried  'run_keybase' with sudo, but thats probably not the best way to do it. I'll do a bit of reading and see what groups my account needs to be in for FUSE mounting and see if I can get it started

The GUI I can happily do without as I was thinking to install it on a server

@cjb correct, it has a 2.6.32 kernel. I'll try it again on a Centos 7 and Jessie box, both of which have version 3 kernels

**Comment by sot001** [comment]
Success!

To get it working I had to add my user to the fuse group;

usermod -G fuse <user>

I tried 'run_keybase' and it through the same permission errors, even though the fuse group had execute permissions on the binary. So then I  tried to add +x to fusermount binary;

sudo chmod +x /usr/bin/fusermount

And then it works. Adding my user to the group may not be required as I've removed myself from that group and it is still working.

Thanks for your time a guidance guys, great product.

**Comment by oconnor663** [comment]
Awesome. This was another case where having `run_keybase` return real errors would be really great. Unfortunately it's starting background processes that don't exit at all in the success case. Systemd integration might be able to give us something here (I think it includes some logic to detect crashes that happen "quickly"?), but I'm not sure even that would come for free.
