### ISSUE TITLE
Stuck on Loading Screen

### ISSUE THREAD

**Issue by tom-davies** [keybase/client#5399]
Keybase GUI Version: 1.0.18-20161219123904+7868d49

What should happen: Keybase opens the GUI
What actually happens: Keybase stays on the Loading screen forever

**Comment by otteydw** [comment]
I am having this same issue.  Just installed the client on Friday and it was working fine.
https://github.com/keybase/client/issues/5491

Now "My Computer" no longer shows the KBFS drive (K:) and when I launch the GUI it just says "Loading..."

**Comment by cjb** [comment]
@otteydw Please could you run `keybase log send`?  You too please, @tom-davies.

CC @zanderz

**Comment by otteydw** [comment]
@cjb I have run the command per your request.

Also note that while I currently have a AppData/Local/Keybase/Gui, I no longer have an AppData/Local/Keybase/keybase.exe (I think the CLI) as I remember having on Friday.  I don't know where it went?

**Comment by otteydw** [comment]
I went through "add/remove programs" and had Keybase reinstall itself.  This worked,  The Keybase/keybase.exe was again present, and the GUI loaded successfully.  Later my computer rebooted.  After restart, the Keybase/keybase.exe is no longer present.

**Comment by zanderz** [comment]
Can you post the log ID number after doing log send?

Reinstalling an older version is not quite the same as updating to a newer version. There was recently a change in target installation directory, from %APPDATA%\Keybase to %LOCALAPPDATA%\Keybase. Sometimes the migration of settings fails. As a last resort, it should be OK to:

1. uninstall old Keybase + Dokan
2. copy everything remaining from %APPDATA%\Keybase to %LOCALAPPDATA%\Keybase
3. install the latest version from keybase.io

No idea how your keybase.exe could disappear, unless it was due to the above migration.

**Comment by otteydw** [comment]
I did not "reinstall an older version" to resolve the issue.  I mean, basically I ran the same installer I grabbed on Friday and it said I should uninstall and reinstall.  When I went to uninstall, there was an option to either repair or reinstall.  So I chose that option (assuming the installer didn't change since Friday).

So what I'm saying is that %LOCALAPPDATA%\Keybase\keybase.exe is the one that is disappearing.  And I assume that is the one I need to call to send the logs...

I do not see a Keybase directory under %APPDATA%.

**Comment by otteydw** [comment]
So, I think this happened again just yesterday.  I noticed yesterday afternoon that my computer "spontaneously" restarted (ie: Windows showed me "Restarting" and then it cleanly rebooted).  When it came back up, the Keybase GUI was stuck "Loading" again.  And again my %LOCALAPPDATA%\Keybase\keybase.exe is missing.

If I'm not mistaken, it looks like keybase released an update at that time yesterday?  And for some reason the auto update is set to true, but it triggers a silentl reboot without me being prompted.  If this is correct, I consider it a major problem.  (It is possible that the prompt did come up, but the default was "OK" and whatever typing I was doing at the time just caused the OK button to be selected.  I would still consider this to be a problem because I never saw the popup.)

And this still doesn't resolve the fact that when the update is occurring, my keybase.exe file is disappearing.

Here is the updater log that brought me to this conclusion.
[keybase.updater.log.txt](https://github.com/keybase/client/files/750450/keybase.updater.log.txt)

**Comment by zanderz** [comment]
Silent reboot would be a serious error, but we haven't seen any more of those lately. Can you do a `keybase log send` to include the installer logs? That will show if it's our installer doing the reboot.

Disappearing keybase.exe is very unusual, it doesn't happen to us and no other user is reporting that. Your updater log does show an upgrade yesterday, but the drivers were current, so no reboot should be required.

**Comment by otteydw** [comment]
Again, I can't do a keybase log send because keybase.exe is no longer present.  Do get it back I have to go an uninstall and reinstall.

And I think @tom-davies was reporting this same issue (Loading...) which I believe happens when keybase.exe is missing.  That would make two of us.

If I uninstall and reinstall, would a keybase log send still be worthwhile?

**Comment by zanderz** [comment]
Might be easier to just send the 3-4 most recent `%TEMP%\Keybase*.log` files, which is what `keybase log send` does anyway.

**Comment by zanderz** [comment]
ah, yes, @tom-davies sent a log but not the ID and I couldn't find it.

**Comment by otteydw** [comment]
[Keybase_20170202160155.log.txt](https://github.com/keybase/client/files/751674/Keybase_20170202160155.log.txt)
[Keybase_20170202160155_000_KeybasePrograms.log.txt](https://github.com/keybase/client/files/751675/Keybase_20170202160155_000_KeybasePrograms.log.txt)
[Keybase_20170202160418.log.txt](https://github.com/keybase/client/files/751676/Keybase_20170202160418.log.txt)
[Keybase_20170203074456.log.txt](https://github.com/keybase/client/files/751677/Keybase_20170203074456.log.txt)

I do see this line in the one log file:

> Product: Keybase Apps. Restart required. The installation or update for the product required a restart for all changes to take effect.  The restart was deferred to a later time.

Again, I don't believe I ever saw a pop up, and even if I did this says the restart was deferred.  And yet I'm pretty sure the restart occurred immediately.

**Comment by zanderz** [comment]
I see something too:
`RESTART MANAGER: Did detect that a critical application holds file[s] in use, so a reboot will be necessary.`
Again, on upgrade, the installer is invoked silently if auto update is configured and drivers are already current. The logs don't show which application or file this is - or at least I can't find where they do.

I suggest as a workaround to edit `%LOCALAPPDATA%\Keybase\updater.json` and set `"auto": false` - this will prevent silent reboots and should show the files in use dialog.

**Comment by srvg** [comment]
Same issue, I just send the logs c91d5f95185a00e7158e381c

**Comment by cjb** [comment]
@srvg What's your Linux distro? Sounds like you don't have $XDG_CONFIG_DIRS set.

**Comment by srvg** [comment]
@cjb Debian testing with no specific desktop environment (i3wm)
I can confirm $XDG_CONFIG_DIRS is not set. AFAIK there is no requirement for it to be set? There should be a default fallback when not set?

From the man page
```
$XDG_CONFIG_DIRS defines the preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME base directory. The directories in $XDG_CONFIG_DIRS should be seperated with a colon ':'.

If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used.
```

**Comment by sucrose** [comment]
I'm having the same issue. I'm using Windows 7 Ultimate 64bit.

Log ID: `5fefbf2b91ca080d68308b1c`

**Comment by zanderz** [comment]
@sucrose can you tell whether:
- any instances of `keybase.exe` (lower case) are running, using Task Manager?
- you have a shortcut called KeybaseStartup located at `%APPDATA%\Microsoft\Windows\Start Menu\Programs`?
- If so, does the UI come back if you invoke that shortcut?
We are seeing a few reports where the services don't start at reboot for some reason, and your symptoms match.

**Comment by sucrose** [comment]
@zanderz Sorry for the delayed response.

Yes there are about 6 processes running...
![2017-06-25 14_51_43-windows task manager](https://user-images.githubusercontent.com/5590958/27518794-00bc3a06-59b6-11e7-8a8d-2ecf6c55d48c.png)

I don't have KeybaseStartup in %APPDATA%\Microsoft\Windows\Start Menu\Programs. I do have KeybaseStartup in C:\Users\[USER]\AppData\Local\Keybase though. Nothing visually happens when I execute it.

**Comment by zanderz** [comment]
@sucrose We made a release a week or so ago which should help a lot with these issues. Can you make sure you're updated to it by issuing `upd check` at a Keybase Shell? If you still have problems after that, please do a log send again.

**Comment by nekromoff** [comment]
I am having this issue with the latest 1.0.33-20171003193427.d9ceb86ac

**Comment by zanderz** [comment]
@nekromoff Can you do a `keybase log send`? Thanks.

**Comment by nekromoff** [comment]
done c812f5ccada402e977f3b51c

**Comment by rptb1** [comment]
I have this issue on OS X 10.11.6, right after installation. Log id 4a6a3142a8a839588508a01c.
