### ISSUE TITLE
Reboot causes "This computer is unable to read files" Error

### ISSUE THREAD

**Issue by rawkode** [keybase/client#5519]
Log ID: 505b312020a920ae12ef9d1c

Precise Error:

> This computer and possibly others are unable to read some of your folders. To avoid losing > data forever, please turn on one of the devices below:
> 
> <paper device listed>
>

I've provided my paper key a handful of times, but on every reboot, or Keybase restart, the error comes back

**Comment by maxtaco** [comment]
thanks for the report

cc: @strib  and @jzila, his KBFS logs shows repeated rekey failures

**Comment by strib** [comment]
Hi @rawkode -- it looks like it's complaining about one of your private, shared folders. (I don't want to say the name publicly, but if you need to know which one, please ask and I'll encrypt it for you.)  It also looks like you reset your account a few days ago.  In that case, it's the _other_ user who needs to log in with one of their devices in order to give you access to that folder.

The error message seems incorrect.  There is definitely an incorrect message coming from KBFS in the logs, but the specific one you cite is coming from the service I think.  @maxtaco, is it possible that the service gets confused when an account has been reset, and a folder is still keyed for the pre-reset keys of the user, so it thinks the user can do a self-rekey?  I think that's why KBFS is confused.

**Comment by rawkode** [comment]
I believe I know what user it is and I've tried removing it, but I don't have permission to (I assume because of the reset)

So I'm not really sure what to do

**Comment by strib** [comment]
You can remove the folder from your view with `rmdir /keybase/private/<user1,user2>`, but I'm not sure whether that will stop the messages or now.

It should go away when that user logs in next.  If you know that person, maybe you can give them a nudge?

**Comment by rawkode** [comment]
Hi @strib, I spoke with the person in question and we took a look at his directories. Unfortunately the directory in question doesn't exist on his side.

I'm happy for my kbfs to be nuked and started afresh, can you help with that? There's nothing I need inside of it

**Comment by strib** [comment]
Ok, I looked into this a little bit.  The shared TLF I'm looking at is keyed for your paper key starting with `artwork march`, and your now-revoked desktop `Dell XPS13 9350`.  It has no keys for the other user, presumably because that user just added devices today according to his/her sigchain.

Looking through the log a bit more, I can see an error/bug that happened after you entered your paper key.  I'll file an internal ticket to investigate more.

In the meantime, I'm happy to reset this folder, but we ask for a signed statement from you authorizing it.  Please run the following command on one of your devices, and substitute the current date and time, and other user name, as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/rawkode,<otheruser> because of a rekey bug."
```

If you want to keep the other user name private, you can then encrypt it just for me (`strib` on Keybase), or you can put it in our shared folder `/keybase/private/rawkode,strib@github`.  Thanks, and sorry for the inconvenience.

**Comment by rawkode** [comment]
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

owEBogFd/pANAwAKAa2L6bn7VSHVActyYgBYixHBMjAxNy0wMS0yNyAwOTozMDog
UGxlYXNlIGNvbXBsZXRlbHkgcmVzZXQgZm9sZGVycyAva2V5YmFzZS9wcml2YXRl
L3Jhd2tvZGUsbmV2c3Rva2VzIGJlY2F1c2Ugb2YgYSByZWtleSBidWcuiQEcBAAB
CgAGBQJYixHBAAoJEK2L6bn7VSHVcQUH/24BEoMLO7HJCHqRhTngB0+PBiWop5Y1
BZpvijnXrGvSLM/EMPEgFozW3myxzGdV+l1zaqs2/a+qkZrP8jtRqcvxvIohl9FG
vWyEjrdl4+QmpdDzmzdERWP2ewk2OT8YT8T/wsnIjJeiN0OWuTY28m7QWRYWyEtb
W9w9z1/OPHYSzQfcj8Xw98g7BDYiYWcVOD1Tq66lT17w76+qAbpZ0LcHIi9KV1u8
ZWHZqIBN9R1vVVnS00aicxny1c/Q9ADBLJWgO/dBHIyi4v42DszfVyntvBvYv+AP
qg0hJQraiK5Qpbfz1ctnJCGNRC+Zplzznzht5+V/uCyFAQhWhS4YfWU=
=G/vx
-----END PGP MESSAGE-----
```

**Comment by rawkode** [comment]
@strib Did I sign the message correctly?

**Comment by strib** [comment]
I'm sorry, I didn't get to this on Friday, and I can't do it from home.  But I've set myself a reminder for tomorrow.

You used `keybase pgp encrypt` instead of just `keybase encrypt`, which should be ok but I haven't verified it yet.

**Comment by strib** [comment]
@rawkode: I was about to reset this folder, but when I looked at it today, I saw that over the weekend it's been rekeyed for your new devices.  Can you confirm that everything looks ok with it now?  It looks like maybe adding a new device on Friday triggered a fix.

**Comment by rawkode** [comment]
Hi @strib,

It does seem like that folder has disappeared on my end. There are, however, a bunch of "files before rawkode account reset" that I do not have permissions to `ls`

What happens to those?

**Comment by strib** [comment]
We keep those versions of the folders around in case someone who can still read it wants to copy the old data into the new, fresh version of the folder.  Since you're the one who reset your account, you can't read any of the private ones, but if there's a public folder in that state you can recover the data in it, if you want.  If the private folders are shared with other people, you can ask those people to recover the data.

If you don't want to see those folders any more, you can choose to "Ignore" them in the GUI, or use `rmdir` on them from the command line.

**Comment by rawkode** [comment]
Ignoring seems like a bit of a kludge?

**Comment by strib** [comment]
As per our explanation above, we keep them around so data is recoverable after an account reset.  Not sure what a better answer would be than letting you dismiss them once you decide you're done with them.  But open to suggestions.

If you think this issue is finished, please close it out, thanks!

**Comment by rawkode** [comment]
Hi @strib,

Thanks for your help, it's really appreciated.

I believe the confusion comes from an account reset not really being a reset at all. All my followers and followees disappear, but device names and fs persisted, which shouldn't happen. There should be a warning "DELETE MEANS DELETE" and just let the user do as they ask, IMO.

The OCD part of my programming brain will go crazy with those directories being "ignored", perhaps I should just delete my account and start again, properly :+1: 

Thanks again :smile: 
David

**Comment by cjb** [comment]
> perhaps I should just delete my account and start again

Please don't do that!  We don't allow device name reuse *or* account name reuse at the moment.

**Comment by Zenexer** [comment]
Can we reopen this?  It seems to be more than just an incorrect error message.  I'm completely unable to access affected folders/chats until I rekey each time I start Keybase.  I can confirm this started when I revoked one of my devices.

**Comment by strib** [comment]
@Zenexer: please open a new issue, and if you can, do a `keybase log send` so we can see what's going on.  We need to handle this kind of error on a case-by-case basis.
