### ISSUE TITLE
Files need to be rekeyed

### ISSUE THREAD

**Issue by fearoffish** [keybase/client#5534]
I have a private folder shared with another user, and neither of us can access it. I'm not sure how I got my install to this state (nor is he) but we did get the option to rekey, and after doing this (yesterday) nothing has changed.

I thought we could maybe just delete it and start again, but of course that's impossible.

How do we 'reset' this folder?  Pardon my ignorance.

Log id: 51ec89f03f65f5d9c691ed1c

**Comment by strib** [comment]
Would you mind doing a `keybase log send` and reporting the log ID here, so we can check it out please?  Thanks!

**Comment by fearoffish** [comment]
If I try and send him a chat message, I get the following error too:

```
ERROR completing TLF name error: MD with revision=21 not initialized
```

**Comment by 7hunderbird** [comment]
Log id: eb312586cdbeabc90a99fd1c as the other side of this communication.  Hello... it's me...

**Comment by strib** [comment]
Looks like the folder is in a pretty rough state.  It looks like it is only encrypted for these devices, all of which are revoked:

* `fearoffish`: `MacBook13`
* `7hunderbird`: `dancehood` (paper key)
* `7hunderbird`: `snw-laptop`

I guess what happened is `fearoffish` revoked devices back in July and added new ones in November, and `7hunderbird` revoked them earlier this month.  In between, `7hunderbird` never ran KBFS, and so the folder never got rekeyed for `fearoffish`'s new devices.  And now that `7hunderbird`'s devices are revoked too, there's nothing left that can do the rekey.

Unless one of you has the secret encryption key backed up somewhere for one of those devices, there's probably no way to save the data in that folder (even then, it would be tough).  Since July we have gotten better about letting you know that you're about to lose data when you revoke your last device, but we know there's still more work to do on that front.

However, if you don't mind losing the data in that folder, I can reset it for you.  But I need a signed statement from one of you saying it's ok.  Please run the following command on one of your devices, and substitute the current date and time as indicated:

```keybase sign -m "<DATE_AND_TIME>: Please completely reset folder /keybase/private/fearoffish,7hunderbird because all the devices that can read it are revoked."
```

and post the output here.  Thanks!

**Comment by 7hunderbird** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsDWe4TW URBhQvoUwlQqeIE CuE4gOE3hzWWFL6 0zkqGYE6O9Rk6En TbR16IMnDqcLWZe aI0usdKhzag2da5 VnfwwAOBHeAJk0k Yh4LAjhCXUszsHh aI0Xh8lvW0YLvKU LsUQCRQbAUkzURQ uNKSG2Ax4wHTiUm 07tQdVcKzhbs3Bi SgpBxgzUt0ZtaBF rNlkKO2VbByG12h 9H0doHfD2DHfxvl 28AS7dBWLTQTUAE SDVSmbWfBwEksAP 1mMwCIjJwjyK8m5 r9guDCnSRUKIXg9 4NKrTgovIY9Heuy hdkkijTmlNjrgSp MR3LCIHzkOwCUzR XItX0xr7hANn2xu BVmr2ceF9oWiXv0 Ews4J9r6e8mYyDy O1Sv34qKFgNQhK9 J29jHe4uRahxgEH lbJGf2NNfJ94WKw cRuj0CAZs3thaqP vmqPVhkQOfoT3R3 0z7jHBg. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok, I've reset that folder.  You should be able to write in there and chat with each other now.  Please close this out if it seems fixed.  Sorry for the inconvenience!

**Comment by fearoffish** [comment]
Looks good to me, thanks! No need to apologise, we're still testing :)
