### ISSUE TITLE
KBFS I/O Errors Preventing File Deletion

### ISSUE THREAD

**Issue by Saklad5** [keybase/client#5660]
I’ve been using rsync to maintain an encrypted mirror of a folder using KBFS. This worked for months, but now there are two files that cannot be deleted by any means. Finder returns Error -36, `rm` also runs into I/O errors, and so on. Even writing /dev/zero to these files doesn’t work.

If you could reset my KBFS private folder while this bug gets fixed, that’d be fine. As I said, I’m only using it as a mirror for other files. It is an alpha, after all.

**Comment by strib** [comment]
Oh no!  We can certainly reset it, but there might be other options. Are you willing to do a `keybase log send` and share the resulting ID here so we can try to figure out what's going on?

**Comment by Saklad5** [comment]
https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20c43d550b5d5021efeb47331c

**Comment by strib** [comment]
Hi @Saklad5 -- thanks for the log.  The good news is that it doesn't look like data is corrupt or anything.

The bad news is that it seems you've used up your 10GB quota.  When that happens, we do two things: 1) show you pop-up notifications to let you know (though maybe you've turned off notifications from Keybase so you haven't seen those), and 2) slow down your writes.  At this point, your writes have been slowed down so much that it's causing timeouts whenever you try to write data.  We don't completely fail writes, so you have been able to get a lot through, at a much slower rate -- you're using almost 20GB of space now actually.

Most of the data are probably not currently visible to you -- they are probably old versions of files that have been deleted.  Because of end-to-end encryption, we rely on a background process in the client to clean up old deleted data.  However, in the current release, there is a bug that causes this to happen 80% more slowly than it is supposed to.  So I think you're client hasn't gotten around to cleaning up most of the old, deleted data.  This will be fixed in our next public release.

In the meantime, we can provide you with more quota.  I've put a file at `/keybase/private/saklad5,strib/updating_your_quota.txt` with instructions on how to do this.  Let me know if that fixes the issue for you.  Sorry for the inconvenience.

**Comment by Saklad5** [comment]
Keybase was sending notifications every time I added a file or removed a file, so I turned that off. If there was an option to disable activity notifications like that, I’d gladly turn push notifications back on for Keybase.

If you’re sure it's okay, I’ll follow those instructions. I don’t want to impose, so feel free to remove that quota increase as you see fit. Thanks.

Also, the quantity of deleted files probably has a lot to do with my use of `rsync` and a launchd agent. If this is troublesome for your servers, I’d be happy to stop using it.

**Comment by strib** [comment]
> Keybase was sending notifications every time I added a file or removed a file, so I turned that off. If there was an option to disable activity notifications like that, I’d gladly turn push notifications back on for Keybase.

Understood.  We are definitely erring on the side of being chatty right now while people are learning about the product.  This will probably change in the future.  There's currently no way to selectively turn off file notifications, sorry.

> If you’re sure it's okay, I’ll follow those instructions. I don’t want to impose, so feel free to remove that quota increase as you see fit. Thanks.

No problem, it's our bug, you shouldn't have to suffer.  Go for it, just please don't share with anyone else without first checking with us.

> Also, the quantity of deleted files probably has a lot to do with my use of rsync and a launchd agent. If this is troublesome for your servers, I’d be happy to stop using it.

Nope, no trouble on our end!

**Comment by strib** [comment]
I believe we're improved things in terms of speeding up freeing old data.  Please open a new issue if you see more problems in this area.

**Comment by Saklad5** [comment]
Would you like me to suspend the quota increase?

**Comment by strib** [comment]
Thanks for offering, but it's ok with me if you keep it as is, in recompense for the bad experience.
