### ISSUE TITLE
Issue with broken shared private folder billinghamj,duffleman

### ISSUE THREAD

**Issue by billinghamj** [keybase/client#5708]
Keybase GUI Version: 1.0.18-20170131120020+3f505f9

Log ID: 0854b32c2d906875caaf9b1c

We both (billinghamj & duffleman) had used Keybase a while back but deleted it due to instability issues. We both set it up again today, but had to revoke and recreate our laptop devices and paper keys.

Then we tried to use our shared folder, but it complained about needing to be rekeyed. As neither of us have our original paper keys or devices available, we weren't able to do this.

There wasn't anything of value in the folder. Please could you just clear/delete all KBFS data for both of us so we can get it working again?

**Comment by strib** [comment]
Sorry for not getting to this earlier today, it was a busy day!

I can reset the folder for you tomorrow, but we'd like a signed statement from one of your current devices giving us permission.  Please run this command, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folders /keybase/private/billinghamj,duffleman because all the devices that have access have been revoked."
```

and post the results here.

**Comment by billinghamj** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrwREOQ0 ePnLKcTZUIbWE2s VZJldygOJsPWigF G63FdGgnQsAPDrq OQXicEK0gIbcLQx GtpCBoZ1ERfi9at FWVGW8rII68pNv5 HKaL2mkglcoC5uU SblHnCcJbtw7xpe qxia5EcSkeexhHE tXgPjT3wlPoeBeg l7hm3KxMKv95m3S JDxO9yrfDUzwpoJ qmhtLNym8qH9bGJ ihi1VdaGUwBvzKb ySDcIKVXjmntlrT D9xBEeMG118Ee0D ky0Vb6iNjIPxspV ymzi9sU65IwSElR BPi2KPMPiffaCQP 8ILux5gPyRAfPxJ 8iVcpfWYYGU86yO kcEVTqnoSWzGjxz sP8ZwRqGkO4nXyF vPuW5cwXicPLbkU UvuGnpz0fX48qMP fvXGEUYAQ3W3fYd tJ4VsmJD5KTHMUW wdDEstCb6W9FF3T qc17VsgE0Lw. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by billinghamj** [comment]
It may be worth building in an option to delete the folder when rekeying is not possible btw

**Comment by strib** [comment]
Ok the folder should be reset now.  Can you please close this out if things look ok?

It would be nice to have that option, but it's probably low on the list of priorities.  Hopefully it will be rare that people revoke their paper keys!  Also, if you completely reset your account and start from scratch, we automatically reset folders for you.

**Comment by billinghamj** [comment]
Perfect - thank you! :)

**Comment by Duffleman** [comment]
@strib 

keybase sign -m "2017-02-08 18:50:00: Please reset folders /keybase/private/duffleman because all the devices that have access have been revoked."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsByn4cm 9FuDikBsqDYzW3p WghRsHAPkLF1z71 viGsZSTLDFZ2Q8v R8Dg7bZUf3vQV6f oCsqciqs996uA8A yLWcGyV8OdhSqCJ eP4YKTbs1YCys5L UIfG7iV5wVDKskg Swe5jpaA80CKSl8 u4X4A8UZSlzBaIL EdJ2MykRbLnT89c rXO7kB53Ltp7drW TcpsiO2VbByGCPC MOpuQKDVGkySiPd EutlcGbJmHaJbIb 1HyN6mvldIjyVS0 pedCR4U3q4o6ZSV IGwK7NrCiU4eL6A 9S4tswWu0K2m4Pg RgRIFm7FM0l1Qcs vleS4Oae5LengE7 h2JNxC7BUNJGPBz bWWHZHU3xMZbuNu lLDT3wq5MeE1n6k sCKC1QXVjzxnf3t MY4o5vAdyuCdTfH kPvngWW3dw39wxn povkPqTzZmyNk0. END KEYBASE SALTPACK SIGNED MESSAGE.

Could you reset my own private folder as well please?

**Comment by strib** [comment]
@Duffleman: done.
