### ISSUE TITLE
Ignore folder does not stay after reboot

### ISSUE THREAD

**Issue by aroblu94** [keybase/client#5976]
Every time I power on my pc I get notified for a public folder I ignored.
It seems to affect only my netbook (ubuntu 16.10). On my two others PCs running Windows 10 and Ubuntu 16.10 (as the laptop) it works.

**Comment by strib** [comment]
Hi @aroblu94, thanks for the report.  Usually this happens because something on your device has that folder (or a file in that folder) in its recent files list, and checks if it's still there occasionally, which triggers the tracker popup.

If you can't figure out which application is causing it (the application PID will be in the KBFS logs, I can take a look for you if you want to do a `keybase log send`), then the best workaround is to track that user.  If you don't want to track them publicly, you can track them locally just on that machine with `keybase track -l <user>`.

**Comment by aroblu94** [comment]
@strib ok, i cleaned recent files and it worked, thanks!
