### ISSUE TITLE
Can't delete user's public folder from Finder on MacOS

### ISSUE THREAD

**Issue by greinacker** [keybase/client#6057]
When I browse to the public folder in the Finder, and right-click on a folder and Move to Trash, I get an error message:

"The operation can't be completed because you don't have permission to access some of the items."

I can, however, remove the folder from the terminal by doing

rmdir /keybase/public/{username}

**Comment by strib** [comment]
That's intended behavior.  If you were able to drag it into the trash, you would be actually deleting the files inside of it from KBFS, which is not allowed since you're not the writer.  `rmdir` is the supported way of removing it.  (Or ignoring it via the Keybase GUI.)

**Comment by greinacker** [comment]
Fair enough - the current behavior isn't super friendly, though, IMHO.  Especially since as I'm playing with public chat, I get peoples' public folders showing up that I didn't expect to see...

**Comment by strib** [comment]
Right, that's a separate issue that we'll work on soon -- viewing a chat shouldn't cause the folder to show up in your KBFS favorites list.

At the file system level, we can't really support the delete behavior you want, because when macOS goes to remove a folder, it first tries to remove everything inside it, which can't work if you're not the writer.
