### ISSUE TITLE
Keybase file system is inaccessible...

### ISSUE THREAD

**Issue by adamtait** [keybase/client#6068]
Here are the results of some of my attempts to access files contained within my private kbfs.

```
❯ ll
gls: cannot open directory .: No such file or directory
```
```
❯ cd /keybase/private
cd: permission denied: /keybase/private
```
```
❯ cd /keybase
cd: no such file or directory: /keybase
```

I've tried sending logs using `keybase log send` but have gotten this error more than 5 times (none succeeded):
```
▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

This has gotten me a little worried. Although I'm aware of the alpha status of kbfs, I'd like my data back.

**Comment by maxtaco** [comment]
We're getting bit by the S3 outage

**Comment by adamtait** [comment]
My issues sound very similar to those reported in #6067, though I'm running OSX 10.12.3

**Comment by adamtait** [comment]
Ah great! Thanks @maxtaco - I didn't realize there was an S3 outage or that Keybase was running there.
I'll track it on AWS and close this issue.

**Comment by fdovila** [comment]
:( 
It would be nice to let your users know about this kind of connectivity issues, so we do not think it's a local issue and throw our machines by the window.

**Comment by cjb** [comment]
@fdovila Honest question -- where would have been a good place to tell you about the AWS issue?  Would it have to be inside the app itself?

**Comment by fdovila** [comment]
@cjb inside the app, via a notification bubble:
"we are experiencing some connectivity issues", "our servers are down", come back later and pray...

Also at the moment of sending the issue via terminal... it would be nice to get a more insightful error message. 
I wouldn't guess "all your servers belong to AWS". In my very noob opinion, wouldn't be better to have an independent non-AWS server to collect the log-reports and disseminate the status of the service?

**Comment by cjb** [comment]
> inside the app, via a notification bubble

Thanks, sounds like a good idea, can't promise we'll get to it soon.

> In my very noob opinion, wouldn't be better to have an independent non-AWS server to collect the log-reports and disseminate the status of the service?

I'm not sure whether you mean independent for security reasons or availability reasons, so I'll answer both:

* Security: We don't write anything sensitive (like passwords, chat messages, contents of files) to our logs.  Our servers already know who you're talking to, and our servers are on AWS, so having that data also in log files stored on AWS doesn't add any security problem that wasn't there before.

* Availability: We think it wouldn't make sense to pretend that we can run a service with higher availability than Amazon is able to, so that's why we don't collect log reports on a non-AWS service for availability reasons.

It would be good to have a status page that isn't on AWS, but I think most people wouldn't know where to look for it, so we should probably just use the @KeybaseIO twitter account for big outages for now.
