### ISSUE TITLE
Please sign all releases & downloads

### ISSUE THREAD

**Issue by jonathancross** [keybase/client#6393]
Hi, I noticed that [releases here in Github](https://github.com/keybase/client/releases) and [downloads on your website](https://keybase.io/download) do not provide PGP signatures that can be used to verify the authenticity / integrity of what users are downloading.  This is common practice for software such as this, please consider implementing as part of each release.

**Comment by cjb** [comment]
Our Mac and Windows downloads are signed our with Apple/Microsoft developer keys, and we only serve downloads over HTTPS.  GPG signatures wouldn't add much practical benefit, since someone who can lie about TLS would just lie about the signing key too.

**Comment by jonathancross** [comment]
Thanks for the reply Chris.  The benefit of signing both tagged releases / commits **_and_** binaries, is that we can independently establish that _"the key that signed the binaries on keybase.io"_ is the same as _"the key controlled by the project maintainer on GitHub"_.  This is actually a very useful guarantee (especially if that key is then used to prove other identities via keybase itself).

At the very least, providing SHA-256 digest in both locations would help.

Keybase is a fantastic project with the potential to become the foundation for many forms of secure communication & identity. As a security tool, it should use these well established systems for establishing integrity.

Cheers!

**Comment by junderw** [comment]
> GPG signatures wouldn't add much practical benefit, since someone who can lie about TLS would just lie about the signing key too.

I can verify your fingerprint independently though.

**Comment by luehring** [comment]
I guess this ~6 year old thread is defunct but I'd like to comment.

I am just starting with Keybase because I am associated with an organization that is using it communicate files securely. Your response about getting no practical benefit from signing disagrees with what all other open source security-related projects that I use say and do. All of them sign both install images and source code. They all provide fingerprints too. I would really prefer you to sign with your own keys and not trust outside organizations even Apple and Microsoft. I expect the project and not some 3rd party to provide me with the means to tell that I am getting the correct software. This is @junderw is saying.  

As for HTTPS, the reason for using HTTPS is to keep the content exchanged between the client & server and not to guarantee that the correct content is being downloaded. Certainly using HTTPS is to hide from prying eyes that Keybase is being installed on a workstation or server is the correct thing to do but it's not relevant to the issue raised by @jonathancross.

**Comment by jonathancross** [comment]
I just saw that they started signing releases:
```
gpg --verify keybase-v6.4.0.tar.xz.sig
gpg: assuming signed data in 'keybase-v6.4.0.tar.xz'
gpg: Signature made Wed 21 Aug 2024 06:50:51 PM WEST
gpg:                using RSA key 222B85B0F90BE2D24CFEB93F47484E50656D16C7
gpg: Good signature from "Keybase.io Code Signing (v1) <code@keybase.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 222B 85B0 F90B E2D2 4CFE  B93F 4748 4E50 656D 16C7
```
