### ISSUE TITLE
GTK popup from `keybase login` won't accept pastes?

### ISSUE THREAD

**Issue by ketzacoatl** [keybase/client#6445]
When I run `keybase login` on linux, I get a GTK popup asking for my passphrase. I have a very, very long passphrase, and when I try to paste it into the window, the GTK window doesn't seem to accept the paste. I can type in the dialog, but it will not accept any paste. Is this by design, or is there potentially another problem?

**Comment by cjb** [comment]
It sounds like you're not running our GUI (if you installed from our site then `run_keybase` should start it), which would give you a separate popup that does allow pastes. Your system is probably falling back to some gpg pinentry app, and some of those disallow pastes, I suppose by design (once your password is on the clipboard then any other X app you were running could see it).

**Comment by ketzacoatl** [comment]
I did skip `run_keybase`, and instead ran `keybase login` directly (which started/forked the `keybase` daemon). OK, so `run_keybase` is required? Is there a way to use keybase without all the fluff? I don't want a daemon running, I only want `keybase` running when I invoke it (sorry, but I have minimal trust for keybase, and I don't want it running on startup or stuff like that).

**Comment by ketzacoatl** [comment]
You are right, I can paste when using `run_keybase` and the associated gui.
