### ISSUE TITLE
Unable to open KBFS folders on mac

### ISSUE THREAD

**Issue by TechMaz** [keybase/client#6457]
When I try to access the KBFS folders, the drive keeps mounting and unmounting repeatedly and my Keybase app freezes, showing only a white screen when I navigate to the folders through the app.
Please help!

<img width="980" alt="screen shot 2017-03-31 at 4 49 20 pm" src="https://cloud.githubusercontent.com/assets/2186709/24572930/01c54e0a-1632-11e7-8e1e-3139cd4c6533.png">

**Comment by cjb** [comment]
Sorry for the trouble. Please could you run `keybase log send` in a terminal and tell us the ID?

**Comment by TechMaz** [comment]
Thanks for your quick response. I just enabled the logs as you said. Also I looked into system logs and found these:
<img width="1289" alt="screen shot 2017-03-31 at 4 51 31 pm" src="https://cloud.githubusercontent.com/assets/2186709/24572961/702f8c2a-1632-11e7-9675-258701748ff6.png">

**Comment by cjb** [comment]
CC @gabriel @strib

I don't see anything bad in the logs. :( The GUI's BrowserWindow is crashing but I don't know why. Did you happen to try rebooting the machine? Would be curious if that fixes it.

**Comment by TechMaz** [comment]
I've rebooted a couple times and it has the same issue. The first time I logged into keybase it seemed to work and I dragged files into the public folder, but they never uploaded even though they showed up in the folder. Every time after that however, the blank screen issue occurred.

**Comment by strib** [comment]
Hi @TechMaz -- sorry about this!  You hit a known rare bug in KBFS that will be fixed in the next version.  Basically, you've wrote a bunch of stuff locally to your public folder, but it was never flushed out to our servers, and now it's stuck in a state where it will never fix itself.

You'll need to fix it by wiping out all the local state for that directory.  If you have put anything in there that you want to save, you'll need to copy it somewhere safe first.  So follow these steps from a terminal:

1. `mkdir ~/kbfs_public_tmp && cp -r  /keybase/public/techmaz/* ~/kbfs_public_tmp/`
2. Completely quit Keybase so that it doesn't show up in your task bar anymore.
3. `mv "/Users/steven/Library/Application Support/Keybase/kbfs_journal/v1/0120e8cc68352582cb33c1354e455d21dadf-86499f26d8210727" /tmp/saved_kbfs_public_journal_dir`
4. Restart Keybase.
5. `cp -r ~/kbfs_public_tmp/* /keybase/public/techmaz/`

Let us know if that fixes it for you.  Sorry for the trouble!

**Comment by strib** [comment]
(After everything finishes and if it looks ok, you can clean up with `rm -rf ~/kbfs_public_tmp`.)

**Comment by TechMaz** [comment]
Thanks, that seems to have fixed it! I had already deleted files from that directory so there was nothing to save anyways.

Thanks again for your fast response!
