### ISSUE TITLE
Can't add files to /keybase/private/[my username]/*

### ISSUE THREAD

**Issue by Poeticode** [keybase/client#6516]
I think I tried adding and deleting a large file in my private folder a while back, and it rendered the folder unusable. It shows nothing in the private folder, and when I try adding a file, it asks for admin privileges and then claims that the drive is unavailable.

my log id: 30ba994ee5c8a7418a9d7c1c

**Comment by maxtaco** [comment]
Cc: @strib

**Comment by strib** [comment]
Hi @Poeticode, thanks for the report.  I can see from the log that your folder is in a bad state.  When you say "a while back", do you remember exactly when things broke?  If it was a long time ago, this is probably a bug we've already fixed in the latest releases.

If it's been more than two weeks since things broke, I'm a little worried we won't be able to recover the data that was in there.  We can always reset the folder to a clean state so you can continue using KBFS, but I know that's not a very happy answer.

So any more details about when it broke would be much appreciated.  Also, unfortunately, I'm not in the office today, so recovery and resetting might need to wait until tomorrow.

**Comment by Poeticode** [comment]
@strib : Yeah, it was probably months ago. I wouldn't mind for the folder to be reset tomorrow, as I was just testing the kbfs out. I wish I sent a log + issue at the time, but I think I figured it'd probably fix itself upon a reinstall and then eventually forgot about it entirely until now. I'm sorry that I don't have an actual date, or any additional information. :/

**Comment by strib** [comment]
Bummer, well I'm very sorry for the bad experience!  Tomorrow I'll see what I can do about recovery, and if not I can reset it.  But before we mess with people's folders, we need to get a signed statement saying it's ok.

If you want us to reset your folder, please run this command from the Keybase terminal on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/prophesi because it is in an unrecoverable broken state."
```

and post the results here.  (I don't have a Windows machine handy, you might need to do `keybase.exe` instead of `keybase`.)

**Comment by Poeticode** [comment]
> Bumm, well I'm very sorry for the bad experience!

Nah, everything else with Keybase has been smooth. I'll be putting my invites to good use this weekend as I convince a few friends to try out the chat and KBFS.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsC9mJu8 4m7sJwIOq1ZRBkh kJzJPEzdb6enAS8 DmbeLgnNl5bQwvg 8ZdaESdFbvvwfhD qfGbFBqieSuF44E 2yy2mO5xt7GDeLg 7vFWNHerwjdAQ1C 3fUtOsSbvfIcaWE DVo5UWO4jiKw2h5 sr48DFzpX4J0Jnf qmEVUZoj9ERgKRv jix51QEHfwO7WfQ hkBmKJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVknVrXr3 HX2atvmpLlG8ZCj eWiWwM6Fjf8k9T6 XQ75xdtCee2mA30 eAezT2HHmCV7KEh rwQNOG0pyLzlBo2 j07KNMG0CMerW80 N7ezY5j70qDHzdw atD2A8qgu6gjOMa OjvwBOR3dD76Nns cn0lyx0mY5vTpl9 PeU3wX4tVoD3I. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @Poeticode -- I was about to reset your folder when I noticed it had some updates in the last 24 hours.  I can't tell from the servers what is exactly in the updates -- one of your clients may have been able to fix the data (due to something locally cached maybe?), or it may just be some background bookkeeping work that wouldn't affect the data in the folder.

Before I reset, can you please double-check your private folder one more time, and just make sure it's still broken?  Thanks!

**Comment by Poeticode** [comment]
@strib : Yep! The private folder is still broken. I tried adding a text file earlier to see if it was reset already, which I'm guessing is what set off the update. Sorry about that.

**Comment by strib** [comment]
Ok, thanks for checking.  I just reset the folder.  Can you check it out and close this if things look ok?  Thanks and sorry again for the messed up folder.

**Comment by Poeticode** [comment]
It seems that the folder is still messed up. This time Keybase gives a read timeout when I attempt to open the folder, while Windows says "Error 0x800705AA: Insufficient system resources exist to complete the requested service."

**Comment by strib** [comment]
Hrm, can you please do a new `keybase log send`?  Also, after you do that, it might make sense to try restarting KBFS/Keybase, to see if that helps.

**Comment by Poeticode** [comment]
Ah whoops, meant to include my newest log.
Log id: 8837c0c3eb4abb338ce2561c

**Comment by Poeticode** [comment]
Now it seems to work properly after a restart. Which is a bit odd, considering I had booted up this PC long after the folder was reset.

**Comment by strib** [comment]
Weird!  The only error I see in the log is an expected one for when the OS tries to create "desktop.ini":

```
2017-04-07T19:19:51.027346-04:00 - [DEBU kbfs fs.go:565] 106 => FS CreateFile [tags:DID=pfbqDUiIk0tGwJoteT6z0Q]
2017-04-07T19:19:51.027346-04:00 - [DEBU kbfs fs.go:275] 107 open: []string{"private", "prophesi", "desktop.ini"} [tags:DID=pfbqDUiIk0tGwJoteT6z0Q]
...
2017-04-07T19:20:01.311637-04:00 - [DEBU kbfs tlf.go:33] 160 TLF prophesi does not exist, so pretending it's empty [tags:DID=pfbqDUiIk0tGwJoteT6z0Q]
2017-04-07T19:20:01.311637-04:00 - [DEBU kbfs dir.go:124] 161 Request complete [tags:DID=pfbqDUiIk0tGwJoteT6z0Q]
2017-04-07T19:20:01.311637-04:00 - [DEBU kbfs folderlist.go:56] 162 NTSTATUS=c0000034 [tags:DID=pfbqDUiIk0tGwJoteT6z0Q]
```
This is a hardcoded error in KBFS, but I think it's normal and I'm not sure why it would result in a user error.  Maybe @taruti or @zanderz would know?

Glad it's working now though!
