### ISSUE TITLE
rekey folder

### ISSUE THREAD

**Issue by crushingbear** [keybase/client#6554]
Unable to use my private folder as it says that it files need to be rekeyed?  I have tried uninstalling and re-installing keybase.

my log id: d769c883de4b75fa9495f21c

**Comment by cjb** [comment]
CC @strib, want to take a look?

@crushingbear Did you try doing the rekey, do you have access to your paper key?

**Comment by strib** [comment]
Hi @crushingbear -- it seems that yesterday you revoked all the devices that had access to this folder (presumably because you lost/reset `Surface` and you lost your paper key, and just realized it?).  We don't have any way to recover what's in there (it doesn't look like there was much yet), but we still need to your signed permission to reset it to a blank state.

If you want us to reset your folder, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/jacobegly because all the devices that have access have been revoked."
```

and post the results here.

**Comment by strib** [comment]
@crushingbear provided me a signed statement offline.  This folder is reset, please close out this issue if everything looks ok to you.
