### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by fkabs** [keybase/client#7144]
Dear devs/admins,

can someone reset my private folder "/keybase/private/fkabs" please?

I've resetted my keys and have started from scratch, now I don't have access on my private folder anymore.

I've also submitted the corresponding log-file (id below), I hope this helps you out.

Thanks in advance!

Cheers

my log id: 3c1a75a4d8b829a05a38601c

**Comment by strib** [comment]
Hi @fkabs, thanks for the report.  When you reset your Keybase account, we move your old folders out of the way, to a new name.  For example, your old private folder is now `/keybase/private/fkabs (files before account reset 2017-05-25)`.  However, your new, post-reset devices won't be able to read it.  It's possible that if you still have an explorer window or shell open that had navigated to your private folder before you reset, it will still look like you're in your private folder.  In the log, it seems like you're trying to access that old folder, rather than the new one. Can you try navigating to your folder again from the k: drive and see if you are still having problems?  On Windows, a Keybase restart might help as well.

If you're still having issues, please let me know and send new logs, and I'll take a closer look.

**Comment by fkabs** [comment]
@strib sorry for my really late reply
it's working now as desired, thank you sir!
