### ISSUE TITLE
Can't use username of already deleted account

### ISSUE THREAD

**Issue by fruchtmord** [keybase/client#7190]
Yesterday I created a Keybase Account and deleted it a bit later.... Today I can't created a new account with the same username.

When I try to create the account I get the error : "username already taken"
When I try to "reset" the "old" account I get (obviously) the error: "Server failure: user deleted"

**Comment by cjb** [comment]
Hi, sorry to say that this is intentional.  It would confuse people to have deleted accounts reappear (especially if it was owned by someone else).

**Comment by fruchtmord** [comment]
It's my account :D the "old"

**Comment by fruchtmord** [comment]
and I would like to use my "old" username

**Comment by cjb** [comment]
I'm afraid it's still not possible.  :/

**Comment by fruchtmord** [comment]
Ok, thank you....

Keybase has no support email am I right?

**Comment by ype** [comment]
@cjb I am experiencing the same issue as fruchtmord. 

Although it is not possible to regain deleted usernames at present, do you know if this feature will be implemented in the future?

**Comment by fmartingr** [comment]
I have the same issue as @fruchtmord and @ype. Can this be done manually for users that want to regain control of their own accounts?

**Comment by shelhezan** [comment]
I'd like to queue like @fruchtmord, @ype and @fmartingr.

**Comment by ryanpcmcquen** [comment]
I'd like to recover the account I deleted, is this impossible?

**Comment by odarriba** [comment]
I'm on the same situation. I created @odarriba user long time ago, and closed it later on. Now I cannot create one using the same username. Any chance of recovering or freeing the user handler?

**Comment by maxtaco** [comment]
We don’t have the bandwidth right now to implement this feature. Pick a new
name is the best we can offer.

**Comment by sebastianbauer** [comment]
@maxtaco To recover an account you are being asked for email or username. I understand that by username this should not be possible without the apprpriate keys. Recovering via email address should be verification enough. I really want this first username back and can't. Doesn't sound like an very big issue.

**Comment by maxtaco** [comment]
We can reset accounts, and do so all the time. We just can't undelete deleted accounts

**Comment by odarriba** [comment]
But is there any real chance of being able to recover a username (with the same email address as the first time), or it is completely out of the plan (because you don't want to give that possibility for security reasons)?

Thanks for answering, it's really appreciated :heart:

**Comment by maxtaco** [comment]
Sorry @odarriba, there's probably a way to do it with the right security guarantees, but it's pretty buried in our todo list.

**Comment by ryanpcmcquen** [comment]
@maxtaco, thank you for the response. It would be great to see this functionality. It'd also be great to be able to reuse device names.

**Comment by odarriba** [comment]
Thanks for the response @maxtaco , that's really appreciated.

Regarding this: 

> We can reset accounts, and do so all the time. We just can't undelete deleted accounts.

Do you mean you can reset my (previously deleted) account with no data on it? I don't really care about the keys that were there or the verifications done, I just one to have the same handler on every place.

Thanks a lot and best regards ❤️

**Comment by fmartingr** [comment]
I'm on the same spot as @odarriba, want the handle just don't care about the current data on the account, if that means I can recover the username please ping me out too :)

**Comment by dschense** [comment]
For me it's the same. Just want my old username back. ;-)

**Comment by sebastianbauer** [comment]
Seems there are some users that really want to use Keybase but (accidentally) deleted their account. Maybe you can offer some manual way in such case. I still have the initial welcome mails and everything. Just don't get the chance to re-use my username. :-(

**Comment by tracphil** [comment]
Same here. I deleted mine a few years ago and still have all my proofs, I don't recall a message saying once deleted you can never recreate it again. That would be a nice warning for others if it hasn't already been implemented.

**Comment by petrsnm** [comment]
Same problem.  I deleted my account to "clean-up" after testing adding various devices.  No warning that I'd never be able to re-create.  Now I can't get my old username back.  Really wish I could. 

Any estimate for when this can be fixed?

**Comment by robert-i-greathouse** [comment]
I agree with petrsnm. It wasn't clear that i wouldn't be able to use the same username after i deleted the account to do some testing. Also, why do you limit usernames to 16 characters?

**Comment by robert-i-greathouse** [comment]
This is still a stupid restriction. It's not confusing as we could validate with the attached keys.

**Comment by TigerC10** [comment]
> Hi, sorry to say that this is intentional. It would confuse people to have deleted accounts reappear (especially if it was owned by someone else).

> We can reset accounts, and do so all the time. We just can't undelete deleted accounts

Well, I guess I'm deleting Keybase and never recommending it to anyone.


I, too, deleted my user account because the reset didn't do what I expected it to do.  App NEVER mentioned that my username would forever be unusable after deletion.  Literally no other app on the web else has this behavior - you should make that ULTRA clear in the screens before deletion.

**Comment by chindraba-work** [comment]
I've always thought the warning was extremely clear. It even uses red text on the button as opposed to the standard color of _every other_ button in app.
The text reads:

> This can not be undone. You won't be able to create a new account with the same username.

Nothing is said about a manual override being available, or any other work-arounds to that limitation.

As for the "no other app on the web has this behavior," one could also say "no other app on the web has the security of Keybase either."

As a user, if I encountered a use @krisnova on Keybase, verified the proofs, and accepted them, I would be extremely suspicious of another @krisnova after I was notified the the account had been deleted. Enough so that I wouldn't even bother to check the proofs; I'd just block that account if any contact was attempted.

Good security is not always ultra-convenient, and the protocols have to be consistent, and absolute. Keybase does make it a lot easier to have good security, yet it cannot be capricious in the application of the rules or its security would end up being no better than Facebook.

**Comment by petrsnm** [comment]
Perhaps someone should write a bot that burns all the names

--
Matt

________________________________
