### ISSUE TITLE
rekey/delete private folder

### ISSUE THREAD

**Issue by koaxed** [keybase/client#7304]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

hello,

can you please rekey/delete my private folder under /keybase/koaxed/private?

-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.71
Comment: https://keybase.io/crypto

wsBcBAABCgAGBQJZN29aAAoJEHH4LiivGXjHmeAH/3zc8uhyjyTHoHrOdUOj5BJH
h4Q7ahTNbM0nd008JUf4/qbQU8fPTGzceDHVrVx7NBnaXcQ8z/QCeZGhnh4OUQfE
MBJ8eLRQZg/x8fltUlSrtUswMEA/u4DJCsfWnlfUSHYJYuuJR92LIw0vlbRumzBU
9y35I3DsGynL5hi8jtw1+1FkLtqJrnRmP67mrZLVE7LdZLVIcFoiaGsfWv7x0VO+
TRH3UElvdCqoC8zKBEvIaK5kfCQjJ6xbRUZ2uzy/VaUFdZFchnwEomdKro5d4moJ
Vfz+ByV7Kq8NdTAv8ZOXeIPkDtD/dI8RjlELWzuNI8/oQAKzXy2S1gnyxekoa9U=
=HAab
-----END PGP SIGNATURE-----

**Comment by strib** [comment]
Hi @koaxed, the PGP isn't checking out for me, for some reason.  Also, we prefer if you specify a reason for why you need it reset.  Maybe it's because you revoked all devices, including paper keys, that had access?  If so, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/koaxed because all the devices that have access have been revoked."
```

and post the results here.

**Comment by koaxed** [comment]
hi @strib,

I revoked the original device (laptop) and my paper key as well as I had lost the key for it. 

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs7WATKZ 1VTmJrUi3bvEI4P kt86PYTqsdVMQmh 5LhEB8gUCHBVYJl IHO0G8uTrrzeiw0 t70pYBfbAkuz28F OjnIrnqoyIB2gkS 5b92UFmBt5Cco6F THkvCrDE8rWlIi7 pdwXOsFfVN20uwY a1z2tPZUTOZ1OlK xx2PvNixj0FyLRE hF24KNJ7Ol2dv5G rJn0bRMY7R6Xr7X ONhZ7bZdQ8GhL5Z HSbg80GkE90ogX5 spBBFAUFMYiNULK tGtsQPljT5TgEoZ o8LIuuxbNRbVBGy WRbREgiXJcu0plM 8zLW83dcBJD9edf WqnileyudUePPvO 2fK7zGgkdEfemnB qVyRgWlBXaDEE66 5tBU7l0r8FlO7JE IVvsFJghezr8ArF PhvH2SpkCuGNolr ZBBuKiIbQUFulh8 1y6PmC. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @koaxed, sorry for the delay.  I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by koaxed** [comment]
hi @strib - I'm receiving an error when accessing the private folder that says "keybase - user not found. folder is not a keybase user".

**Comment by strib** [comment]
@koaxed: what exactly are you doing when you get that error?  Seems like you're trying to navigate to the wrong path.

**Comment by koaxed** [comment]
@strib I'm trying to access the path through Nautilus. Which apprears to be the default method

**Comment by strib** [comment]
Sorry, that's not enough info for me to understand.  Do you get the error when you double click on the "keybase" folder icon in your root directory?  Or are you typing something into nautilus finder?  Or clicking on a folder in the Keybase GUI?

If you want to look further, you can do a `keybase log send` and post the ID here, and I can take a look tomorrow.

**Comment by koaxed** [comment]
@strib inside the keybase app itself. When I click Folders - Private - Open Folder. The location opens up in dolphin, although I receive a system notification with the  message I provided above.  Functionality appears to be working though.  

log ID: b65732e1b04622d6d364d71c

Thanks

**Comment by strib** [comment]
Ah I see, thanks.  It looks like something on your system (process ID 2966) is trying to look up `/keybase/private/folder`.  Maybe it's a Dolphin thing.  We're showing that message to let you know you're making a mistake, because we can't tell the difference between you looking up that folder and some application on your system doing it.

I'll add an exception to the code for the name "folder" so it doesn't show that popup anymore.  Sorry for the inconvenience, but glad everything is working ok otherwise.  Can we close out this ticket?

**Comment by koaxed** [comment]
@strib thanks for your help on this. I'd say we're good to close this off.
