### ISSUE TITLE
Broken folder? [bug?]

### ISSUE THREAD

**Issue by iJusty** [keybase/client#7517]
after creating private folder that can viewed only by me and guy that not on keybase,
folder is broken.
with broken folder, now i see rekey window, its annoying for me.
Rekeying not working,
Ignoring folder not working.
Any ideas to fix this?
my log id: a1206709969c4fabc3f2581c

**Comment by strib** [comment]
The folder was written by one of your devices about an hour after that device was revoked, according to the timestamps on our servers:

```
Not trusting revoked verifying key 01207d546f805694a41db8b8226d5965f2632e5d24cb5d412e2b29a9ec1d17ecc3420a for user e141245a42fdee62a386ddb3a2430219 (revoked time: 2017-03-13 07:57:36 +0300 MSK vs. server time 2017-03-13 08:57:46 +0300 MSK, slack=1m0s)
```

It's suspicious to me that the times are off by exactly an hour. It makes me think that at some point, the clocks on the API server and the KBFS MD server were off by an hour.  @maxtaco do you remember anything weird happening with the API server (or DB) clock back in March?

@iJusty: if you want, I can completely nuke that folder for you, so you stop getting the annoying messages.  If you want that, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/<XXX> because all the devices that have access have been revoked."
```

and post the results here.  I didn't fill in the folder name since it has the name of another user you might want to keep private, but you should fill it in yourself.  If you prefer to keep that private, you can put the results in `/keybase/private/idankexe,strib@github`.

**Comment by iJusty** [comment]
Command is executed.
Result:
`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkQiSIQr jdUAOErbfGRyXnR JqW1ULzCzDhKhI2 0JjncTAHTRe9SKI a4cPDjtPXw2KNq2 OSybL0F9AVzq4ld SwzbUjzLFDOlBRS 9mMy9A09cW1YmYc O7QhWifBL6QOWW2 FJpuFrcJkSpcJo6 R1xUAJBI1exf7pJ wUMUE20YnOPxkJv j6FhVzzvyqBbkIx vr3x3RMY7R6Xr7X ONhZ7bZdQ8GhL5Z HSbg80GkE90ogX5 spBBF3DEp7QEn7P ETt3WjgSsPA7ebQ YeaQaVXhoJvefXT 0O2cTFPLRrSxQjM IV431aA7bHRDBo8 14BSvqPE5NYJQD5 xHMfaCHAEcoQTCs Ea3l7tJuShGNKV8 mBI6. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by strib** [comment]
@iJusty: I deleted the folder from the file system.  You might still see a rekey notification or badge about it until the next time we deploy our server, but it should go away in a day or two.

**Comment by iJusty** [comment]
ok.
seems folder is deleted.
thanks!
