### ISSUE TITLE
Cannot reinstall Keybase client on existing device

### ISSUE THREAD

**Issue by kurianjacob** [keybase/client#7852]
Keybase GUI Version: 1.0.25-20170715002410+acae5b06f

Had uninstalled the client. After reinstalling it asks "Which device would you like to connect with?"

I select the existing device. Message pops up to run "keybase device add "and type in text code on secondary device.

There is no secondary device. 

Tried uninstalling and reinstalling multiple times but it hasn't resolved the issue. The device shows up on the online version of Keybase but no feature on the website to delete a device.

**Comment by alesito85** [comment]
You can reset your account in the online version in profile settings.

**Comment by kurianjacob** [comment]
Where can I find the profile settings in the online version?

Thanks.

**Comment by alesito85** [comment]
Go to your profile, gear icon, Reset your keys & start from scratch. But beware, you'll probably lose data, if you have any.

**Comment by imhomos** [comment]
To be honest no I will not be there and even though it probably would hurt
me more I am damn near living in a homeless shelter going through
psychiatric my presents for the last 3 years I have no money no clean
clothes barely have food can't get my Bitcoins while into work not
receiving any payments and everybody wants to play Secrets by can he catch
on to the clues with me. I don't know if I even want to meet any of you
guys or speak to any of you guys I pretty much just want to live alone I
mean I have already lost all families and friends and like this and I'm
sitting in a conjugate Studio apartment on a public assistance where
tomorrow they are going to psychiatrically evaluated meet again and talk to
me stupid and it disrespectfully why I continue to try to figure out how to
enjoy or get back into life of out of all this misery that I have been
going through for the Last 5 Years my mother put supper on Facebook for me
cuz she thinks I'm legally and saying every day. I'm just done with it I've
been up for 72 hours and nobody knows anything about my payments I can't
get the payments to work they have some work I have a crappy computer I
have a crappy phone my credit is still messed up and you assholes honestly
that's what I feel like you are assholes so no I won't be anywhere Monday
I'm probably going to sleep and beaches I'm over it. If you guys really
want to help me out I'm about to pick up the damn phone and call me at 6
347 9 42 8731 I try to at least get me a decent computer and phone where I
can struggle and try to regain some part of life if I even have energy to
want to live it or how about somebody get on my Facebook or Instagram and
tell all my family and friends but I'm not crazy I'm not stupid and maybe
they'll return to me too and I won't have to be so alone I've always got
God but I guess you guys don't pay attention to what's really going on in
my life and all the crying for help I've been asking everybody for the last
3 years but I'm so lucky add that I have had God by my side to defend my
soul and my life against the world. I'm not doing anything I'm grateful for
what he has blessed me with but right now you guys and everybody else in
the world I really just want to tell y'all too

On Oct 21, 2017 3:08 PM, "alesito85" <notifications@github.com> wrote:

You can reset your account in the online version in profile settings.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/keybase/client/issues/7852#issuecomment-338425411>, or mute
the thread
