### ISSUE TITLE
build failed under arch linux

### ISSUE THREAD

**Issue by JR1994** [keybase/client#7881]
I am getting the following error when trying the build under Arch

    linux-x64 finished!
    null
    Done in 258.20s.
    Building client for 386...
    # runtime/cgo
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib/libpthread.so when  searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /lib/../lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /lib/../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../libpthread.a when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
    /usr/bin/ld: cannot find -lpthread
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /lib/../lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /usr/lib/../lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/../../../libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: cannot find libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    collect2: error: ld returned 1 exit status
    ==> ERROR: A failure occurred in build().
        Aborting...
    :: failed to build keybase-git package(s)

I am still new to programing but it looks like it trying to build 32bit client and failing.

**Comment by oconnor663** [comment]
Ah what's probably happening is that the cgo steps we added to the build recently are requiring 32-bit versions of various libs for the 32-bit binaries. Though of course, we shouldn't be building 32-bit binaries on most people's machines _at all_, so instead of adding more dependencies we should just disable that part of the build. I should be able to get to that today.

**Comment by oconnor663** [comment]
As an aside, any reason you're using `keybase-git` and not `keybase-bin`? The latter is much more convenient and slightly more stable, if you don't care about building from source.

**Comment by oconnor663** [comment]
@JR1994 could you try it again now?

**Comment by JR1994** [comment]
Yes it builds now. I want to the git version mostly for times like this. I
want to see if I can at least understand why the build is failing.

**Comment by oconnor663** [comment]
The previous build failure would probably have been fixed by installing `lib32-glibc` and `lib32-gcc-libs` from the [official `multilib` repo](https://wiki.archlinux.org/index.php/Multilib). There might've been other things missing too; it's hard to know without trying it. Now that the i386 build has been disabled in the `keybase-git` package, if you want to try to repro this again, you'll need to run that part of the build manually. You can do it like this:

```bash
git clone https://github.com/keybase/client
cd client/go/keybase
GOARCH=386 CGO_ENABLED=1 go build
```
