### ISSUE TITLE
upd.exe reported as malware by 11/63 on VirusTotal

### ISSUE THREAD

**Issue by aronconi** [keybase/client#7908]
As per attached screenshot, upd.exe is being reported as malware by 11 out of 63 vendors on VirusTotal.  Please look into this file to determine if there is an issue with it or if this is a false positive.

Keybase GUI Version: 1.0.26-20170724101459+b095a79
![2017-07-26_14-16-22](https://user-images.githubusercontent.com/9482526/28637344-384c02e6-720f-11e7-8682-7765579dbabb.png)

**Comment by maxtaco** [comment]
cc @zanderz

**Comment by zanderz** [comment]
We sign each executable with an EV certificate issued by DigiCert, a Microsoft approved vendor. If you are using an antivirus product which interferes with the legitimate software you are trying to run, we urge you to take it up with your AV vendor. We try to submit false positives, but it is not always possible if you are not a customer.

**Comment by kkarhan** [comment]
these errors are generic / heuristics errrors caused by the fact that the application may download stuff and write it on disk.

As the name implies, this is mostly caused by stupid engines & their sandbox analysis being paranoid as hell.

Protip: verify the certificate of the file and it's checksum.

AV vendors are just a******* when it comes to support. Guess why there's a heated debate about the whether AV scanners are actually useful or just bloatware.

Common sense should tell that the only implementation that could be anything more than some ugly binary kernel hack is from the OS vendor [i.e. Microsoft] himself.
Some scanners even act maliciously as transparent proxies and MitM connections, such as  HTTPS, IMAPS and SMTPS, causing certificate errors all over the place with their nasty, self-signed and/or unmatching certificates. Some even go so far as to add themselves into the system certificate storage - something that should be considered malicious behaviour by any application.

But since this likely only appears to be a problem on Windows, it's the least problem there, since the entire CryptoAPI is backdoored with automated and autonomous certificate updates. Making any application insecure that does rely on it (i.e. Chrome & Opera - Firefox doesn't since it has it's own Crypto API [NSS] and own certificate storage!)...

**Comment by AramZS** [comment]
Wanted to add to this that Microsoft Security Essentials doesn't mark upd.exe as a virus but does ask to look at it for additional analysis. 
![image](https://user-images.githubusercontent.com/748069/57861361-72831780-77c4-11e9-8f35-e81855347f7e.png)

**Comment by pzduniak** [comment]
@AramZS I've contacted MSE regarding this issue. I'll update this ticket when I receive an response.

**Comment by pzduniak** [comment]
>We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>
>1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>3. Run "MpCmdRun.exe -SignatureUpdate"
>
>Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
>
>Thank you for contacting Microsoft.
