### ISSUE TITLE
Recover files after reset with paper key

### ISSUE THREAD

**Issue by ag14774** [keybase/client#8109]
Hi,

I recently reset my account but I lost access to all my files. I have my old paper key. Is it possible to recover my files? I have a folder that is called "...files before account reset.." or something but it says that I do not have access when I try to open it. 

Any help would be appreciated.

Thanks

**Comment by strib** [comment]
Hi @ag14774, we have not built a way to recover files using a paper key, and I'm not sure it's actually possible.  Even if it were, it would be pretty hard for us to build a way to do that securely since an account reset is effectively saying: "all the keys associated with the old account are being revoked", and trusting a revoked key is bad news.

The "files before account reset" folders are pretty useless for your private folder, I agree.  They are more for the case of shared folders.

We probably need to give you better warnings about potential data loss before letting you reset your account.  Sorry we can't be of more help after the fact.

**Comment by ag14774** [comment]
Ok no problem. Is it possible to reset the filesystem so that those folders disappear. It doesn't let me delete them

**Comment by strib** [comment]
You're asking about the "files before account reset" folders?  You can "un-favorite" them so they don't show up in your list anymore with `rmdir /keybase/private/ageorgiou (files before account reset ...)"` (using the full date in the folder name, I don't know it offhand).  That assumes you're on mac/Linux.  Windows should be similar with the command that deletes directories.

**Comment by ag14774** [comment]
That worked thanks!
