### ISSUE TITLE
Keybase appears to hang/panic when rekeying shared private folder with conflicts

### ISSUE THREAD

**Issue by pwestling** [keybase/client#8188]
I recently revoked a device. The keybase app began rekeying all my kbfs files, but seemed to hang for a particular private shared folder. An OS notification pops up every 5 seconds or so telling me that keybase is rekeying the folder:

![image](https://user-images.githubusercontent.com/1170414/29594402-83178640-8765-11e7-9b8f-b31937f5de20.png)

The logs feature some kind of panic that seems to be related to the fact that my folder with this other user had a conflict. Any help with this issue is greatly appreciated! The notification is quite annoying -.-

my log id: 874579acbde05c1f6ddf8f1c

**Comment by strib** [comment]
Hrm, I will look into this tonight if I get the chance. Sorry for the inconvenience.

**Comment by pwestling** [comment]
Thanks so much for the quick response! I can just quit the app in the meantime.

**Comment by strib** [comment]
It looks like our code got pretty confused when the folder-level conflict happened due to some bug I haven't figured out yet, and now there's some data on your local disk that's inconsistent and screwing everything up.

You can fix it by blowing away that local state for the conflict folder.  I doubt it will cause any major data loss for you, but if you are desperate to preserve anything in that conflict folder, you should copy it out before you do the next part, just in case.

1. Quit Keybase completely (sounds like you've done that).
2. run this command from the terminal: `rm -rf /Users/$USER/Library/Application Support/Keybase/kbfs_journal/v1/0120e97c27c41a6591c89a574c990a6dbf2f-2b098eeddce574c5/`
3. Restart Keybase

If that doesn't fix it, please let me know.

Also, I'm interested in knowing more about how you got into this state, but `keybase log send` only sends us a limited piece of the logs.  If you're willing to share your entire set of logs, I'd be grateful.  You can find your log directory by running `keybase status` and looking for one of the "log:" lines.  Go into that directory and then: `tar -czf client8188.tgz keybase.kbfs*.log && cp client8188.tgz /keybase/private/strib@github,pwestling/`.  I'd appreciate it, thanks in advance!

**Comment by pwestling** [comment]
That fixed the issue! Thanks for the help. I can get you the more complete logs later tonight.

**Comment by pwestling** [comment]
Transferred the logs. Hope that helps!

**Comment by strib** [comment]
Hi @pwestling, thanks for that.  But I made a mistake in my command, it should have been this: `tar -czf client8188.tgz *kbfs* && cp client8188.tgz /keybase/private/strib@github,pwestling/`.  The one you made doesn't include all the logs unfortunately.  If you could run it again I'd appreciate it. Thanks!

**Comment by pwestling** [comment]
Done

**Comment by strib** [comment]
Thanks for the logs!   I think I figured out the problem, there should be a fix for future issues like this in the next release.
