### ISSUE TITLE
Requesting reset of KBFS

### ISSUE THREAD

**Issue by dtkerr** [keybase/client#8512]
Did an account reset - I still have an old paper key from pre-reset and had no issue getting my computer and phone both keyed up again afterward, but I have had an issue with KBFS - even after ignoring all the `(files before account reset...)` folders when trying to rekey with the old paper key I'm still getting an error about not having read access to the `(files before account reset...)` folders.

Sent some logs: 
my log id: a5e7d583ed5c0f79fad5301c

If you need to ask more question go ahead, but if that's enough to help me out this is signed with the PGP key on [my keybase account](https://keybase.io/dtkerr).

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

2017-09-18: Please reset my (keybase user dtkerr) folders as is appropriate for me to be able to rekey... or honestly if it's that much trouble just fully reset it, nothing important in there anyway.
-----BEGIN PGP SIGNATURE-----

iHUEARYIAB0WIQRc0Ehw4QtIpz7A2u70P661AcfhHAUCWcBONwAKCRD0P661Acfh
HFKzAQCN/vZ/27xkG7Sa2xN/frYphLF8XnbeRA9Y/lBBc3SWqwD/fxv94YgC536w
kbZGAI5ldte1qqIqr4wCWu6CMomPLA0=
=4gTy
-----END PGP SIGNATURE-----

**Comment by strib** [comment]
@dtkerr: The "files before account reset" folders are confusing, I know.  But your new, post-reset account are not _supposed_ to be able to read them.  If they are shared folders with other users, it's up to those users to copy the data into some new folder with you.  If it is a private folder for just you, I'm afraid the data is lost as a consequence of the account reset.

Arguably those "files before account reset" folders shouldn't be showing up in your list of folders anymore, since you can't read them.  We keep them there so you know to contact the other users about moving the data, if you want.  You can remove them from your list by calling `rmdir` on the folders you want removed.
