### ISSUE TITLE
Unable to access public folder after account reset

### ISSUE THREAD

**Issue by neersighted** [keybase/client#8832]
Hey there,

I appear to be experiencing something similar to #2090. After resetting my account, I can no longer use a public keybase folder. Instead, I get this:

    ls: reading directory '.': Input/output error

In addition, in my signature chain, the JS does not show an account reset. I believe that a reset should be shown at [#117](https://keybase.io/neersighted/sigchain#302af53357fc61e9db079aed592f522e103b685382af9b96585e544ca4ee7cd40f). Maybe it doesn't show because I used the same PGP key?

Anyway, if you could please help me get my public keybase folder working again, I would greatly appreciate it.

My log ID is: `9e5a7eb832cf83f8b25b981c`

My Keybase is: https://keybase.io/neersighted

**Comment by strib** [comment]
We discussed offline a bit and I gathered more logs from @neersighted (thank you!).  There was a rare bug in conflict resolution that caused the folder to be inaccessible.  The data would be recoverable with a little extra work, but we decided we will reset the folder since none of the data was needed.

**Comment by neersighted** [comment]
Thanks for the quick resolution @strib!
