### ISSUE TITLE
Cannot create a new account after deleting existing

### ISSUE THREAD

**Issue by igorkulman** [keybase/client#8900]
I deleted my account to start over because my account got broken and I could not add new devices. 

Now I cannot create the account again, because `Username XXX is unavailable. Pick again or login if that's you.`

but when I try to login I get `Error: Server failure: user deleted`

I also tried recovering password but got `user deleted`

**Comment by maxtaco** [comment]
Can’t reuse deleted accounts. We warned you.

**Comment by igorkulman** [comment]
Really this is your answer? That I should have read some warning that nobody reads? If my account did not get into a broken state I would never have had to do it.

**Comment by maxtaco** [comment]
What was wrong with your account?  How was it broken?

Sorry, we just don't have the resources to fix this issue at the moment. Keybase is different from the other apps you might be thinking of. We make heavy use of append-only data-structures to prevent service malice.  Undoing an operation is not a question of just changing a value in a database.

**Comment by Orbixx** [comment]
I never envisioned using Keybase again when I deleted my account, my usage of GPG turned out to be very, very seldom.

But the new chat service is something I would love to use, however just like the mentioned warning it seems like I can no longer use or re-register my old username.

I don't know how many users you could get to return by allowing username re-use, but I'd be very happy if this was accepted for inclusion in a future milestone.
