### ISSUE TITLE
Automatically join an open team

### ISSUE THREAD

**Issue by qbi** [keybase/client#9106]
When a team exists, one can set it to open. As far as I understand it, open means that anyone can join with the pre-defined role (`--join-as`). I created a team and edited the settings: `keybase team settings --set-open --join-as=reader teamname`. But when people tried to join with `keybase team request-access teamname`, I had to manually accept them. IMHO it should be possible that people automatically join teams.

**Comment by maxtaco** [comment]
this is a very new feature.  @zapu can you take a look?

**Comment by zapu** [comment]
The concept behind open teams is that the teams are open to join by anyone at any time, but they are still end-to-end encrypted. So when someone joins an open team using `team request-access`, a notification is sent to one of admins' devices to automatically add them in, without user interaction. This should be very quick given there is an online admin device - that's why we also encourage people to install Keybase on their mobile phones.

I don't know if there is actual bug here or not. Also your friends has probably seen old `team request-access` message - there was a fix few days ago which changed it to say different things whether you are requesting access to closed team or open team, but it's not released yet.

**Comment by qbi** [comment]
@zapu Thanks for your comment. It helped me to better understand the concept behind open teams. I'll close the issue. However maybe it is possible to add some more words into the `--help` to make sure also other people understand it better.

Furthermore please have a look at #9107. I got no indicator when other people joined.
