### ISSUE TITLE
1.9GB new git repo is stuck while uploading > 4 hours (and still going on)

### ISSUE THREAD

**Issue by vraravam** [keybase/client#9113]
<img width="664" alt="screen shot 2017-10-18 at 10 15 51 pm" src="https://user-images.githubusercontent.com/69629/31731257-14585e9a-b452-11e7-8d1c-928d1f14a584.png">
my log id: e819e76f9a2c8c5e2a19361c

**Comment by strib** [comment]
Hi @vraravam: oof, sorry for the bad experience.  From the logs, this looks like the same race as #8915, and it should be fixed in master (but not yet released).

I can't think of a good way to salvage the long-running process unfortunately.  You might have to shut it down and try again, and hopefully you won't hit the same race.  I'm sorry for the inconvenience.

**Comment by vraravam** [comment]
@strib - tx. I killed the process - and restarted, and it went through successfully. Must have been the same race condition. Hope your commit fixes the issue. We can close this ticket if you want.

**Comment by strib** [comment]
Great, thanks for your patience!
