### ISSUE TITLE
subteam kbfs sync

### ISSUE THREAD

**Issue by jamesbcook** [keybase/client#9123]
subteam folder doesn't seem to be syncing for me anymore. looks to work with the
 rest of the group, but not for me. I've rebooted and restarted the application
multiple times.

my log id: cdc53a3a0ebf7142df08ce1c

**Comment by strib** [comment]
It looks like this is the same issue as #9034, and will be fixed in the next release (hopefully this week?). If you'd like to fix it sooner, the user whose data has not been synchronized should try installing this experimental build, which worked for another user: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-1.0.34-20171013234544%2B8bdf88aed.dmg.

**Comment by jamesbcook** [comment]
Looks like everything is syncing now. Thanks!
