### ISSUE TITLE
[Feature Request] disappearing messages

### ISSUE THREAD

**Issue by jamesbcook** [keybase/client#9137]
It would be nice to have messages disappear or delete after a set time determined by the user. This may be similar to the way Signal works.

**Comment by mutagenfork** [comment]
Yes, it would be great if Keybase had this feature.   "disappearing messages" are useful for discussing sensitive topics that you don't necessarily want to be exposed, should your laptop/phone be stolen, seized at at border crossing, hacked, etc.

**Comment by micahflee** [comment]
Just wanted to add that I would love this feature as well. The fact that Keybase teams and chat are zero knowledge is excellent, but it doesn't allow for having any sort of data retention policies.

Ideally, each team channel, and each one-on-one conversation, should have its own retention settings. For example, you may want #general to retain messages for a 3 months, but #security to retain messages for one week. It would be cool to have a team-wide setting for the max retention time allowed in that team.

And likewise, it would be nice to be able to set direct message conversations to retain messages for 1 week, or 1 day, rather than forever, if I'd like.

This would also help with the problem of new members of a team having access to all of the old conversations. Maybe you don't want new team members to be able to go back years in the chat history and read all of the old stuff.

**Comment by icco** [comment]
+1 to what @michahflee said. Disappearing messages / data retention policies are a hard requirement for us adopting keybase team chat as an org.

**Comment by jamesbcook** [comment]
This has been added https://keybase.io/blog/keybase-exploding-messages
