### ISSUE TITLE
Private Folder no longer sync'd with other devices

### ISSUE THREAD

**Issue by mbaladjay** [keybase/client#9333]
My Work PC (Windows 8.1) no longer seems to be in sync with my HOME (MacOS High Sierra 12.13) device.
Any changes done on my Work PC does not seem to be updated on my HOME PC.
There are also some folders that appear to exist on Work PC but are empty and I am unable to delete either GUI or CLI.
Is it also possible to recover any files from the local cached files if they are not in sync?

my log id: d38f09456fcec7ac5e30321c

**Comment by strib** [comment]
Hi @mbaladjay, sorry for the bad experience.  It seems like your device `WORK-AV` has been in a "conflict" state for some time, due to a bug that was fixed in the latest update.  However, now that it is fixed, `WORK-AV` seems to be too far out of date and can't catch seem to catch up.

I think the best way to recover is to copy the data you want to save from `WORK-AV` out of the private folder and onto your local hard drive.  Once you're sure you have saved everything locally, do:

* Shut down the whole Keybase app, including the mounted drive.
* Rename the directory `%appdata%\Local\Keybase\kbfs_journal\v1\01205a0507361a229f25c86d93947b551175-f59b5054c08789a7` to some other name, say `conflict_folder_backup`.
* Restart the Keybase app.

After this, `WORK-AV` should be synced with your other devices, and you can drag the old data back into the folder.

Sorry for the inconvenience, hopefully you won't run into this again now that the original bug is fixed.

**Comment by mbaladjay** [comment]
Thanks for the help! It now appears to be back in sync, but will have to check that my Home device also sync's up with any changes from here.
It is not a big loss, but would it be possible to recovery any files in `conflict_folder_backup`

**Comment by strib** [comment]
@mbaladjay: the files in `conflict_folder_backup` are the ones I asked you to drag out of the private folder on `WORK-AV` _before_ you renamed the directory.  To restore them, just drag them back in. If you didn't save a copy before, you can stop Keybase,  rename the directory back to what it was called before, and restart Keybase, and you should be able to copy the old files out again.

**Comment by mbaladjay** [comment]
Sorry for the trouble. I had backed them up. It's good to know that some files could still be backed up if necessary. The `conflict_backup_folder` seems to be quite large (18GB) and the files that I could copy is no where near that size. 
When I restored the original folder name as suggested, I could see some folders that were 0 bytes size. If I try to delete the folder I would either get access denied via GUI or folder doesn't exist if I tried from CLI.
Anyway, I am not concerned about the loss of these files, so I will close the issue as both devices are now in sync.
Thanks again for the suggestions.
