### ISSUE TITLE
My private folder is inaccessible to myself

### ISSUE THREAD

**Issue by akatrevorjay** [keybase/client#9503]
Hi, not sure how this happened, but my private folder is unreadable and I'd appreciate it if you could reset it. My chats all work fine, it's just my private folder @ `/keybase/private/trevorj`.

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkHyb2MW x1cEgXSzjsUkVuz COOhKkGwpH3RPhv PTXCtyAAqwh9Zgs h1ZCyDss84Bd8HI eZfGTKw6Q5rRisQ 4lflhForH0x7Dan H6gnaT1UVV2B1xe GjGPlGMBUvCeeRm OqKBPIM3lBU53pB RW9jJsG4XIpCvMH nBbIhvtrXma6xMF mGFBF1KrCZCykTn FPKMqOkc9N2Ylfr 8XZCtzR1CDEDTFX sK7ZDH3wwZSnsFc Ly4P0Kf0tTBPMjQ kmrHmQd5puYI7cV urFLs32iBZiRfdN F7gWTB8CFDhPOuq VUCSdBSa8gpRtMg rgcSuXv5f24NcuN 6n7n15xTllmipn7 gu6G715thzu4chR Nr46wH4xojImQfC pZTXXAhpuGImLnI HevSGnOKygy6CIZ s6q5FUfMbR37RK0 OriRTIdkA7Kgc. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by akatrevorjay** [comment]
I was an early beta user, perhaps it's related? What's preventing me from viewing this is I've long ago replaced all devices I started using Keybase with (incrementally though), it's odd that this is allowed to happen to be honest.  graph: https://keybase.io/trevorj/graph

Perhaps we can offer to the user to reset if they are ever in a situation where it's impossible for them to repair it, namely in the case like mine, ala:
Offer to reset private folder if user does not have access to their private folder from any valid (non-revoked) device, thereby making recovery impossible.

Thoughts?

**Comment by strib** [comment]
Unfortunately I don't think I'll have time this weekend, but I'll look into it first thing Monday.

**Comment by strib** [comment]
@akatrevorjay: It seems your private folder is indeed only keyed for two devices that have been revoked: `hotel fine` and `beastlyfingerstiggers`.  The former was revoked on 5/27/16, on the same day that a new device `notsofatbookho` was added, but somehow that new device was never keyed into the folder.  That was so long ago that it could have been any of a number of bugs, now since fixed.  I'm sorry for the inconvenience.

I can definitely reset the folder, but the signed message above doesn't include the current date and time, and that's a requirement.  Please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/trevorj because all the devices that have access have been revoked."
```

and post the results here.

**Comment by akatrevorjay** [comment]
Sure, thanks so much. Also, no worries at all.

Here you go:
```BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkHyb2MW x1cEgXSzjsUkVuz COOhKkGwpH3RPhv PTXCtyAAqwo709a f9U6J2eezyyF2Nf cEt0bWn4UhSkApk lKiaZqL4PNKXCrA RwgUYqr0E7BJbzi k3tEFcJjQMDuNbK SdnviUQ0chQf9US 2QReZKaJo41TNRn dwBuLtoWGgqoazy PUcIveJrlImBw9l pENrXNym8qH9bGJ ihi1VdaGUF9fbPF CbfzTsaFLZVEMoR dfTRc0tl6kMbxTj XEUyfFusV4ONcWR pZvlzM2f3YGrYiH IRbREgiXJcu0plM 8zLW83dcBJD9edf WqnileyudUePPv0 Rsbu. END KEYBASE SALTPACK SIGNED MESSAGE.```

**Comment by strib** [comment]
@akatrevorjay: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by akatrevorjay** [comment]
Works great, ty!
