### ISSUE TITLE
Windows installation of KeyBase failed because Windows 7 not recognized

### ISSUE THREAD

**Issue by DK75019** [keybase/client#9557]
My computer has an Active License of Windows 7 (Edition familiale Premium) 
and the Windows Update is up to date,
but the install fails, I quote the pop-up message, "because your version of Windows is too old (W7 SP1 or newer required)".
Perhaps the log attached could be useful (I attach also the install exe I used)

PS : it is the first time an install gives me such an reason on this computer.

[Keybase_20171115002847.log](https://github.com/keybase/client/files/1472947/Keybase_20171115002847.log)

**Comment by zanderz** [comment]
The log shows no service pack is installed. How long ago did you install this Windows 7? A fresh install can take hours to fully update. Otherwise, your system is several years behind on updates.

The SP1 prerequisite is really only for the filesystem driver, which we have since made optional, so maybe we can ease up that restriction.

**Comment by DK75019** [comment]
About file system, my disk format is NTFS .
_I installed it since years and kept it updated (I can not confirmed if SP1 was installed because I have a bunch of PCs but it should be because it the one I use the most and care about)._
