### ISSUE TITLE
Is it possible to login using PGP key?

### ISSUE THREAD

**Issue by tyrion** [keybase/client#9716]
Hello, I have other devices connected to keybase, but I was wondering if it was possible to login from a new device using my either passphrase or the pgp private key linked with my account (which is currently imported locally in gpg).

Thanks

**Comment by maxtaco** [comment]
It used to be, but no longer. You can provision your first device with GPG, but not your second, third, etc.  It's because all of your devices share a secret that is not encrypted for GPG.  We made that decision explicitly since GPG encryption is all over the map, can be in a multiplicity of configurations, and just isn't as reliable as simple encryption via NaCl/Curve25519

**Comment by tyrion** [comment]
Ok, thanks for the quick answer. So, just to be sure I am understanding this correctly: every time I change/upgrade OS on a device I have to delete the old "device" and add a new one (with a new name)?
So, right now I am naming my devices with a number suffix like phone-02, or debian-01. Am I doing this right?

**Comment by maxtaco** [comment]
The phone is a different situation from the desktop, but in both cases, an OS upgrade should *not* kill your device provisioning.  The relevant files are kept in stable storage in your home dir.

The mobile case is slightly different because if you delete the app and reinstall the app, you will have to reprovision, since all data is lost from the first install.  For the desktop case, the config files persist, so you won't need to reprovision on app uninstall/reinstall.
