### ISSUE TITLE
1.0.45: New starting mechanism using systemctl --user doesn't work when users $HOME is on an AFS filesystem

### ISSUE THREAD

**Issue by heini** [keybase/client#9972]
systemd --user doesn't work with $HOME in /afs in general, there are systemd bug reports about this already. Maybe it would be better to revert to the old mechanism for starting things?

Long version: systemd --user bypasses the normal PAM stack when user logs in and instead tells the system 's systemd (PID 1) to spawn systemd --user processes for each user, which systemctl --user talks to. However, these systemd --user processes run through their own PAM stack which doesn't call any auth modules (just account and session, see /etc/pam.d/system-user). This leads to them having neither a kerberos ticket, nor an AFS token, both of which are required to get access to anything inside /afs.

**Comment by heini** [comment]
Seems there's now a fallback for situations where `systemd --user` is unavailable or doesn't work.

**Comment by heini** [comment]
OK, need to reopen, the script doesn't really work.

It runs `keybase config set mountdir` which in turn tries to start *keybase.service* using `systemctl --user` before even knowing whether this works at all. This the fails because `systemctl --user` runs in *degraded* mode.

It also doesn't handle this *degraded* mode of `systemctl --user` correctly. It treats *degraded* the same as *running*, which is wrong:
```
    status="$(systemctl --user is-system-running || true)"
    if [ "$status" = "running" ] || [ "$status" = "degraded" ] ; then
        return 0
    elif [ -z "$status" ] ; then
```
This should really be:
```
    status="$(systemctl --user is-system-running || true)"
    if [ "$status" = "running" ] ; then
        return 0
    elif [ "$status" = "degraded" ] || [ -z "$status" ] ; then
```
because *degraded* means "doesn't work", which is the case when $HOME is in AFS (or any other kerberized network filesystem.

**Comment by heini** [comment]
> Sorry, I missed this. In the future please make a new issue if you need to re-open after a long time,
> otherwise no one will get notified.

OK, wasn't aware of this. Will do next time...
 
> I'll look at this more after the holidays, but as I understand it, systemd user manager doesn't
> work on AFS?

Yes, when the user's $HOME is below /afs. This is because systemd --user itself is not started from the user session, but from systemd (PID 1) and thus doesn't belong to the same process group and never get's a token to access anything inside /afs (root is NOT a special user there). See the link in my previous message.
 
> Your fix seems reasonable though, I'll have to look into it.

Sounds great.

> As a workaround for now, could you try exporting `KEYBASE_SYSTEMD=0` before `run_keybase`
> to signal that it isn't wanted?

Tried, and it works. Thanks a lot.

**Comment by heronhaye** [comment]
What is the output of 
```
systemctl --user is-active init.scope 
```
for you? I'm thinking of changing the logic to that. The problem with `systemctl --user is-system-running` is that it returns degraded if any unit is failing.

**Comment by heini** [comment]
Unfortunately this prints out `active` in both cases.

**Comment by heronhaye** [comment]
`systemctl --user status dbus.service` too?

**Comment by heronhaye** [comment]
Sorry, just to make sure, also `systemctl --is-active dbus`?

**Comment by heini** [comment]
Looks like the best option:
```
% systemctl is-active dbus 
active
% systemctl --user is-active dbus
inactive
```

**Comment by heronhaye** [comment]
Great, thanks for the help. We'll get this in in the next Linux release. Thanks for the report!

**Comment by heronhaye** [comment]
Hey, glad to hear it's working out. We did have that `dbus` check in for a while and it ended up causing false positives for systems where the user manager was supported. Unfortunately I couldn't really come up with a better solution, so the next release will revert that change. Of course, `KEYBASE_SYSTEMD=0` will still work to disable systemd startup.

The reason we support systemd is because it gives the user much greater control over how Keybase runs on their system. With systemd they can restart, stop, and start all of the keybase processes independently, configure some subset to start at boot or remain running after logout, make custom rules with drop-in config files, etc.

Not all users need that level of control, so we provide `run_keybase` which should do the right thing automatically, but unfortunately not in your specific case.

Please make another issue if `KEYBASE_SYSTEMD=0` ever stops working or for other bugs as well. Thanks!
